export const inventoryPurchaseOrderActionTypes = {
  // addInventoryPurchaseOrder
  ADD_INVENTORY_PURCHASE_ORDER_REQUEST: 'ADD_INVENTORY_PURCHASE_ORDER_REQUEST',
  ADD_INVENTORY_PURCHASE_ORDER_SUCCESS: 'ADD_INVENTORY_PURCHASE_ORDER_SUCCESS',
  ADD_INVENTORY_PURCHASE_ORDER_FAILURE: 'ADD_INVENTORY_PURCHASE_ORDER_FAILURE',

  // deletePurchaseOrder
  DELETE_PURCHASE_ORDER_REQUEST: 'DELETE_PURCHASE_ORDER_REQUEST',
  DELETE_PURCHASE_ORDER_SUCCESS: 'DELETE_PURCHASE_ORDER_SUCCESS',
  DELETE_PURCHASE_ORDER_FAILURE: 'DELETE_PURCHASE_ORDER_FAILURE',

  // getPurchaseOrderList
  GET_PURCHASE_ORDER_LIST_REQUEST: 'GET_PURCHASE_ORDER_LIST_REQUEST',
  GET_PURCHASE_ORDER_LIST_SUCCESS: 'GET_PURCHASE_ORDER_LIST_SUCCESS',
  GET_PURCHASE_ORDER_LIST_FAILURE: 'GET_PURCHASE_ORDER_LIST_FAILURE',

  // searchInventoryPurchaseOrderVendor
  SEARCH_INVENTORY_PURCHASE_ORDER_VENDOR_REQUEST:
    'SEARCH_INVENTORY_PURCHASE_ORDER_VENDOR_REQUEST',
  SEARCH_INVENTORY_PURCHASE_ORDER_VENDOR_SUCCESS:
    'SEARCH_INVENTORY_PURCHASE_ORDER_VENDOR_SUCCESS',
  SEARCH_INVENTORY_PURCHASE_ORDER_VENDOR_FAILURE:
    'SEARCH_INVENTORY_PURCHASE_ORDER_VENDOR_FAILURE',

  // updateInventoryPurchaseOrder
  UPDATE_INVENTORY_PURCHASE_ORDER_REQUEST:
    'UPDATE_INVENTORY_PURCHASE_ORDER_REQUEST',
  UPDATE_INVENTORY_PURCHASE_ORDER_SUCCESS:
    'UPDATE_INVENTORY_PURCHASE_ORDER_SUCCESS',
  UPDATE_INVENTORY_PURCHASE_ORDER_FAILURE:
    'UPDATE_INVENTORY_PURCHASE_ORDER_FAILURE',
  SET_P_O_ERROR_FALSE: 'SET_P_O_ERROR_FALSE',
}
