const inventoryOverviewActionTypes = {
  // Fetch the cummilative data for inventory overview cards
  FETCH_AGGREGATED_DATA_REQUEST: 'FETCH_AGGREGATED_DATA_REQUEST',
  FETCH_AGGREGATED_DATA_SUCCESS: 'FETCH_AGGREGATED_DATA_SUCCESS',
  FETCH_AGGREGATED_DATA_FAILURE: 'FETCH_AGGREGATED_DATA_FAILURE',

  // Fetch the categories data for inventory overview tables
  FETCH_ALL_CATEGORIES_REQUEST: 'FETCH_ALL_CATEGORIES_REQUEST',
  FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
  FETCH_ALL_CATEGORIES_FAILURE: 'FETCH_ALL_CATEGORIES_FAILURE',

  // Fetch the categories data for inventory overview tables
  FETCH_ALL_ITEMS_REQUEST: 'FETCH_ALL_ITEMS_REQUEST',
  FETCH_ALL_ITEMS_SUCCESS: 'FETCH_ALL_ITEMS_SUCCESS',
  FETCH_ALL_ITEMS_FAILURE: 'FETCH_ALL_ITEMS_FAILURE',

  // Fetch Single Item
  FETCH_SINGLE_ITEM_BY_ID_REQUEST: 'FETCH_SINGLE_ITEM_BY_ID_REQUEST',
  FETCH_SINGLE_ITEM_BY_ID_SUCCESS: 'FETCH_SINGLE_ITEM_BY_ID_SUCCESS',
  FETCH_SINGLE_ITEM_BY_ID_FAILURE: 'FETCH_SINGLE_ITEM_BY_ID_FAILURE',

  // fetchAllItemsBySearchText
  FETCH_ALL_ITEM_BY_SEARCHTEXT_REQUEST: 'FETCH_ALL_ITEM_BY_SEARCHTEXT_REQUEST',
  FETCH_ALL_ITEM_BY_SEARCHTEXT_SUCCESS: 'FETCH_ALL_ITEM_BY_SEARCHTEXT_SUCCESS',
  FETCH_ALL_ITEM_BY_SEARCHTEXT_FAILURE: 'FETCH_ALL_ITEM_BY_SEARCHTEXT_FAILURE',

  //checkItemNameAvailability
  CHECK_ITEM_NAME_AVAILABILITY_REQUEST: 'CHECK_ITEM_NAME_AVAILABILITY_REQUEST',
  CHECK_ITEM_NAME_AVAILABILITY_SUCCESS: 'CHECK_ITEM_NAME_AVAILABILITY_SUCCESS',
  CHECK_ITEM_NAME_AVAILABILITY_FAILURE: 'CHECK_ITEM_NAME_AVAILABILITY_FAILURE',

  //checkCategoryNameAvailability
  CHECK_CATEGORY_NAME_AVAILABILITY_SUCCESS:
    'CHECK_CATEGORY_NAME_AVAILABILITY_SUCCESS',
  CHECK_CATEGORY_NAME_AVAILABILITY_FAILURE:
    'CHECK_CATEGORY_NAME_AVAILABILITY_FAILURE',
  CHECK_CATEGORY_NAME_AVAILABILITY_REQUEST:
    'CHECK_CATEGORY_NAME_AVAILABILITY_REQUEST',

  //createPrefix
  CREATE_PREFIX_REQUEST: 'CREATE_PREFIX_REQUEST',
  CREATE_PREFIX_SUCCESS: 'CREATE_PREFIX_SUCCESS',
  CREATE_PREFIX_FAILURE: 'CREATE_PREFIX_FAILURE',

  // addInventoryItem
  ADD_INVENTORY_ITEM_REQUEST: 'ADD_INVENTORY_ITEM_REQUEST',
  ADD_INVENTORY_ITEM_SUCCESS: 'ADD_INVENTORY_ITEM_SUCCESS',
  ADD_INVENTORY_ITEM_FAILURE: 'ADD_INVENTORY_ITEM_FAILURE',

  //searchInventoryCategory
  SEARCH_INVENTORY_CATEGORY_REQUEST: 'SEARCH_INVENTORY_CATEGORY_REQUEST',
  SEARCH_INVENTORY_CATEGORY_SUCCESS: 'SEARCH_INVENTORY_CATEGORY_SUCCESS',
  SEARCH_INVENTORY_CATEGORY_FAILURE: 'SEARCH_INVENTORY_CATEGORY_FAILURE',

  //searchInventoryItem
  SEARCH_INVENTORY_ITEM_REQUEST: 'SEARCH_INVENTORY_ITEM_REQUEST',
  SEARCH_INVENTORY_ITEM_SUCCESS: 'SEARCH_INVENTORY_ITEM_SUCCESS',
  SEARCH_INVENTORY_ITEM_FAILURE: 'SEARCH_INVENTORY_ITEM_FAILURE',

  //deleteInventoryItemCategory
  DELETE_INVENTORY_ITEM_CATEGORY_REQUEST:
    'DELETE_INVENTORY_ITEM_CATEGORY_REQUEST',
  DELETE_INVENTORY_ITEM_CATEGORY_SUCCESS:
    'DELETE_INVENTORY_ITEM_CATEGORY_SUCCESS',
  DELETE_INVENTORY_ITEM_CATEGORY_FAILURE:
    'DELETE_INVENTORY_ITEM_CATEGORY_FAILURE',

  //deleteInventoryItem
  DELETE_INVENTORY_ITEM_REQUEST: 'DELETE_INVENTORY_ITEM_REQUEST',
  DELETE_INVENTORY_ITEM_SUCCESS: 'DELETE_INVENTORY_ITEM_SUCCESS',
  DELETE_INVENTORY_ITEM_FAILURE: 'DELETE_INVENTORY_ITEM_FAILURE',

  //updateInventoryItemCategory
  UPDATE_INVENTORY_ITEM_CATEGORY_REQUEST:
    'UPDATE_INVENTORY_ITEM_CATEGORY_REQUEST',
  UPDATE_INVENTORY_ITEM_CATEGORY_SUCCESS:
    'UPDATE_INVENTORY_ITEM_CATEGORY_SUCCESS',
  UPDATE_INVENTORY_ITEM_CATEGORY_FAILURE:
    'UPDATE_INVENTORY_ITEM_CATEGORY_FAILURE',

  //updateInventoryItem
  UPDATE_INVENTORY_ITEM_REQUEST: 'UPDATE_INVENTORY_ITEM_REQUEST',
  UPDATE_INVENTORY_ITEM_SUCCESS: 'UPDATE_INVENTORY_ITEM_SUCCESS',
  UPDATE_INVENTORY_ITEM_FAILURE: 'UPDATE_INVENTORY_ITEM_FAILURE',

  //updateInventoryItemUnitCondition
  UPDATE_INVENTORY_ITEM_UNIT_CONDITION_REQUEST:
    'UPDATE_INVENTORY_ITEM_UNIT_CONDITION_REQUEST',
  UPDATE_INVENTORY_ITEM_UNIT_CONDITION_SUCCESS:
    'UPDATE_INVENTORY_ITEM_UNIT_CONDITION_SUCCESS',
  UPDATE_INVENTORY_ITEM_UNIT_CONDITION_FAILURE:
    'UPDATE_INVENTORY_ITEM_UNIT_CONDITION_FAILURE',

  //allocateItemsManually
  ALLOCATE_ITEMS_MANUALLY_REQUEST: 'ALLOCATE_ITEMS_MANUALLY_REQUEST',
  ALLOCATE_ITEMS_MANUALLY_SUCCESS: 'ALLOCATE_ITEMS_MANUALLY_SUCCESS',
  ALLOCATE_ITEMS_MANUALLY_FAILURE: 'ALLOCATE_ITEMS_MANUALLY_FAILURE',

  //allocateItemsAutomatically
  ALLOCATE_ITEMS_AUTOMATICALLY_REQUEST: 'ALLOCATE_ITEMS_AUTOMATICALLY_REQUEST',
  ALLOCATE_ITEMS_AUTOMATICALLY_SUCCESS: 'ALLOCATE_ITEMS_AUTOMATICALLY_SUCCESS',
  ALLOCATE_ITEMS_AUTOMATICALLY_FAILURE: 'ALLOCATE_ITEMS_AUTOMATICALLY_FAILURE',
  //EMPTY_BLACKLIST
  EMPTY_BLACKLIST: 'EMPTY_BLACKLIST',

  //PAGINATION
  SET_PAGE: 'SET_PAGE',
  SET_CURRENT_PAGE_REFERENCE: '  SET_CURRENT_PAGE_REFERENCE',
  SET_API_FILTER_DATA: 'SET_API_FILTER_DATA',
  SET_POSSIBLE_ALLOCATION_IDS: 'SET_POSSIBLE_ALLOCATION_IDS',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
  SET_SELECTED_FILTERS: 'SET_SELECTED_FILTERS',
}

export default inventoryOverviewActionTypes
