export const INSTITUTE_ACTIONS = {
  INSTITUTE_PROFILE_DATA_REQUEST: 'INSTITUTE_PROFILE_DATA_REQUEST',
  INSTITUTE_PROFILE_UPDATE_REQUEST: 'INSTITUTE_PROFILE_UPDATE_REQUEST',
  INSTITUTE_PROFILE_LOADER: 'INSTITUTE_PROFILE_LOADER',
  LOGO_UPLOAD_REQUEST: 'LOGO_UPLOAD_REQUEST',
}

export const STUDENT_ACTIONS = {
  STUDENT_PROFILE_DATA: 'STUDENT_PROFILE_DATA',
  STUDENT_PROFILE_FIELDS_DATA: 'STUDENT_PROFILE_FIELDS_DATA',
  STUDENT_LIST_GET_SUCCEEDED: 'STUDENT_LIST_GET_SUCCEEDED',

  STUDENT_PROFILE_DETAILS: 'STUDENT_PROFILE_DETAILS',
  STUDENT_PROFILE_DATA_REQUEST: 'STUDENT_PROFILE_DATA_REQUEST',

  STUDENT_PROFILE_ADD_REQUEST: 'STUDENT_PROFILE_ADD_REQUEST',
  STUDENT_PROFILE_UPDATE_REQUEST: 'STUDENT_PROFILE_UPDATE_REQUEST',

  STUDENT_PROFILE_UPDATE_SUCCESSFUL: 'STUDENT_PROFILE_UPDATE_SUCCESSFUL',

  STUDENT_PROFILE_LOADER: 'STUDENT_PROFILE_LOADER',
  STUDENT_DUPLICATE_LIST: 'STUDENT_DUPLICATE_LIST',
  STUDENT_PROFILE_DELETE: 'STUDENT_PROFILE_DELETE',
  STUDENT_LIST_REQUEST: 'STUDENT_LIST_REQUEST',
  STUDENT_DISPLAY_PIC_UPLOAD_REQUEST: 'STUDENT_DISPLAY_PIC_UPLOAD_REQUEST',
  STUDENT_PROFILE_UPDATE_FAILED: 'STUDENT_PROFILE_UPDATE_FAILED',
}

export const TEACHER_ACTIONS = {
  TEACHER_PROFILE_UPDATE_REQUEST: 'TEACHER_PROFILE_UPDATE_REQUEST',
  TEACHER_PROFILE_ADD_REQUEST: 'TEACHER_PROFILE_ADD_REQUEST',
  TEACHER_PROFILE_LOADER: 'TEACHER_PROFILE_LOADER',
  TEACHER_PROFILE_DATA: 'TEACHER_PROFILE_DATA',
  TEACHER_PROFILE_UPDATE_SUCCESSFUL: 'TEACHER_PROFILE_UPDATE_SUCCESSFUL',
  TEACHER_DUPLICATE_LIST: 'TEACHER_DUPLICATE_LIST',
  TEACHER_PROFILE_DELETE: 'TEACHER_PROFILE_DELETE',
  TEACHER_LIST_REQUEST: 'TEACHER_LIST_REQUEST',
  TEACHER_DISPLAY_PIC_UPLOAD_REQUEST: 'TEACHER_DISPLAY_PIC_UPLOAD_REQUEST',
  TEACHER_DISPLAY_PIC_UPLOAD_SUCCESS: 'TEACHER_DISPLAY_PIC_UPLOAD_SUCCESS',
  TEACHER_PROFILE_UPDATE_FAILED: 'TEACHER_PROFILE_UPDATE_FAILED',
}

export const ADMIN_ACTIONS = {
  ADMIN_PROFILE_UPDATE_REQUEST: 'ADMIN_PROFILE_UPDATE_REQUEST',
  ADMIN_PROFILE_LOADER: 'ADMIN_PROFILE_LOADER',
  ADMIN_PROFILE_DATA: 'ADMIN_PROFILE_DATA',
  ADMIN_PROFILE_UPDATE_SUCCESSFUL: 'ADMIN_PROFILE_UPDATE_SUCCESSFUL',
  ADMIN_PROFILE_UPDATE_FAILED: 'ADMIN_PROFILE_UPDATE_FAILED',
  ADMIN_PROFILE_ADD_REQUEST: 'ADMIN_PROFILE_ADD_REQUEST',
  ADMIN_PROFILE_DATA_REQUEST: 'ADMIN_PROFILE_DATA_REQUEST',
  ADMIN_PROFILE_DELETE: 'ADMIN_PROFILE_DELETE',
  ADMIN_LIST_REQUEST: 'ADMIN_LIST_REQUEST',
  ADMIN_DISPLAY_PIC_UPLOAD_REQUEST: 'ADMIN_DISPLAY_PIC_UPLOAD_REQUEST',
  ADMIN_DISPLAY_PIC_UPLOAD_SUCCESS: 'ADMIN_DISPLAY_PIC_UPLOAD_SUCCESS',
}

export const COMMON_ACTIONS = {
  DISPLAY_PIC_UPLOAD_SIGNED_URL_REQUEST:
    'DISPLAY_PIC_UPLOAD_SIGNED_URL_REQUEST',
  DISPLAY_PIC_UPLOAD_CLOUD_REQUEST: 'DISPLAY_PIC_UPLOAD_CLOUD_REQUEST',
  DISPLAY_PIC_UPLOAD_SIGNED_URL_SUCCESS:
    'DISPLAY_PIC_UPLOAD_SIGNED_URL_SUCCESS',
  DISPLAY_PIC_UPLOAD_SIGNED_URL_FAILED: 'DISPLAY_PIC_UPLOAD_SIGNED_URL_FAILED',
  DISPLAY_PIC_ATTACH_REQUEST: 'DISPLAY_PIC_ATTACH_REQUEST',
  DISPLAY_PIC_ATTACH_SUCCESS: 'DISPLAY_PIC_ATTACH_SUCCESS',
}
