export const AnnouncementActionType = {
  TITLE: 'TITLE',
  MESSAGE: 'MESSAGE',
  ANNOUNCEMENT_DRAFT_DATA_REQUEST: 'ANNOUNCEMENT_DRAFT_DATA_REQUEST',
  ADD_VOICE_NOTE: 'ADD_VOICE_NOTE',
  ADD_VOICE_NOTE_DURATION: 'ADD_VOICE_NOTE_DURATION',
  VOICE_RECORDING: 'VOICE_RECORDING',
  GET_SELECTED_USERS_LIST: 'GET_SELECTED_USERS_LIST',
  ANNOUNCEMENT_ID: 'ANNOUNCEMENT_ID',
}

export const CommonActionType = {
  SET_LOADER: 'SET_LOADER',
  SET_ACADEMIC_SESSION_ID: 'SET_ACADEMIC_SESSION_ID',
  SET_DRAFT_DATA: 'SET_DRAFT_DATA',
  COMMON_ANNOUNCEMENT_DRAFT_DATA_REQUEST:
    'COMMON_ANNOUNCEMENT_DRAFT_DATA_REQUEST',
  COMMON_FEEDBACK_DRAFT_DATA_REQUEST: 'COMMON_FEEDBACK_DRAFT_DATA_REQUEST',
  COMMON_POLL_DRAFT_DATA_REQUEST: 'COMMON_POLL_DRAFT_DATA_REQUEST',
  COMMON_DRAFT_DATA_REQUEST: 'COMMON_DRAFT_DATA_REQUEST',
  CHANNEL: 'CHANNEL',
  SEGMENTS: 'SEGMENTS',
  ATTACHMENT_FILE: 'ATTACHMENT_FILE',
  SELECTED_USERS: 'SELECTED_USERS',
  NODE_IDS: 'NODE_IDS',
  USER_FILTER_TAGS: 'USER_FILTER_TAGS',
  ANNOUNCEMENT_TYPE: 'ANNOUNCEMENT_TYPE',
  DURATION: 'DURATION',
  SET_IS_ANONYMOUS: 'SET_IS_ANONYMOUS',
  TOTAL_NO_OF_USERS: 'TOTAL_NO_OF_USERS',
  CREATE_NEW_COMMUNICATION: 'CREATE_NEW_COMMUNICATION',
  SET_CREATOR_ID: 'SET_CREATOR_ID',
  FETCH_POSTS_DATA_REQUEST: 'FETCH_POSTS_DATA_REQUEST',
  CREATE_NEW_COMMUNICATION_FAIL: 'CREATE_NEW_COMMUNICATION_FAIL',
  UPDATE_COMMUNICATION: 'UPDATE_COMMUNICATION',
  USER_FILTER_VISIBLE: 'USER_FILTER_VISIBLE',
  GET_USERS_LIST: 'GET_USERS_LIST',
  SET_USER_SEGMENT_LOADER: 'SET_USER_SEGMENT_LOADER',
  FETCH_USER_LIST_REQUEST: 'FETCH_USER_LIST_REQUEST',
  FETCH_UNCATEGORISED_CLASSES_DATA_REQUEST:
    'FETCH_UNCATEGORISED_CLASSES_DATA_REQUEST',
  FETCH_UNCATEGORISED_CLASSES_DATA_SUCCEEDED:
    'FETCH_UNCATEGORISED_CLASSES_DATA_SUCCEEDED',
  FETCH_UNCATEGORISED_CLASSES_DATA_FAIL:
    'FETCH_UNCATEGORISED_CLASSES_DATA_FAIL',
  DELETE_DRAFT_REQUEST: 'DELETE_DRAFT_REQUEST',
  DELETE_DRAFT_SUCCEEDED: 'DELETE_DRAFT_SUCCEEDED',
  DELETE_DRAFT_FAIL: 'DELETE_DRAFT_FAIL',
  SET_IS_POST_CREATED_OR_UPDATED: 'SET_IS_POST_CREATED_OR_UPDATED',
  SET_SELECTALL: 'SET_SELECTALL',
  SEND_REMINDER: 'SEND_REMINDER',
  FETCH_POST_RECEIVERS_LIST_REQUEST: 'FETCH_POST_RECEIVERS_LIST_REQUEST',
  FETCH_POST_RECEIVERS_LIST_SUCCESS: 'FETCH_POST_RECEIVERS_LIST_SUCCESS',
  FETCH_POST_RECEIVERS_LIST_FAILURE: 'FETCH_POST_RECEIVERS_LIST_FAILURE',
  EDIT_COMMUNICATION_POST: 'EDIT_COMMUNCATION_POST',
  REMOVE_POST: 'REMOVE_POST',
  EDIT_POST: 'EDIT_POST',
  REDIRECT_ON_SUCCESS: 'REDIRECT_ON_SUCCESS',
  REDIRECT_ON_CLOSE: 'REDIRECT_ON_CLOSE',
  SET_ATTACHMENT_URLS: 'SET_ATTACHMENT_URLS',
  SET_REQUEST_SIZE: 'SET_REQUEST_SIZE',
}

export const PollActionType = {
  QUESTION_OPTIONS: 'QUESTION_OPTIONS',
  IS_POLL_PUBLIC: 'IS_POLL_PUBLIC',
  SET_POLL_QUESTION: 'SET_POLL_QUESTION',
  SET_POLL_DRAFT_DATA: 'SET_POLL_DRAFT_DATA',
  SET_OPTION_VALUE: 'SET_OPTION_VALUE',
}

export const PostActionType = {
  FETCH_POSTS_DATA_REQUEST: 'FETCH_POSTS_DATA_REQUEST',
  FETCH_POSTS_DATA_SUCCEEDED: 'FETCH_POSTS_DATA_SUCCEEDED',
  FETCH_POSTS_DATA_FAIL: 'FETCH_POSTS_DATA_FAIL',
  POST_LIST: 'POST_LIST',
  FILTERED_POST_LIST: 'FILTERED_POST_LIST',

  CREATE_NEW_POST_REQUEST: 'CREATE_NEW_POST_REQUEST',
  CREATE_NEW_POST_SUCCEEDED: 'CREATE_NEW_POST_SUCCEEDED',
  CREATE_NEW_POST_FAIL: 'CREATE_NEW_POST_FAIL',

  IS_DELETE_POST_MODAL_OPEN: 'IS_DELETE_POST_MODAL_OPEN',
  POST_TITLE_FOR_DELETE: 'POST_TITLE_FOR_DELETE',
  POST_TO_DELETE_INFO: 'POST_TO_DELETE_INFO',
}

export const FeedbackActionType = {
  FEEDBACK_RESPONSES: 'FEEDBACK_RESPONSES',
  FETCH_FEEDBACK_RESPONSE_DATA_REQUEST: 'FETCH_FEEDBACK_RESPONSE_DATA_REQUEST',
  FETCH_FEEDBACK_RESPONSE_DATA_SUCCEEDED:
    'FETCH_FEEDBACK_RESPONSE_DATA_SUCCEEDED',
  FETCH_FEEDBACK_RESPONSE_DATA_FAIL: 'FETCH_FEEDBACK_RESPONSE_DATA_FAIL',
  SET_FEESBACK_RESPONSE_LOADER: 'SET_FEESBACK_RESPONSE_LOADER',

  SET_FEEDBACK_INFO: 'SET_FEEDBACK_INFO',
  SET_QUESTION: 'SET_QUESTION',
  SET_FEEDBACK_DRAFT_DATA: 'SET_FEEDBACK_DRAFT_DATA',
}

export const TabActionType = {
  TAB: 'TAB',
  SET_TAB: 'SET_TAB',
}

export const SliderActionTypes = {
  SET_SLIDER: 'SET_SLIDER',
}

export const ButtonActionEnableType = {
  SET_ENABLE: 'SET_ENABLE',
}

export const TemplateActionTypes = {
  GET_TEMPLATES: 'GET_TEMPLATES',
  SET_TEMPLATE_DATA: 'SET_TEMPLATE_DATA',
  SET_CURRENT_TEMPLATE: 'SET_CURRENT_TEMPLATE',
}

export const SaveDraftType = {
  SET_SAVE_DRAFT: 'SET_SAVE_DRAFT',
}

export const DefaultSegmentType = {
  SET_DEFAULT_SEGMENT: 'SET_DEFFAULT_SEGMENT',
}

export const SmsActionType = {
  GET_SMS_TEMPLATES: 'GET_SMS_TEMPLATES',
  SET_SMS_TEMPLATES: 'SET_SMS_TEMPLATES',
  SET_SMS_TEMPLATE_VARIABLES: 'SET_SMS_TEMPLATE_VARIABLES',
  SET_SELECTED_TEMPLATE_ID: 'SET_SELECTED_TEMPLATE_ID',
  GET_SMS_UNUSED_QUOTA: 'GET_SMS_UNUSED_QUOTA',
  SET_SMS_UNUSED_QUOTA: 'SET_SMS_UNUSED_QUOTA',
  SET_SMS_USED_QUOTA: 'SET_SMS_USED_QUOTA',
  SET_SMS_BODY: 'SET_SMS_BODY',
  ADD_USER_VARIABLES: 'ADD_USER_VARIABLES',
  SET_DISPLAY_UI_DATA: 'SET_DISPLAY_UI_DATA',
  SEND_SMS: 'SEND_SMS',
  SET_ALL_VARS_FILLED: 'SET_ALL_VARS_FILLED',
  GET_SMS_PREVIEW: 'GET_SMS_PREVIEW',
  SET_SMS_PREVIEW: 'SET_SMS_PREVIEW',
  SET_SMS_CREDIT_REQUIRED: 'SET_SMS_CREDIT_REQUIRED',
  GET_SMS_ORDER: 'GET_SMS_ORDER',
  CREATE_SMS_ORDER: 'CREATE_SMS_ORDER',
  VERIFY_SMS_ORDER: 'VERIFY_SMS_ORDER',
  SET_RECHARGE_OPEN: 'SET_RECHARGE_OPEN',
}

export const schedulerActionType = {
  UPDATE_RULE: 'UPDATE_RULE',
  FETCH_RULES_LIST: 'FETCH_RULES_LIST',
  SET_RULES_LIST: 'SET_RULES_LIST',
  FETCH_TEMPLATES: 'FETCH_TEMPLATES',
  SET_TEMPLATES: 'SET_TEMPLATES',
  TOGGLE_RULE_STATUS: 'TOGGLE_RULE_STATUS',
  DELETE_RULE: 'DELETE_RULE',
  FETCH_AUTOMATED_MESSAGES: 'FETCH_AUTOMATED_MESSAGES',
  SET_AUTOMATED_MESSAGES: 'SET_AUTOMATED_MESSAGES',
  FETCH_RULE_INSTANCES: 'FETCH_RULE_INSTANCES',
  SET_RULE_INSTANCES: 'SET_RULE_INSTANCES',
  TOGGLE_RULE_INSTANCES: 'TOGGLE_RULE_INSTANCES',
  TOGGLE_SCHEDULER_LOADER: 'TOGGLE_SCHEDULER_LOADER',
}
