export const inventoryStoreActionTypes = {
  //addInventoryItemStore
  ADD_INVENTORY_ITEM_STORE_REQUEST: 'ADD_INVENTORY_ITEM_STORE_REQUEST',
  ADD_INVENTORY_ITEM_STORE_SUCCESS: 'ADD_INVENTORY_ITEM_STORE_SUCCESS',
  ADD_INVENTORY_ITEM_STORE_FAILURE: 'ADD_INVENTORY_ITEM_STORE_FAILURE',

  //deleteInventoryItemStore
  DELETE_INVENTORY_ITEM_STORE_REQUEST: 'DELETE_INVENTORY_ITEM_STORE_REQUEST',
  DELETE_INVENTORY_ITEM_STORE_SUCCESS: 'DELETE_INVENTORY_ITEM_STORE_SUCCESS',
  DELETE_INVENTORY_ITEM_STORE_FAILURE: 'DELETE_INVENTORY_ITEM_STORE_FAILURE',

  //fetchInventoryStoreItems
  FETCH_INVENTORY_STORE_ITEMS_REQUEST: 'FETCH_INVENTORY_STORE_ITEMS_REQUEST',
  FETCH_INVENTORY_STORE_ITEMS_SUCCESS: 'FETCH_INVENTORY_STORE_ITEMS_SUCCESS',
  FETCH_INVENTORY_STORE_ITEMS_FAILURE: 'FETCH_INVENTORY_STORE_ITEMS_FAILURE',

  // getInventoryStoreList
  GET_INVENTORY_STORE_LIST_REQUEST: 'GET_INVENTORY_STORE_LIST_REQUEST',
  GET_INVENTORY_STORE_LIST_SUCCESS: 'GET_INVENTORY_STORE_LIST_SUCCESS',
  GET_INVENTORY_STORE_LIST_FAILURE: 'GET_INVENTORY_STORE_LIST_FAILURE',

  //searchInventoryItemStore
  SEARCH_INVENTORY_ITEM_STORE_REQUEST: 'SEARCH_INVENTORY_ITEM_STORE_REQUEST',
  SEARCH_INVENTORY_ITEM_STORE_SUCCESS: 'SEARCH_INVENTORY_ITEM_STORE_SUCCESS',
  SEARCH_INVENTORY_ITEM_STORE_FAILURE: 'SEARCH_INVENTORY_ITEM_STORE_FAILURE',

  //updateInventoryItemStore
  UPDATE_INVENTORY_ITEM_STORE_REQUEST: 'UPDATE_INVENTORY_ITEM_STORE_REQUEST',
  UPDATE_INVENTORY_ITEM_STORE_SUCCESS: 'UPDATE_INVENTORY_ITEM_STORE_SUCCESS',
  UPDATE_INVENTORY_ITEM_STORE_FAILURE: 'UPDATE_INVENTORY_ITEM_STORE_FAILURE',
}
