const GLOBAL_SETTINGS_ACTIONS = {
  GET_SETTINGS: 'GET_SETTINGS',
  SET_SETTINGS: 'SET_SETTINGS',
  POST_SETTINGS: 'POST_SETTINGS',
  SET_SELECTED_SETTING_CATEGORY: 'SET_SELECTED_SETTING_CATEGORY',
  SET_SELECTED_SETTING_SUB_CATEGORY: 'SET_SELECTED_SETTING_SUB_CATEGORY',
  POST_SETTING_SUCCESS: 'POST_SETTING_SUCCESS',
}

export default GLOBAL_SETTINGS_ACTIONS
