const feeStructureActionTypes = {
  // Fetch fee structure listing
  FETCH_FEE_STRUCTURES_REQUESTED: 'FETCH_FEE_STRUCTURES_REQUESTED',
  FETCH_FEE_STRUCTURES_SUCCEEDED: 'FETCH_FEE_STRUCTURES_SUCCEEDED',
  FETCH_FEE_STRUCTURES_FAILED: 'FETCH_FEE_STRUCTURES_FAILED',
  FETCH_PREVIOUS_SESSION_DUES: 'FETCH_PREVIOUS_SESSION_DUES',
  FETCH_PREVIOUS_SESSION_DUES_SUCCESS: 'FETCH_PREVIOUS_SESSION_DUES_SUCCESS',
  // Create fee structure
  CREATE_FEE_STRUCTURE_REQUESTED: 'CREATE_FEE_STRUCTURE_REQUESTED',
  CREATE_FEE_STRUCTURE_SUCCEEDED: 'CREATE_FEE_STRUCTURE_SUCCEEDED',
  CREATE_FEE_STRUCTURE_FAILED: 'CREATE_FEE_STRUCTURE_FAILED',

  // Get specific fee structure
  EDIT_FEE_STRUCTURE_REQUESTED: 'EDIT_FEE_STRUCTURE_REQUESTED',
  EDIT_FEE_STRUCTURE_SUCCEEDED: 'EDIT_FEE_STRUCTURE_SUCCEEDED',
  EDIT_FEE_STRUCTURE_FAILED: 'EDIT_FEE_STRUCTURE_FAILED',

  // Update fee structure
  UPDATE_FEE_STRUCTURE_REQUESTED: 'UPDATE_FEE_STRUCTURE_REQUESTED',
  UPDATE_FEE_STRUCTURE_SUCCEEDED: 'UPDATE_FEE_STRUCTURE_SUCCEEDED',
  UPDATE_FEE_STRUCTURE_FAILED: 'UPDATE_FEE_STRUCTURE_FAILED',

  // Delete fee structure
  DELETE_FEE_STRUCTURE_REQUESTED: 'DELETE_FEE_STRUCTURE_REQUESTED',
  DELETE_FEE_STRUCTURE_SUCCEEDED: 'DELETE_FEE_STRUCTURE_SUCCEEDED',
  DELETE_FEE_STRUCTURE_FAILED: 'DELETE_FEE_STRUCTURE_FAILED',

  // Fetch fee categories
  FETCH_FEE_CATEGORIES_REQUESTED: 'FETCH_FEE_CATEGORIES_REQUESTED',
  FETCH_FEE_CATEGORIES_SUCCEEDED: 'FETCH_FEE_CATEGORIES_SUCCEEDED',
  FETCH_FEE_CATEGORIES_FAILED: 'FETCH_FEE_CATEGORIES_FAILED',

  // Fetch used fee categories
  FETCH_USED_FEE_CATEGORIES_REQUESTED: 'FETCH_USED_FEE_CATEGORIES_REQUESTED',
  FETCH_USED_FEE_CATEGORIES_SUCCEEDED: 'FETCH_USED_FEE_CATEGORIES_SUCCEEDED',
  FETCH_USED_FEE_CATEGORIES_FAILED: 'FETCH_USED_FEE_CATEGORIES_FAILED',

  // Modify fee installments for Recurring and transport structures
  MODIFY_FEE_INSTALLMENT_REQUESTED: 'MODIFY_FEE_INSTALLMENT_REQUESTED',
  MODIFY_FEE_INSTALLMENT_SUCCEEDED: 'MODIFY_FEE_INSTALLMENT_SUCCEEDED',
  MODIFY_FEE_INSTALLMENT_FAILED: 'MODIFY_FEE_INSTALLMENT_FAILED',

  // Create new custom fee category
  ADD_NEW_CUSTOM_CATEGORY_REQUEST: 'ADD_NEW_CUSTOM_CATEGORY_REQUEST',
  ADD_NEW_CUSTOM_CATEGORY_SUCCEEDED: 'ADD_NEW_CUSTOM_CATEGORY_SUCCEEDED',
  SET_CUSTOM_CATEGORY_STATE: 'SET_CUSTOM_CATEGORY_STATE',

  // Fetch global fee settings
  FETCH_FEE_SETTING_REQUEST: 'FETCH_FEE_SETTING_REQUEST',
  FETCH_FEE_SETTING_SUCCEEDED: 'FETCH_FEE_SETTING_SUCCEEDED',
  FETCH_FEE_SETTING_FAILED: 'FETCH_FEE_SETTING_FAILED',

  // Fetch transport pickup points
  FETCH_TRANSPORT_PICKUP_POINTS_REQUEST:
    'FETCH_TRANSPORT_PICKUP_POINTS_REQUEST',
  FETCH_TRANSPORT_PICKUP_POINTS_SUCCEEDED:
    'FETCH_TRANSPORT_PICKUP_POINTS_SUCCEEDED',
  FETCH_TRANSPORT_PICKUP_POINTS_ERROR: 'FETCH_TRANSPORT_PICKUP_POINTS_ERROR',
  SET_TRANSPORT_STRUCTURE_TYPE: 'SET_TRANSPORT_STRUCTURE_TYPE',

  // Download fee structure report
  DOWNLOAD_FEE_STRUCTURE_REQUESTED: 'DOWNLOAD_FEE_STRUCTURE_REQUESTED',
  DOWNLOAD_FEE_STRUCTURE_SUCCEEDED: 'DOWNLOAD_FEE_STRUCTURE_SUCCEEDED',
  DOWNLOAD_FEE_STRUCTURE_FAILED: 'DOWNLOAD_FEE_STRUCTURE_FAILED',

  // Check receipt prefix exists
  RECEIPT_PREFIX_EXISTS_REQUESTED: 'RECEIPT_PREFIX_EXISTS_REQUESTED',
  RECEIPT_PREFIX_EXISTS_SUCCEEDED: 'RECEIPT_PREFIX_EXISTS_SUCCEEDED',
  RECEIPT_PREFIX_EXISTS_FAILED: 'RECEIPT_PREFIX_EXISTS_FAILED',

  // Previous year dues
  PREVIOUS_YEAR_DUES_REQUESTED: 'PREVIOUS_YEAR_DUES_REQUESTED',
  PREVIOUS_YEAR_DUES_SUCCEEDED: 'PREVIOUS_YEAR_DUES_SUCCEEDED',
  PREVIOUS_YEAR_DUES_FAILED: 'PREVIOUS_YEAR_DUES_FAILED',

  // Modify previous year dues
  MODIFY_PREVIOUS_YEAR_DUES_REQUESTED: 'MODIFY_PREVIOUS_YEAR_DUES_REQUESTED',
  MODIFY_PREVIOUS_YEAR_DUES_SUCCEEDED: 'MODIFY_PREVIOUS_YEAR_DUES_SUCCEEDED',
  MODIFY_PREVIOUS_YEAR_DUES_FAILED: 'MODIFY_PREVIOUS_YEAR_DUES_FAILED',

  // // Fetch fee webinar status
  FETCH_FEE_WEBINAR_STATUS: 'FETCH_FEE_WEBINAR_STATUS',
  FETCH_FEE_WEBINAR_STATUS_SUCCESS: 'FETCH_FEE_WEBINAR_STATUS_SUCCESS',
  FETCH_FEE_WEBINAR_STATUS_FAIL: 'FETCH_FEE_WEBINAR_STATUS_FAIL',

  // revoke fee receipts transactions (Bulk receipts delete)
  REVOKE_FEE_RECEIPTS_TRANSACTIONS_REQUEST:
    'REVOKE_FEE_RECEIPTS_TRANSACTIONS_REQUEST',

  // import dues from previous session
  IMPORT_PREVIOUS_SESSION_DUES_REQUESTED:
    'IMPORT_PREVIOUS_SESSION_DUES_REQUESTED',
  IMPORT_PREVIOUS_SESSION_DUES_FAILED: 'IMPORT_PREVIOUS_SESSION_DUES_FAILED',
  DELETE_STUDENT_PREVIOUS_SESSION_DUES: 'DELETE_STUDENT_PREVIOUS_SESSION_DUES',
  DELETE_STUDENT_PREVIOUS_SESSION_DUES_SUCCESS:
    'DELETE_STUDENT_PREVIOUS_SESSION_DUES_SUCCESS',
  FETCH_IMPORTED_SESSION_DUE_DATA: 'FETCH_IMPORTED_SESSION_DUE_DATA',
  FETCH_FAILED_SESSION_TRANSFER_TASK: 'FETCH_FAILED_SESSION_TRANSFER_TASK',
  FETCH_IMPORTED_SESSION_DUE_DATA_SUCCEEDED:
    'FETCH_IMPORTED_SESSION_DUE_DATA_SUCCEEDED',
  FETCH_FAILED_SESSION_TRANSFER_TASK_SUCCEEDED:
    'FETCH_FAILED_SESSION_TRANSFER_TASK_SUCCEEDED',
  ACKNOWLEDGE_FAILED_TASK: 'ACKNOWLEDGE_FAILED_TASK',
}

export default feeStructureActionTypes
