export const FEE_TAB_ACTION_TYPES = {
  FEE_UPDATE_HISTORY_REQUEST: 'FEE_UPDATE_HISTORY_REQUEST',
  FEE_UPDATE_HISTORY_SUCCESS: 'FEE_UPDATE_HISTORY_SUCCESS',
  SET_STUDENT_PROFILE_FEE_TAB_STATE: 'SET_STUDENT_PROFILE_FEE_TAB_STATE',
  SET_UPADATE_HISTORY_STATE: 'SET_UPADATE_HISTORY_STATE',
  STUDENT_PROFILE_FEE_TAB_DETAILS_REQUEST:
    'STUDENT_PROFILE_FEE_TAB_DETAILS_REQUEST',
  SET_STUDENT_PROFILE_FEE_SUMMARY_STATE:
    'SET_STUDENT_PROFILE_FEE_SUMMARY_STATE',
  STUDENT_PROFILE_FEE_TAB_SUMMARY_REQUEST:
    'STUDENT_PROFILE_FEE_TAB_SUMMARY_REQUEST',
  SET_STUDENT_PROFILE_FEE_INSTALLMENT_WISE_DETAILS_STATE:
    'SET_STUDENT_PROFILE_FEE_INSTALLMENT_WISE_DETAILS_STATE',
  SET_STUDENT_PROFILE_FEE_INSTALLMENT_WISE_DETAILS_REQUEST:
    'SET_STUDENT_PROFILE_FEE_INSTALLMENT_WISE_DETAILS_REQUEST',

  STUDENT_PROFILE_PAYMENT_HISTORY_REQUEST:
    'STUDENT_PROFILE_PAYMENT_HISTORY_REQUEST',
  SET_STUDENT_PROFILE_PAYMENT_HISTORY_STATE:
    'SET_STUDENT_PROFILE_PAYMENT_HISTORY_STATE',

  STUDENT_PROFILE_DISCOUNT_TILL_DATE_REQUEST:
    'STUDENT_PROFILE_DISCOUNT_TILL_DATE_REQUEST',
  SET_STUDENT_PROFILE_DISCOUNT_TILL_DATE_STATE:
    'SET_STUDENT_PROFILE_DISCOUNT_TILL_DATE_STATE',

  STUDENT_PROFILE_WALLET_TAB_STATE: 'STUDENT_PROFILE_WALLET_TAB_STATE',

  STUDENT_PROFILE_WALLET_SUMMARY_REQUEST:
    'STUDENT_PROFILE_WALLET_SUMMARY_REQUEST',
  SET_STUDENT_PROFILE_WALLET_SUMMARY_STATE:
    'SET_STUDENT_PROFILE_WALLET_SUMMARY_STATE',

  SET_STUDENT_PROFILE_FEE_AND_WALLET_STATE_RESET:
    'SET_STUDENT_PROFILE_FEE_AND_WALLET_STATE_RESET',

  STUDENT_PROFILE_WALLET_MAKE_REFUND_REQUEST:
    'STUDENT_PROFILE_WALLET_MAKE_REFUND_REQUEST',

  SET_STUDENT_PROFILE_WALLET_REFUND_STATE:
    'SET_STUDENT_PROFILE_WALLET_REFUND_STATE',
}
