export const feeFineActionTypes = {
  SET_FEE_FINE_STATES: 'SET_FEE_FINE_STATES',
  RESET_FEE_FINE_STATES: 'RESET_FEE_FINE_STATES',
  FETCH_FEE_FINE_RULES: 'FETCH_FEE_FINE_RULES',
  SAVE_RULE_CONFIGURATION_REQUEST: 'SAVE_RULE_CONFIGURATION_REQUEST',
  FETCH_FEE_FINE_STUDENT_LISTING_REQUEST:
    'FETCH_FEE_FINE_STUDENT_LISTING_REQUEST',
  FETCH_FEE_FINE_STUDENT_LISTING_SUCEESS:
    'FETCH_FEE_FINE_STUDENT_LISTING_SUCEESS',
  DELETE_FEE_FINE_RULE: 'DELETE_FEE_FINE_RULE',
}
