export const ProfileSettingsActionTypes = {
  SET_GENERAL_PROFILE_SETTINGS_LOADER: 'SET_GENERAL_PROFILE_SETTINGS_LOADER',

  // Get Profile Settings Action Types
  GET_PERSONA_PROFILE_SETTINGS: 'GET_PERSONA_PROFILE_SETTINGS',
  PERSONA_PROFILE_SETTINGS_GET_SUCCEEDED:
    'PERSONA_PROFILE_SETTINGS_GET_SUCCEEDED',
  PERSONA_PROFILE_SETTINGS_GET_FAILED: 'PERSONA_PROFILE_SETTINGS_GET_FAILED',

  GET_PERSONA_WISE_CATEGORIES: 'GET_PERSONA_WISE_CATEGORIES',
  PERSONA_WISE_CATEGORIES_GET_SUCCEEDED:
    'PERSONA_WISE_CATEGORIES_GET_SUCCEEDED',
  PERSONA_WISE_CATEGORIES_GET_FAILED: 'PERSONA_WISE_CATEGORIES_GET_FAILED',

  // Add Category Form Submit Action Types
  ADD_CATEGORY_FORM_SUBMIT_REQUEST: 'ADD_CATEGORY_FORM_SUBMIT_REQUEST',
  ADD_CATEGORY_FORM_SUBMIT_SUCCEEDED: 'ADD_CATEGORY_FORM_SUBMIT_SUCCEEDED',
  ADD_CATEGORY_FORM_SUBMIT_FAILED: 'ADD_CATEGORY_FORM_SUBMIT_FAILED',

  // Get Category and Their Fields Settings Data
  GET_CATEGORY_AND_FIELDS_SETTINGS_DATA:
    'GET_CATEGORY_AND_FIELDS_SETTINGS_DATA',

  // Get Persona wise Document categories fetch
  GET_DOCUMENT_CATEGORIES_REQUEST: 'GET_DOCUMENT_CATEGORIES_REQUEST',
}
