const commonActionTypes = {
  SHOW_SIDEBAR: 'SHOW_SIDEBAR',
  SHOW_LOADING: 'SHOW_LOADING',
  SET_LOADING_LIST: 'SET_LOADING_LIST',
  RESET_LOADING_LIST: 'RESET_LOADING_LIST',
  SHOW_EDIT_ACADEMIC_SESSION: 'SHOW_EDIT_ACADEMIC_SESSION',
  SHOW_ERROR_OCCURED: 'SHOW_ERROR_OCCURED',
  SHOW_LOGOUT_POPUP: 'SHOW_LOGOUT_POPUP',
  SHOW_FEATURE_LOCK_POPUP: 'SHOW_FEATURE_LOCK_POPUP',
  REDIRECT: 'REDIRECT',
  NOTIFICATION_COUNT: 'NOTIFICATION_COUNT',
  SHOW_PENDING_REQUEST_TEACHER_PAGE: 'SHOW_PENDING_REQUEST_TEACHER_PAGE',
  SHOW_EDIT_INSTITUTE_DETAILS_POPUP: 'SHOW_EDIT_INSTITUTE_DETAILS_POPUP',
  ERROR_MESSAGE: 'ERROR_MESSAGE',
  SHOW_FREE_TRIAL_CONGRATS_POPUP: 'SHOW_FREE_TRIAL_CONGRATS_POPUP',
  SHOW_PROFILE_DROPDOWN: 'SHOW_PROFILE_DROPDOWN',
  SHOW_NOTIFICATION_DROPDOWN: 'SHOW_NOTIFICATION_DROPDOWN',
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
  TOAST_DATA: 'TOAST_DATA',
  LOGOUT_USER: 'LOGOUT_USER',
  ADMIN_SWITCH_ACCOUNT: 'ADMIN_SWITCH_ACCOUNT',
  COUNTRY_LIST: 'COUNTRY_LIST',
  SET_IS_MOBILE: 'SET_IS_MOBILE',
}

const adminInfoActionTypes = {
  ADMIN_INFO: 'ADMIN_INFO',
  ROLES_LIST: 'ROLES_LIST',
  CURR_ADMIN_INFO: 'CURR_ADMIN_INFO',
  SIDEBAR: 'SIDEBAR',
}

const staffActionTypes = {
  GET_STAFF_LIST: 'GET_STAFF_LIST',
}

const instituteInfoActionTypes = {
  IS_FIRST_INSTITUTE_LOGIN: 'IS_FIRST_INSTITUTE_LOGIN',
  INSTITUTE_LIST_INFO: 'INSTITUTE_LIST_INFO',
  PENDING_INSTITUTE_LIST_INFO: 'PENDING_INSTITUTE_LIST_INFO',
  SHOW_INSTITUTE_LIST: 'SHOW_INSTITUTE_LIST',
  INSTITUTE_INFO: 'INSTITUTE_INFO',
  INSTITUTE_STATS: 'INSTITUTE_STATS',
  INSTITUTE_TEACHER_STATS: 'INSTITUTE_TEACHER_STATS',
  LINK_PENDING_REQUESTS: 'LINK_PENDING_REQUESTS',
  DELINK_PENDING_REQUESTS: 'DELINK_PENDING_REQUESTS',
  INSTITUTE_ALL_CLASSES: 'INSTITUTE_ALL_CLASSES',
  INSTITUTE_ATTENDANCE: 'INSTITUTE_ATTENDANCE',
  INSTITUTE_TEACHERS_LIST: 'INSTITUTE_TEACHERS_LIST',
  INSTITUTE_ACTIVE_TEACHERS_LIST: 'INSTITUTE_ACTIVE_TEACHERS_LIST',
  INSTITUTE_INACTIVE_TEACHERS_LIST: 'INSTITUTE_INACTIVE_TEACHERS_LIST',
  INSTITUTE_ADMINS_LIST: 'INSTITUTE_ADMINS_LIST',
  KAM_LIST: 'KAM_LIST',
  INSTITUTE_BOOKS_LIST: 'INSTITUTE_BOOKS_LIST',
  INSTITUTE_STUDENTS_LIST: 'INSTITUTE_STUDENTS_LIST',
  INSTIUTE_ACTIVE_STUDENTS_LIST: 'INSTITUTE_ACTIVE_STUDENT_LIST',
  INSTITUTE_INACTIVE_STUDENTS_LIST: 'INSTITUTE_INACTIVE_STUDENT_LIST',
  INSTITUTE_TODAYS_SCHEDULE: 'INSTITUTE_TODAYS_SCHEDULE',
  INSTITUTE_HIERARCHY: 'INSTITUTE_HIERARCHY',
  INSTITUTE_ACADEMIC_SESSION_INFO: 'INSTITUTE_ACADEMIC_SESSION_INFO',
  INSTITUTE_ACADEMIC_SESSION_LOADING: 'INSTITUTE_ACADEMIC_SESSION_LOADING',
  INSTITUTE_ACADEMIC_SESSION_ERROR: 'INSTITUTE_ACADEMIC_SESSION_ERROR',
  INSTITUTE_ACTIVE_ACADEMIC_SESSION_ID: 'INSTITUTE_ACTIVE_ACADEMIC_SESSION_ID',
  DUPLICATE_TEACHERS_LIST: 'DUPLICATE_TEACHERS_LIST',
  DUPLICATE_STUDENTS_LIST: 'DUPLICATE_STUDENTS_LIST',
  BULK_ASSIGN_CLASS_TEACHERS_TO_SECTION:
    'BULK_ASSIGN_CLASS_TEACHERS_TO_SECTION',
  UNASSIGNED_CLASS_TEACHERS_TO_SECTION: 'UNASSIGNED_CLASS_TEACHERS_TO_SECTION',
  GET_PENDING_STUDENT_LIST: 'GET_PENDING_STUDENT_LIST',
  GET_DASHBOARD_FEE_STATISTICS_REQUESTED:
    'GET_DASHBOARD_FEE_STATISTICS_REQUESTED',
  GET_DASHBOARD_FEE_STATISTICS_SUCCEEDED:
    'GET_DASHBOARD_FEE_STATISTICS_SUCCEEDED',
  GET_DASHBOARD_FEE_STATISTICS_FAILED: 'GET_DASHBOARD_FEE_STATISTICS_FAILED',
  INSTITUTE_STUDENTS_LIST_LOADING: 'INSTITUTE_STUDENTS_LIST_LOADING',
  TEACHERS_LIST_LOADING: 'TEACHERS_LIST_LOADING',
  INSTITUTE_BILLING_INFO: 'INSTITUTE_BILLING_INFO',
}

const hostelInfoActionTypes = {
  HOSTEL_LIST: 'HOSTEL_LIST',
  HOSTEL_ROOMS_LIST: 'HOSTEL_ROOMS_LIST',
  HOSTEL_INFO: 'HOSTEL_INFO',
}

const eventManagerActionTypes = {
  EVENT_MANAGER: 'EVENT_MANAGER',
  LAST_EVENT: 'LAST_EVENT',
}

const schoolSystemActionTypes = {
  SCHOOL_SYSTEM_SECTION_SELECTED: 'SCHOOL_SYSTEM_SECTION_SELECTED',
  SCHOOL_SYSTEM_SCREEN_SELECTED: 'SCHOOL_SYSTEM_SCREEN_SELECTED',
}

const reportLogActionTypes = {
  DOWNLOAD_REPORT_LOG_REQUEST: 'DOWNLOAD_REPORT_LOG_REQUEST',
  DOWNLOAD_REPORT_LOG_SUCCESS: 'DOWNLOAD_REPORT_LOG_SUCCESS',
  SAVE_REPORT_LOG: 'SAVE_REPORT_LOG',
  SET_DOWNLOAD_REPORT_LOADER: 'SET_DOWNLOAD_REPORT_LOADER',
  PERFORMANCE_REPORT_REQUEST: 'PERFORMANCE_REPORT_REQUEST',
  PERFORMANCE_REPORT_SUCCESS: 'PERFORMANCE_REPORT_SUCCESS',
  SET_PERFORMANCE_REPORT_STATES: 'SET_PERFORMANCE_REPORT_STATES',
}

const quickActionsActionTypes = {
  TODAY_COLLECTED_FEE_REQUEST: 'TODAY_COLLECTED_FEE_REQUEST',
  TODAY_COLLECTED_FEE_SUCCESS: 'TODAY_COLLECTED_FEE_SUCCESS',
}

const organisationInfoActionTypes = {
  ORGANISATION_INFO: 'ORGANISATION_INFO',
}

export {
  commonActionTypes,
  adminInfoActionTypes,
  instituteInfoActionTypes,
  eventManagerActionTypes,
  schoolSystemActionTypes,
  hostelInfoActionTypes,
  reportLogActionTypes,
  quickActionsActionTypes,
  staffActionTypes,
  organisationInfoActionTypes,
}
