export const PopupActions = {
  GET_POPUP_DATA: 'GET_POPUP_DATA',
  SHOW_POPUP_DATA: 'SHOW_POPUP_DATA',
  SET_POPUP_DATA: 'SET_POPUP_DATA',
  CLOSE_POPUP: 'CLOSE_POPUP',
  GET_POPUP_DATA_FAILURE: 'GET_POPUP_DATA_FAILURE',
  SET_POPUP_DATA_FAILURE: 'SET_POPUP_DATA_FAILURE',
  // SET_COMMUNICATION_DATA: 'SET_COMMUNICATION_DATA',
  SET_USER_LIST: 'SET_USER_LIST',
  SET_POPUP_TIME: 'SET_POPUP_TIME',
}
