export const feeReportActionTypes = {
  SET_LOADER: 'SET_LOADER',
  SET_FEE_REPORTS_LOADER: 'SET_FEE_REPORTS_LOADER',
  SET_PAID_AND_DUE_DATA: 'SET_PAID_AND_DUE_DATA',
  SET_PAYMENT_COLLECTION_DATA: 'SET_PAYMENT_COLLECTION_DATA',
  SET_FEE_REPORTS_STATES: 'SET_FEE_REPORTS_STATES',

  SET_FEE_REPORTS_STUDENT_CLASS_SECTIONS:
    'SET_FEE_REPORTS_STUDENT_CLASS_SECTIONS',
  SET_FEE_REPORTS_CLASSES: 'SET_FEE_REPORTS_CLASSES',
  SET_FEE_REPORTS_DEPARTMENTS: 'SET_FEE_REPORTS_DEPARTMENTS',
  SET_FEE_REPORTS_MONTHS: 'SET_FEE_REPORTS_MONTHS',
  SET_FEE_REPORTS_FEE_TYPES: 'SET_FEE_REPORTS_FEE_TYPES',
  SET_FEE_REPORTS_DATE_RANGE: 'SET_FEE_REPORTS_DATE_RANGE',
  RESET_FEE_REPORTS_STATES: 'RESET_FEE_REPORTS_STATES',
  SET_IS_PENDING_CHEQUE_DATA_INCLUDED: 'SET_IS_PENDING_CHEQUE_DATA_INCLUDED',
  SET_FEE_TYPE: 'SET_FEE_TYPE',
  SET_PAYMENT_MODES: 'SET_PAYMENT_MODES',
  SET_DATE_RANGE: 'SET_DATE_RANGE',

  FETCH_SAVED_REPORTS: 'FETCH_SAVED_REPORTS',
  SET_SAVED_REPORTS_LIST: 'SET_SAVED_REPORTS_LIST',
  SET_REPORT_TEMPLATE_ID: 'SET_REPORT_TEMPLATE_ID',

  DOWNLOAD_REPORT: 'DOWNLOAD_REPORT',
  SET_HIERARCHY_IDS: 'SET_HIERARCHY_IDS',
  SET_MASTER_CATEGORY_IDS: 'SET_MASTER_CATEGORY_IDS',

  FETCH_INSTITUTE_FEE_TYPES: 'FETCH_INSTITUTE_FEE_TYPES',
  SET_INSTITUTE_FEE_TYPES: 'SET_INSTITUTE_FEE_TYPES',

  FETCH_INSTALMENT_TIMESTAMP: 'FETCH_INSTALMENT_TIMESTAMP',
  SET_INSTALMENT_TIMESTAMP_LIST: 'SET_INSTALMENT_TIMESTAMP_LIST',
  SET_INSTALMENT_TIMESTAMP: 'SET_INSTALMENT_TIMESTAMP',

  SET_IS_REPORT_DOWNLOAD_MODAL_OPEN: 'SET_IS_REPORT_DOWNLOAD_MODAL_OPEN',
  SET_CHEQUE_STATUS: 'SET_CHEQUE_STATUS',

  SET_DOWNLOAD_REPORT_DATA: 'SET_DOWNLOAD_REPORT_DATA',
  FETCH_FEE_DATA: 'FETCH_FEE_DATA',
  FETCH_FEE_DATA_START: 'FETCH_FEE_DATA_START',
  FETCH_CHEQUE_COUNT: 'FETCH_CHEQUE_COUNT',
  SET_CHEQUE_COUNT: 'SET_CHEQUE_COUNT',
  SET_FEE_DATA_START: 'SET_FEE_DATA_START',
  FETCH_FEE_DATA_DEFAULTERS: 'FETCH_FEE_DATA_DEFAULTERS',
  SET_FEE_DATA_DEFAULTERS: 'SET_FEE_DATA_DEFAULTERS',
  SET_FEE_DATA: 'SET_FEE_DATA',
  FETCH_TIMESTAMP_DATA: 'FETCH_TIMESTAMP_DATA',
  FETCH_REPORT_DATA: 'FETCH_REPORT_DATA',
}
