export const FEE_WIDGET_EVENTS = {
  DASHBOARD_FEES_REPORTS_VIEW_CLICKED_TFI:
    'DASHBOARD_FEES_REPORTS_VIEW_CLICKED_TFI',
  DASHBOARD_FEES_REPORTS_TRANSACTIONS_CLICKED_TFI:
    'DASHBOARD_FEES_REPORTS_TRANSACTIONS_CLICKED_TFI',
  DASHBOARD_REPORTS_NOTIFY_STUDENT_CLICKED_TFI:
    'DASHBOARD_REPORTS_NOTIFY_STUDENT_CLICKED_TFI',
  DASHBOARD_FEES_REPORTS_NOTIFY_CLICKED_TFI:
    'DASHBOARD_FEES_REPORTS_NOTIFY_CLICKED_TFI',
  DASHBOARD_FEES_REPORTS_CREATE_FEE_TFI:
    'DASHBOARD_FEES_REPORTS_CREATE_FEE_TFI',
}
