export const events = {
  GET_OTP_CLICKED_TFI: 'GET_OTP_CLICKED_TFI',
  SENDING_OTP_FAILED_TFI: 'SENDING_OTP_FAILED_TFI',
  VERIFY_OTP_CLICKED_TFI: 'VERIFY_OTP_CLICKED_TFI',
  PROFILE_CREATION_INITIALIZED_TFI: 'PROFILE_CREATION_INITIALIZED_TFI',
  ENTER_ADMIN_NAME_FILLED_TFI: 'ENTER_ADMIN_NAME_FILLED_TFI',
  ENTER_INSTITUTE_NAME_FILLED_TFI: 'ENTER_INSTITUTE_NAME_FILLED_TFI',
  ADD_LOGO_CLICKED_TFI: 'ADD_LOGO_CLICKED_TFI',
  SIGNUP_SUCCESSFUL: 'SIGNUP_SUCCESSFUL',
  ADMIN_PROFILE_CREATION_COMPLETED_TFI: 'ADMIN_PROFILE_CREATION_COMPLETED_TFI',
  VIEW_YOUR_PLANS_CLICKED_TFI: 'VIEW_YOUR_PLANS_CLICKED_TFI',
  DOWNLOAD_APP_CLICKED_TFI: 'DOWNLOAD_APP_CLICKED_TFI',
  GET_STARTED_CLICKED_TFI: 'GET_STARTED_CLICKED_TFI',
  ENQUIRY_CONTACT_US_CLICKED_TFI: 'ENQUIRY_CONTACT_US_CLICKED_TFI',
  DASHBOARD_CLICKED_TFI: 'DASHBOARD_CLICKED_TFI',
  PENDING_REQUESTS_CLICKED_TFI: 'PENDING_REQUESTS_CLICKED_TFI',
  TODAYS_SCHEDULE_CLICKED_TFI: 'TODAYS_SCHEDULE_CLICKED_TFI',
  TEACHERS_CLICKED_TFI: 'TEACHERS_CLICKED_TFI',
  CLASSROOMS_CLICKED_TFI: 'CLASSROOMS_CLICKED_TFI',
  STUDENTS_CLICKED_TFI: 'STUDENTS_CLICKED_TFI',
  TEACHERS_ATTENDANCE_CLICKED_TFI: 'TEACHERS_ATTENDANCE_CLICKED_TFI',
  CLASSROOM_ATTENDANCE_CLICKED_TFI: 'CLASSROOM_ATTENDANCE_CLICKED_TFI',
  HELP_CLICKED_TFI: 'HELP_CLICKED_TFI',
  SEND_FEEDBACK_CLICKED_TFI: 'SEND_FEEDBACK_CLICKED_TFI',
  FEEDBACK_SUBMITTED_TFI: 'FEEDBACK_SUBMITTED_TFI',
  CONTACT_US_CLICKED_TFI: 'CONTACT_US_CLICKED_TFI',
  CALL_US_CLICKED_TFI: 'CALL_US_CLICKED_TFI',
  SEND_EMAIL_CLICKED_TFI: 'SEND_EMAIL_CLICKED_TFI',
  CHAT_WITH_US_CLICKED_TFI: 'CHAT_WITH_US_CLICKED_TFI',
  LOGOUT_CLICKED_TFI: 'LOGOUT_CLICKED_TFI',
  LOGOUT_SUCCESSFUL_TFI: 'LOGOUT_SUCCESSFUL_TFI',
  APPROVE_PENDING_REQUEST_CLICKED_TFI: 'APPROVE_PENDING_REQUEST_CLICKED_TFI',
  REJECT_PENDING_REQUEST_CLICKED_TFI: 'REJECT_PENDING_REQUEST_CLICKED_TFI : ',
  ADD_PENDING_REQUEST_MERGE_TFI: 'ADD_PENDING_REQUEST_MERGE_TFI',
  ADD_PENDING_REQUEST_NEW_STUDENT_TFI: 'ADD_PENDING_REQUEST_NEW_STUDENT_TFI',
  VIEW_STATISTICS_CLICKED_TFI: 'VIEW_STATISTICS_CLICKED_TFI',
  VIEW_FEES_STATISTICS_CLICKED_TFI: 'VIEW_FEES_STATISTICS_CLICKED_TFI',
  VIEW_ATTENDANCE_STATISTICS_CLICKED_TFI:
    'VIEW_ATTENDANCE_STATISTICS_CLICKED_TFI',
  ONLINE_LIVE_CLASSES_CLICKED_TFI: 'ONLINE_LIVE_CLASSES_CLICKED_TFI',
  JOIN_LIVE_CLASS_CLICKED_TFI: 'JOIN_LIVE_CLASS_CLICKED_TFI',
  ADD_TEACHER_CLICKED: 'ADD_TEACHER_CLICKED_TFI',
  TEACHER_ADDED_TFI: 'TEACHER_ADDED_TFI',
  UPLOAD_CSV_CLICKED: 'UPLOAD_CSV_CLICKED_TFI',
  STUDENT_CSV_UPLOADED: 'STUDENT_CSV_UPLOADED_TFI',
  TEACHER_CSV_UPLOADED: 'TEACHER_CSV_UPLOADED_TFI',
  DOWNLOAD_TEACHER_SAMPLE_FORMAT_CLICKED:
    'DOWNLOAD_TEACHER_SAMPLE_FORMAT_CLICKED_TFI',
  DOWNLOAD_STUDENT_SAMPLE_FORMAT_CLICKED:
    'DOWNLOAD_STUDENT_SAMPLE_FORMAT_CLICKED_TFI',
  ADD_CLASSROOM_CLICKED: 'ADD_CLASSROOM_CLICKED_TFI',
  CLASSROOM_ADDED: 'CLASSROOM_ADDED_TFI',
  VIEW_CLASSROOM_CLICKED: 'VIEW_CLASSROOM_CLICKED_TFI',
  COPY_INSTITUTE_ID_CLICKED_TFI: 'COPY_INSTITUTE_ID_CLICKED_TFI',
  INSTITUTE_DROP_DOWN_CLICKED_TFI: 'INSTITUTE_DROP_DOWN_CLICKED_TFI',
  INSTITUTE_DROP_DOWN_INSTI_SELECTED_TFI:
    'INSTITUTE_DROP_DOWN_INSTI_SELECTED_TFI',
  INVITE_TEACHER_CLICKED_TFI: 'INVITE_TEACHER_CLICKED_TFI',
  INSTITUTE_LINK_COPIED: 'INSTITUTE_LINK_COPIED_TFI',
  EDIT_DETAILS: 'EDIT_DETAILS_TFI',
  TODAYS_SCHEDULE_TABS_CLICKED: 'TODAYS_SCHEDULE_TABS_CLICKED_TFI',
  VIEW_DETAILS_TFI: 'VIEW_DETAILS_TFI',
  VIEW_FEES_DETAILS_TFI: 'VIEW_FEES_DETAILS_TFI',
  VIEW_ATTENDANCE_DETAILS_TFI: 'VIEW_ATTENDANCE_DETAILS_TFI',
  DASHBOARD_TODAYS_SCHEDULE_CARDS: 'DASHBOARD_TODAYS_SCHEDULE_CARDS_TFI',
  VIEW_ALL_REQUESTS: 'VIEW_ALL_REQUESTS_TFI',
  USER_TYPE_SELECTED_TFI: 'USER_TYPE_SELECTED_TFI',
  RESEND_OTP_CLICKED_TFI: 'RESEND_OTP_CLICKED_TFI',
  INSTITUTE_TYPE_SELECTED_TFI: 'INSTITUTE_TYPE_SELECTED_TFI',
  ADD_TEACHER_SKIP_CLICKED_TFI: 'ADD_TEACHER_SKIP_CLICKED_TFI',
  START_FREE_TRIAL_CLICKED_TFI: 'START_FREE_TRIAL_CLICKED_TFI',
  ADMIN_CLICKED_TFI: 'ADMIN_CLICKED_TFI',
  ANNOUNCEMENTS_CLICKED_TFI: 'ANNOUNCEMENTS_CLICKED_TFI',
  FEES_CLICKED_TFI: 'FEES_CLICKED_TFI',
  USER_TYPE_CARD_CLICKED: 'USER_TYPE_CARD_CLICKED_TFI',
  DASHBOARD_LOADED: 'DASHBOARD_LOADED_TFI',
  MOBILE_NUMBER_FILLED_TFI: 'MOBILE_NUMBER_FILLED_TFI',
  OTP_FILLED_TFI: 'OTP_FILLED_TFI',
  INSTITUTE_TYPE_CARD_CLICKED_TFI: 'INSTITUTE_TYPE_CARD_CLICKED_TFI',
  ADMIN_INSTITUTE_NAME_FILLED_TFI: 'ADMIN_INSTITUTE_NAME_FILLED_TFI',
  ADMIN_DEPARTMENT_SELECTED_TFI: 'ADMIN_DEPARTMENT_SELECTED_TFI',
  BACK_BUTTON_CLICKED: 'BACK_BUTTON_CLICKED_ONBOARDING_TFI',
  ADMIN_NAME_FILLED_TFI: 'ADMIN_NAME_FILLED_TFI',
  ADMIN_CITY_PINCODE_FILLED_TFI: 'ADMIN_CITY_PINCODE_FILLED_TFI',
  SHARE_LINK_CLICKED_TFI: 'SHARE_LINK_CLICKED_TFI',
  LOGIN_SUCCESSFUL_TFI: 'LOGIN_SUCCESSFUL_TFI',
  TEACHER_NAME_FILLED_TFI: 'TEACHER_NAME_FILLED_TFI',
  REMIND_TEACHER_TFI: 'REMIND_TEACHER_TFI',
  TRY_YOURSELF_AS_TEACHER: 'TRY_YOURSELF_AS_TEACHER_TFI',
  BUY_NOW_CLICKED: 'BUY_NOW_CLICKED_TFI',
  CROSS_BUTTON_CLICKED_TFI: 'CROSS_BUTTON_CLICKED_TFI',
  EDIT_MOBILE_NUMBER_CLICKED_TFI: 'EDIT_MOBILE_NUMBER_CLICKED_TFI',
  ADMIN_BOARD_NAME_OPENED_TFI: 'ADMIN_BOARD_NAME_OPENED_TFI',
  ADMIN_BOARD_NAME_SELECTED_TFI: 'ADMIN_BOARD_NAME_SELECTED_TFI',
  WEBSITE_BUILDER_SIDEBAR_CLICKED_TFI: 'WEBSITE_BUILDER_SIDEBAR_CLICKED_TFI',
  COMMUNICATION_CLICKED_TFI: 'COMMUNICATION_CLICKED_TFI',
  HOSTEL_MANAGEMENT_CLICKED_TFI: 'HOSTEL_MANAGEMENT_CLICKED_TFI',
  ADMISSION_MANAGEMENT_SIDEBAR_CLICKED_TFI:
    'ADMISSION_MANAGEMENT_SIDEBAR_CLICKED_TFI',
  TEACHER_ADDED_IN_SCHOOL_TFI: 'TEACHER_ADDED_IN_SCHOOL_TFI',
  TEACHER_ADDED_IN_COACHING_TFI: 'TEACHER_ADDED_IN_COACHING_TFI',
  TEACHER_ADDED_IN_COLLEGE_TFI: 'TEACHER_ADDED_IN_COLLEGE_TFI',
  ADD_AS_NEW_TEACHER_CLICKED_TFI: 'ADD_AS_NEW_TEACHER_CLICKED_TFI',
  ADD_AS_NEW_TEACHERS_CLICKED_TFI: 'ADD_AS_NEW_TEACHERS_CLICKED_TFI',
  IGNORE_TEACHER_CLICKED_TFI: 'IGNORE_TEACHER_CLICKED_TFI',
  LIBRARY_MANAGEMENT_CLICKED_TFI: 'LIBRARY_MANAGEMENT_CLICKED_TFI',
  DOWNLOAD_BULK_ADD_BOOKS_SAMPLE_FORMAT_CLICKED:
    'DOWNLOAD_BULK_ADD_BOOKS_SAMPLE_FORMAT_CLICKED',
  UPLOAD_BULK_BOOKS_CLICKED_TFI: 'UPLOAD_BULK_BOOKS_CLICKED_TFI',
  // onboarding events
  PEOPLE_CLICKED_TFI: 'PEOPLE_CLICKED_TFI',
  MANAGE_INSTITUTE_CLICKED_TFI: 'MANAGE_INSTITUTE_CLICKED_TFI',
  ACADEMICS_CLICKED_TFI: 'ACADEMICS_CLICKED_TFI',
  FINANCE_CLICKED_TFI: 'FINANCE_CLICKED_TFI',
  REPORTS_CLICKED_TFI: 'REPORTS_CLICKED_TFI',
  MANAGE_SCHOOL_CLICKED_TFI: 'MANAGE_SCHOOL_CLICKED_TFI',
  ADMINISTRATION_CLICKED_TFI: 'ADMINISTRATION_CLICKED_TFI',
  HRMS_CLICKED_TFI: 'HRMS_CLICKED_TFI',
  FACILITIES_CLICKED_TFI: 'FACILITIES_CLICKED_TFI',
  INSTITUTE_CURRENCY_SELECTED_TFI: 'INSTITUTE_CURRENCY_SELECTED_TFI',
  INSTITUTE_COUNTRY_SELECTED_TFI: 'INSTITUTE_COUNTRY_SELECTED_TFI',
  INSTITUTE_SETUP_CLICKED_TFI: 'INSTITUTE_SETUP_CLICKED_TFI',
  USER_SETUP_CLICKED_TFI: 'USER_SETUP_CLICKED_TFI',
  SCHOOL_OVERVIEW_CLICKED_TFI: 'SCHOOL_OVERVIEW_CLICKED_TFI',
  SCHOOL_SETUP_CLICKED_TFI: 'SCHOOL_SETUP_CLICKED_TFI',
  TEACHERS_DIRECTORY_CLICKED_TFI: 'TEACHERS_DIRECTORY_CLICKED_TFI',
  STUDENT_DIRECTORY_CLICKED_TFI: 'STUDENT_DIRECTORY_CLICKED_TFI',
  UNASSIGNED_CLASSES_CLICKED_TFI: 'UNASSIGNED_CLASSES_CLICKED_TFI',
  ADD_NEW_SECTION_CLICKED_TFI: 'ADD_NEW_SECTION_CLICKED_TFI',
  NEW_SECTION_ADDED_TFI: 'NEW_SECTION_ADDED_TFI',
  CLASS_SECTION_CLICKED_TFI: 'CLASS_SECTION_CLICKED_TFI',
  CLASS_NAME_CLICKED_TFI: 'CLASS_NAME_CLICKED_TFI',
  EDIT_CLASS_SECTION_CLICKED_TFI: 'EDIT_CLASS_SECTION_CLICKED_TFI',
  CLASS_SECTION_EDITED_TFI: 'CLASS_SECTION_EDITED_TFI',
  NEXT_RECOMMENDATION_ACTION_CLICKED_TFI:
    'NEXT_RECOMMENDATION_ACTION_CLICKED_TFI',
  DELETE_CLASS_SECTION_CLICKED_TFI: 'DELETE_CLASS_SECTION_CLICKED_TFI',
  CLASS_SECTION_DELETED_TFI: 'CLASS_SECTION_DELETED_TFI',
  ADD_MORE_SUBJECTS_CLICKED_TFI: 'ADD_MORE_SUBJECTS_CLICKED_TFI',
  SUBJECT_ADDED_TFI: 'SUBJECT_ADDED_TFI',
  MOVE_STUDENT_INITIALIZED_TFI: 'MOVE_STUDENT_INITIALIZED_TFI',
  MOVE_STUDENT_CLICKED_TFI: 'MOVE_STUDENT_CLICKED_TFI',
  STUDENT_MOVED_TFI: 'STUDENT_MOVED_TFI',
  REPLACE_SUBJECT_TEACHER_CLICKED_TFI: 'REPLACE_SUBJECT_TEACHER_CLICKED_TFI',
  SUBJECT_TEACHER_REMOVED_TFI: 'SUBJECT_TEACHER_REMOVED_TFI',
  REMOVE_SUBJECT_TEACHER_CLICKED_TFI: 'REMOVE_SUBJECT_TEACHER_CLICKED_TFI',
  STUDENT_OPTIONAL_DETAILS_CLICKED_TFI: 'STUDENT_OPTIONAL_DETAILS_CLICKED_TFI',
  TEACHER_OPTIONAL_DETAILS_CLICKED_TFI: 'TEACHER_OPTIONAL_DETAILS_CLICKED_TFI',
  STUDENT_BASIC_INFORMATION_CLICKED_TFI:
    'STUDENT_BASIC_INFORMATION_CLICKED_TFI',
  TEACHER_BASIC_INFORMATION_CLICKED_TFI:
    'TEACHER_BASIC_INFORMATION_CLICKED_TFI',
  SUBJECT_TYPE_CHANGED: 'SUBJECT_TYPE_CHANGED_TFI',
  SUBJECT_DELETED_TFI: 'SUBJECT_DELETED_TFI',
  DELETE_SUBJECT_CLICKED_TFI: 'DELETE_SUBJECT_CLICKED_TFI',
  DELETE_SUBJECT_INITIALIZED_TFI: 'DELETE_SUBJECT_INITIALIZED_TFI',
  EDIT_SUBJECT_NAME_CLICKED_TFI: 'EDIT_SUBJECT_NAME_CLICKED_TFI',
  K_MENU_SUBJECT_CLICKED: 'K_MENU_SUBJECT_CLICKED_TFI',
  OTP_VERIFIED_TFI: 'OTP_VERIFIED_TFI',
  OTP_VERIFICATION_FAILED: 'OTP_VERIFICATION_FAILED_TFI',
  ADD_TEACHER_PROFILE_CREATE_CLICKED: 'ADD_TEACHER_PROFILE_CREATE_CLICKED_TFI',
  ADMIN_BOARD_NAMES_LIST_OPEN_TFI: 'ADMIN_BOARD_NAMES_LIST_OPEN_TFI',
  NODE_CLICKED_TFI: 'NODE_CLICKED_TFI',
  NOTIFICATION_ACCESS_REQUESTED_TFI: 'NOTIFICATION_ACCESS_REQUESTED_TFI',

  ADD_STUDENT_INITIALIZED_TFI: 'ADD_STUDENT_INITIALIZED_TFI',
  ADD_STUDENT_CLICKED_TFI: 'ADD_STUDENT_CLICKED_TFI',
  UPDATE_STUDENT_CLICKED_TFI: 'UPDATE_STUDENT_CLICKED_TFI',
  MANAGE_STUDENT_CLICKED_TFI: 'MANAGE_STUDENT_CLICKED_TFI',
  UPDATE_EXISTING_STUDENT_CLICKED_TFI: 'UPDATE_EXISTING_STUDENT_CLICKED_TFI',
  DOWNLOAD_STUDENT_LIST_CLICKED_TFI: 'DOWNLOAD_STUDENT_LIST_CLICKED_TFI',
  UPLOAD_STUDENT_CSV_CLICKED_TFI: 'UPLOAD_STUDENT_CSV_CLICKED_TFI',
  STUDENT_CSV_UPLOADED_CLICKED_TFI: 'STUDENT_CSV_UPLOADED_CLICKED_TFI',
  CONFIRM_CLICKED_TFI: 'CONFIRM_CLICKED_TFI',
  STUDENT_ADDED_TFI: 'STUDENT_ADDED_TFI',
  STUDENT_SELECTED_TFI: 'STUDENT_SELECTED_TFI',

  UPDATE_STUDENT_INITIALIZED_TFI: 'UPDATE_STUDENT_INITIALIZED_TFI',
  STUDENT_UPDATED_TFI: 'STUDENT_UPDATED_TFI',
  ADD_AS_NEW_STUDENT_CLICKED_TFI: 'ADD_AS_NEW_STUDENT_CLICKED_TFI',
  ADD_AS_NEW_STUDENTS_CLICKED_TFI: 'ADD_AS_NEW_STUDENTS_CLICKED_TFI',
  IGNORE_STUDENT_CLICKED_TFI: 'IGNORE_STUDENT_CLICKED_TFI',
  DELETE_STUDENT_PROFILE_CLICKED_TFI: 'DELETE_STUDENT_PROFILE_CLICKED_TFI',
  DELETE_STUDENT_PROFILE_POPUP_CLICKED_TFI:
    'DELETE_STUDENT_PROFILE_POPUP_CLICKED_TFI',
  STUDENT_PROFILE_DELETED_TFI: 'STUDENT_PROFILE_DELETED_TFI',

  REMOVE_OR_REPLACE_USER_PHOTO_CLICKED_TFI:
    'REMOVE_OR_REPLACE_USER_PHOTO_CLICKED_TFI',
  UPLOAD_USER_PHOTO_CLICKED_TFI: 'UPLOAD_USER_PHOTO_CLICKED_TFI',
  USER_PHOTO_UPLOADED_TFI: 'USER_PHOTO_UPLOADED_TFI',
  USER_PHOTO_UPLOAD_ERROR_TFI: 'USER_PHOTO_UPLOAD_ERROR_TFI',
  USER_PHOTO_REMOVED_TFI: 'USER_PHOTO_REMOVED_TFI',

  UPLOAD_INSTITUTE_LOGO_CLICKED_TFI: 'UPLOAD_INSTITUTE_LOGO_CLICKED_TFI',
  INSTITUTE_LOGO_UPLOADED_TFI: 'INSTITUTE_LOGO_UPLOADED_TFI',
  INSTITUTE_LOGO_UPLOAD_ERROR_TFI: 'INSTITUTE_LOGO_UPLOAD_ERROR_TFI',
  REMOVE_OR_REPLACE_INSTITUTE_LOGO_CLICKED_TFI:
    'REMOVE_OR_REPLACE_INSTITUTE_LOGO_CLICKED_TFI',
  INSTITUTE_LOGO_REMOVED_TFI: 'INSTITUTE_LOGO_REMOVED_TFI',

  ASSIGN_SUBJECT_TEACHER_INITIALIZED_TFI:
    'ASSIGN_SUBJECT_TEACHER_INITIALIZED_TFI',
  ASSIGN_SUBJECT_TEACHER_CLICKED_TFI: 'ASSIGN_SUBJECT_TEACHER_CLICKED_TFI',
  SUBJECT_TEACHER_ASSIGNED_TFI: 'SUBJECT_TEACHER_ASSIGNED_TFI',

  ASSIGN_CLASS_TEACHER_INITIALIZED_TFI: 'ASSIGN_CLASS_TEACHER_INITIALIZED_TFI',
  ASSIGN_CLASS_TEACHER_CLICKED_TFI: 'ASSIGN_CLASS_TEACHER_CLICKED_TFI',
  CLASS_TEACHER_ASSIGNED_TFI: 'CLASS_TEACHER_ASSIGNED_TFI',
  DELETE_TEACHER_PROFILE_CLICKED_TFI: 'DELETE_TEACHER_PROFILE_CLICKED_TFI',
  DELETE_TEACHER_PROFILE_POPUP_CLICKED_TFI:
    'DELETE_TEACHER_PROFILE_POPUP_CLICKED_TFI',
  TEACHER_PROFILE_DELETED_TFI: 'TEACHER_PROFILE_DELETED_TFI',

  DELETE_USER_PROFILE_CLICKED_TFI: 'DELETE_USER_PROFILE_CLICKED_TFI',
  DELETE_USER_PROFILE_POPUP_CLICKED_TFI:
    'DELETE_USER_PROFILE_POPUP_CLICKED_TFI',
  USER_PROFILE_DELETED_TFI: 'USER_PROFILE_DELETED_TFI',

  REMOVE_CLASS_TEACHER_INITIALIZED_TFI: 'REMOVE_CLASS_TEACHER_INITIALIZED_TFI',
  REMOVE_CLASS_TEACHER_CLICKED_TFI: 'REMOVE_CLASS_TEACHER_CLICKED_TFI',
  CLASS_TEACHER_REMOVED_TFI: 'CLASS_TEACHER_REMOVED_TFI',

  ASSIGN_STUDENT_INITIALIZED_TFI: 'ASSIGN_STUDENT_INITIALIZED_TFI',
  ASSIGN_STUDENT_CLICKED_TFI: 'ASSIGN_STUDENT_CLICKED_TFI',
  STUDENT_ASSIGNED_TFI: 'STUDENT_ASSIGNED_TFI',

  ADD_TEACHER_PROFILE_CREATE_CLICKED_TFI:
    'ADD_TEACHER_PROFILE_CREATE_CLICKED_TFI',
  UPDATE_TEACHER_CLICKED_TFI: 'UPDATE_TEACHER_CLICKED_TFI',
  TEACHER_UPDATED_TFI: 'TEACHER_UPDATED_TFI',
  TEACHER_SELECTED_TFI: 'TEACHER_SELECTED_TFI',
  ASSIGN_CO_TEACHER_CLICKED_TFI: 'ASSIGN_CO_TEACHER_CLICKED_TFI',
  CO_TEACHER_ASSIGNED_TFI: 'CO_TEACHER_ASSIGNED_TFI',
  REMOVE_CO_TEACHER_CLICKED_TFI: 'REMOVE_CO_TEACHER_CLICKED_TFI',
  CO_TEACHER_REMOVED_TFI: 'CO_TEACHER_REMOVED_TFI',
  EDIT_SCHOOL_STRUCTURE_CLICKED_TFI: 'EDIT_SCHOOL_STRUCTURE_CLICKED_TFI',
  ADD_CLASSROOM_TO_INSTITUTE_CLICKED_TFI:
    'ADD_CLASSROOM_TO_INSTITUTE_CLICKED_TFI',
  UPDATE_SCHOOL_STRUCTURE_CLICKED_TFI: 'UPDATE_SCHOOL_STRUCTURE_CLICKED_TFI',
  UPDATE_SCHOOL_STRUCTURE_POPUP_CLICKED_TFI:
    'UPDATE_SCHOOL_STRUCTURE_POPUP_CLICKED_TFI',
  SCHOOL_STRUCTURE_UPDATED_TFI: 'SCHOOL_STRUCTURE_UPDATED_TFI',
  CLASSROOM_FROM_INSTITUTE_ACTIVE_CLICKED_TFI:
    'CLASSROOM_FROM_INSTITUTE_ACTIVE_CLICKED_TFI',
  CLASSROOM_FROM_INSTITUTE_INACTIVE_CLICKED_TFI:
    'CLASSROOM_FROM_INSTITUTE_INACTIVE_CLICKED_TFI',
  EDIT_CLASSROOM_NAME_CLICKED_TFI: 'EDIT_CLASSROOM_NAME_CLICKED_TFI',
  CLASSROOM_NAME_EDITED_TFI: 'CLASSROOM_NAME_EDITED_TFI',
  TEACHER_ONBOARDING_CLICKED_TFI: 'TEACHER_ONBOARDING_CLICKED_TFI',
  CLASS_TEACHER_ONBOARDING_CLICKED_TFI: 'CLASS_TEACHER_ONBOARDING_CLICKED_TFI',
  STUDENTS_ONBOARDING_CLICKED_TFI: 'STUDENTS_ONBOARDING_CLICKED_TFI',
  ADMINS_ONBOARDING_CLICKED_TFI: 'ADMINS_ONBOARDING_CLICKED_TFI',
  ANNOUNCEMENT_TEACHER_ONBOARDING_NEXT_CLICKED_TFI:
    'ANNOUNCEMENT_TEACHER_ONBOARDING_NEXT_CLICKED_TFI',
  ADMIN_ONBOARDING_ANNOUNCEMENT_POSTED_TFI:
    'ADMIN_ONBOARDING_ANNOUNCEMENT_POSTED_TFI',
  ANNOUNCEMENT_ADMIN_ONBOARDING_NEXT_CLICKED_TFI:
    'ANNOUNCEMENT_ADMIN_ONBOARDING_NEXT_CLICKED_TFI',
  ADMINS_ONBOARDING_ANNOUNCEMENT_POST_CLICKED_TFI:
    'ADMINS_ONBOARDING_ANNOUNCEMENT_POST_CLICKED_TFI',
  TEACHER_ONBOARDING_ANNOUNCEMENT_POST_CLICKED_TFI:
    'TEACHER_ONBOARDING_ANNOUNCEMENT_POST_CLICKED_TFI',
  TEACHER_ONBOARDING_ANNOUNCEMENT_POSTED_TFI:
    'TEACHER_ONBOARDING_ANNOUNCEMENT_POSTED_TFI',
  STUDENT_ONBOARDING_ANNOUNCEMENT_NEXT_CLICKED_TFI:
    'STUDENT_ONBOARDING_ANNOUNCEMENT_NEXT_CLICKED_TFI',
  STUDENT_ONBOARDING_ANNOUNCEMENT_POST_CLICKED_TFI:
    'STUDENT_ONBOARDING_ANNOUNCEMENT_POST_CLICKED_TFI',
  ANNOUNCEMENT_STUDENT_ONBOARDING_POSTED_TFI:
    'ANNOUNCEMENT_STUDENT_ONBOARDING_POSTED_TFI',
  ASSIGN_CLASS_TEACHER_ONBAORDING_CLICKED_TFI:
    'ASSIGN_CLASS_TEACHER_ONBAORDING_CLICKED_TFI',
  CLASS_TEACHER_ONBOARDING_POSTED_TFI: 'CLASS_TEACHER_ONBOARDING_POSTED_TFI',
  USERID_ADDED_MOENGAGE: 'USERID_ADDED_MOENGAGE',
  USERID_DESTROYED_MOENGAGE: 'USERID_DESTROYED_MOENGAGE',
  //User Permission Events
  USER_MOBILE_NUMBER_FILLED_TFI: 'USER_MOBILE_NUMBER_FILLED_TFI',
  CREATE_USER_CLICKED_TFI: 'CREATE_USER_CLICKED_TFI',
  ADD_USER_POPUP_SHOWN_TFI: 'ADD_USER_POPUP_SHOWN_TFI',
  USER_NAME_FILLED_TFI: 'USER_NAME_FILLED_TFI',
  ADD_USER_CLICKED_TFI: 'ADD_USER_CLICKED_TFI',
  USER_ADDED_TFI: 'USER_ADDED_TFI',
  USER_ROLE_LIST_OPENED_TFI: 'USER_ROLE_LIST_OPENED_TFI',
  USER_ROLE_SELECTED_TFI: 'USER_ROLE_SELECTED_TFI',
  USER_EDIT_CLICKED_TFI: 'USER_EDIT_CLICKED_TFI',
  USER_REMOVE_CLICKED_TFI: 'USER_REMOVE_CLICKED_TFI',
  USER_EDITED_TFI: 'USER_EDITED_TFI',
  USER_REMOVED_TFI: 'USER_REMOVED_TFI',
  USER_REMOVE_POPUP_SHOWN_TFI: 'USER_REMOVE_POPUP_SHOWN_TFI',
  K_MENU_USER_CLICKED_TFI: 'K_MENU_USER_CLICKED_TFI',
  VISIT_ADMISSION_PORTAL_CLICKED_TFI: 'VISIT_ADMISSION_PORTAL_CLICKED_TFI',
  MANAGE_USERS_CLICKED_TFI: 'MANAGE_USERS_CLICKED_TFI',
  //Academic Session events
  ACADEMIC_SESSION_LIST_OPENED_TFI: 'ACADEMIC_SESSION_LIST_OPENED_TFI',
  ACADEMIC_SESSION_SELECTED_TFI: 'ACADEMIC_SESSION_SELECTED_TFI',
  CREATE_NEW_ACADEMIC_SESSION_CLICKED_TFI:
    'CREATE_NEW_ACADEMIC_SESSION_CLICKED_TFI',
  CREATE_NEW_ACADEMIC_SESSION_POPUP_SHOWN_TFI:
    'CREATE_NEW_ACADEMIC_SESSION_POPUP_SHOWN_TFI',
  SESSION_NAME_FILLED_TFI: 'SESSION_NAME_FILLED_TFI',
  SESSION_PERIOD_FILLED_TFI: 'SESSION_PERIOD_FILLED_TFI',
  ADD_NEW_ACADEMIC_SESSION_CLICKED_TFI: 'ADD_NEW_ACADEMIC_SESSION_CLICKED_TFI',
  CREATE_NEW_SESSION_CONFIRMATION_POPUP_SHOWN_TFI:
    'CREATE_NEW_SESSION_CONFIRMATION_POPUP_SHOWN_TFI',
  CREATE_NEW_SESSION_CONFIRMATION_POPUP_CLICKED_TFI:
    'CREATE_NEW_SESSION_CONFIRMATION_POPUP_CLICKED_TFI',
  NEW_ACADEMIC_SESSION_ADDED_TFI: 'NEW_ACADEMIC_SESSION_ADDED_TFI',
  EDIT_ACADEMIC_SESSION_CLICKED_TFI: 'EDIT_ACADEMIC_SESSION_CLICKED_TFI',
  ACADEMIC_SESSION_EDITED_TFI: 'ACADEMIC_SESSION_EDITED_TFI',
  SETTINGS_CLICKED_TFI: 'SETTINGS_CLICKED_TFI',
  EVENT_SEND_GREETINGS_CLICKED_TFI: 'EVENT_SEND_GREETINGS_CLICKED_TFI',
  //User Events
  USER_MOBILE_NUMBER_FILLED: 'USER_MOBILE_NUMBER_FILLED_TFI',

  // Communication
  COMMUNICATIONS_CLICKED_TFI: 'COMMUNICATIONS_CLICKED_TFI',
  ALL_POSTS_CLICKED_TFI: 'ALL_POSTS_CLICKED_TFI',
  MY_POSTS_CLICKED_TFI: 'MY_POSTS_CLICKED_TFI',
  DRAFT_POSTS_CLICKED_TFI: 'DRAFT_POSTS_CLICKED_TFI',
  CREATE_NEW_POST_CLICKED_TFI: 'CREATE_NEW_POST_CLICKED_TFI',
  CREATE_NEW_POST_POPUP_CLICKED_TFI: 'CREATE_NEW_POST_POPUP_CLICKED_TFI',
  ANNOUNCEMENT_TITLE_FILLED_TFI: 'ANNOUNCEMENT_TITLE_FILLED_TFI',
  ANNOUNCEMENT_TEXT_FILLED_TFI: 'ANNOUNCEMENT_TEXT_FILLED_TFI',
  ATTACH_ANNOUNCEMENT_CLICKED_TFI: 'ATTACH_ANNOUNCEMENT_CLICKED_TFI',
  ANNOUNCEMENT_ATTACHED_TFI: 'ANNOUNCEMENT_ATTACHED_TFI',
  ANNOUNCEMENT_ATTACHMENT_ERROR_TFI: 'ANNOUNCEMENT_ATTACHMENT_ERROR_TFI',
  ANNOUNCEMENT_ATTACHMENT_DELETED_TFI: 'ANNOUNCEMENT_ATTACHMENT_DELETED_TFI',
  ANNOUNCEMENT_MESSAGE_CREATED_TFI: 'ANNOUNCEMENT_MESSAGE_CREATED_TFI',
  ANNOUNCEMENT_CHANNEL_SELECTED_TFI: 'ANNOUNCEMENT_CHANNEL_SELECTED_TFI',
  EXIT_ANNOUNCEMENT_POPUP_SHOWN_TFI: 'EXIT_ANNOUNCEMENT_POPUP_SHOWN_TFI',
  EXIT_ANNOUNCEMENT_POPUP_CLICKED_TFI: 'EXIT_ANNOUNCEMENT_POPUP_CLICKED_TFI',
  EDIT_DRAFT_CLICKED_TFI: 'EDIT_DRAFT_CLICKED_TFI',
  ADD_FILTER_CLICKED_TFI: 'ADD_FILTER_CLICKED_TFI',
  USER_SEGMENT_NODE_CLICKED_TFI: 'USER_SEGMENT_NODE_CLICKED_TFI',
  APPLY_FILTER_CLICKED_TFI: 'APPLY_FILTER_CLICKED_TFI',
  CANCEL_FILTER_CLICKED_TFI: 'CANCEL_FILTER_CLICKED_TFI',
  CLEAR_ALL_FILTER_CLICKED_TFI: 'CLEAR_ALL_FILTER_CLICKED_TFI',
  NEW_POST_CONFIRMATION_POPUP_SHOWN_TFI:
    'NEW_POST_CONFIRMATION_POPUP_SHOWN_TFI',
  NEW_POST_CONFIRMATION_POPUP_CLICKED_TFI:
    'NEW_POST_CONFIRMATION_POPUP_CLICKED_TFI',
  NEW_POST_CREATED_TFI: 'NEW_POST_CREATED_TFI',
  FEE_MANAGEMENT_CLICKED_TFI: 'FEE_MANAGEMENT_CLICKED_TFI',

  //fee kyc
  COMPLETE_KYC_CLICKED_TFI: 'COMPLETE_KYC_CLICKED_TFI',
  // Fee Module
  FEES_REPORTS_CLICKED_TFI: 'FEES_REPORTS_CLICKED_TFI',
  DOWNLOAD_RECEIPT_CLICKED_TFI: 'DOWNLOAD_RECEIPT_CLICKED_TFI',
  DOWNLOAD_CANCELLED_RECEIPT_CLICKED_TFI:
    'DOWNLOAD_CANCELLED_RECEIPT_CLICKED_TFI',
  RECEIPT_DOWNLOADED_TFI: 'RECEIPT_DOWNLOADED_TFI',
  CANCELLED_RECEIPT_DOWNLOADED_TFI: 'CANCELLED_RECEIPT_DOWNLOADED_TFI',
  VIEW_TXN_TIMELINE_CLICKED_TFI: 'VIEW_TXN_TIMELINE_CLICKED_TFI',
  UPDATE_TXN_STATUS_CLICKED_TFI: 'UPDATE_TXN_STATUS_CLICKED_TFI',
  TXN_STATUS_UPDATED_TFI: 'TXN_STATUS_UPDATED_TFI',
  DELETE_TXN_TFI: 'DELETE_TXN_TFI',
  CANCEL_TXN_TFI: 'CANCEL_TXN_TFI',
  TXN_RECEIPT_DELETED_TFI: 'TXN_RECEIPT_DELETED_TFI',
  TXN_CANCELLED_TFI: 'TXN_CANCELLED_TFI',
  DELETE_TXN_POPUP_CLICKED_TFI: 'DELETE_TXN_POPUP_CLICKED_TFI',
  CANCEL_TXN_POPUP_CLICKED_TFI: 'CANCEL_TXN_POPUP_CLICKED_TFI',

  FEE_ADD_FILTER_CLICKED_TFI: 'FEE_ADD_FILTER_CLICKED_TFI',
  FEE_APPLY_FILTER_CLICKED_TFI: 'FEE_APPLY_FILTER_CLICKED_TFI',
  RECORD_PAYMENT_INITIALIZED_TFI: 'RECORD_PAYMENT_INITIALIZED_TFI',
  RECORD_PAYMENT_CLICKED_TFI: 'RECORD_PAYMENT_CLICKED_TFI',

  CREATE_NEW_FEE_STRUCTURE_POPUP_CLICKED_TFI:
    'CREATE_NEW_FEE_STRUCTURE_POPUP_CLICKED_TFI',
  FEE_CLASS_CLICKED_TFI: 'FEE_CLASS_CLICKED_TFI',
  FEE_USER_PROFILE_CLICKED_TFI: 'FEE_USER_PROFILE_CLICKED_TFI',
  FEE_DUE_DATES_CLICKED_TFI: 'FEE_DUE_DATES_CLICKED_TFI',
  FEE_AMOUNT_CLICKED_TFI: 'FEE_AMOUNT_CLICKED_TFI',
  CLASSES_AND_PROFILES_SELECTED_TFI: 'CLASSES_AND_PROFILES_SELECTED_TFI',
  FEE_STRUCTURE_SELECTED_TFI: 'FEE_STRUCTURE_SELECTED_TFI',
  DUEDATES_SELECTED_TFI: 'DUEDATES_SELECTED_TFI',
  AMOUNT_SELECTED_TFI: 'AMOUNT_SELECTED_TFI',
  ADD_MORE_SECTION_CLICKED_TFI: 'ADD_MORE_SECTION_CLICKED_TFI',
  PUBLISH_FEE_STRUCTURE_CLICKED_TFI: 'PUBLISH_FEE_STRUCTURE_CLICKED_TFI',
  PUBLISH_FEE_STRUCTURE_POPUP_CLICKED_TFI:
    'PUBLISH_FEE_STRUCTURE_POPUP_CLICKED_TFI',
  ADD_NEW_DISCOUNT_CLICKED_TFI: 'ADD_NEW_DISCOUNT_CLICKED_TFI',
  DISCOUNT_DETAILS_FILLED_TFI: 'DISCOUNT_DETAILS_FILLED_TFI',
  DISCOUNT_DETAILS_COMPLETED_TFI: 'DISCOUNT_DETAILS_COMPLETED_TFI',
  APPLY_DISCOUNT_CLICKED_TFI: 'APPLY_DISCOUNT_CLICKED_TFI',
  EXIT_POPUP_SHOWN_TFI: 'EXIT_POPUP_SHOWN_TFI',
  EDIT_FEE_STRUCTURE_CLICKED_TFI: 'EDIT_FEE_STRUCTURE_CLICKED_TFI',
  FEE_STRUCTURE_VIEW_CHANGED_TFI: 'FEE_STRUCTURE_VIEW_CHANGED_TFI',
  DELETE_FEE_STRUCTURE_CLICKED_TFI: 'DELETE_FEE_STRUCTURE_CLICKED_TFI',
  FEE_STRUCTURE_DELETED_TFI: 'FEE_STRUCTURE_DELETED_TFI',
  FEE_STRUCTURE_PUBLISHED_TFI: 'FEE_STRUCTURE_PUBLISHED_TFI',
  PAYMENT_CONFIRMATION_POPUP_CLICKED_TFI:
    'PAYMENT_CONFIRMATION_POPUP_CLICKED_TFI',
  FEE_COLLECTION_CLICKED_TFI: 'FEE_COLLECTION_CLICKED_TFI',
  TRANSACTIONS_CLICKED_TFI: 'TRANSACTIONS_CLICKED_TFI',
  FEES_HELP_VIDEOS_CLICKED_TFI: 'FEES_HELP_VIDEOS_CLICKED_TFI',
  FEE_STRUCTURE_CLICKED_TFI: 'FEE_STRUCTURE_CLICKED_TFI',
  PAYMENT_GATEWAY_CLICKED_TFI: 'PAYMENT_GATEWAY_CLICKED_TFI',
  CREATE_FEE_STRUCTURE_CLICKED_TFI: 'CREATE_FEE_STRUCTURE_CLICKED_TFI',
  OFFERS_AND_DISCOUNTS_CLICKED_TFI: 'OFFERS_AND_DISCOUNTS_CLICKED_TFI',
  POST_QUESTION_FILLED_TFI: 'POST_QUESTION_FILLED_TFI',
  POST_DURATION_CLICKED_TFI: 'POST_DURATION_CLICKED_TFI',
  POST_DURATION_SELECTED_TFI: 'POST_DURATION_SELECTED_TFI',
  POLL_CHOICE_FILLED_TFI: 'POLL_CHOICE_FILLED_TFI',
  REMOVE_POLL_CHOICE_CLICKED_TFI: 'REMOVE_POLL_CHOICE_CLICKED_TFI',
  ADD_NEW_POLL_CHOICE_CLICKED_TFI: 'ADD_NEW_POLL_CHOICE_CLICKED_TFI',
  POLL_CHOICES_CREATED_TFI: 'POLL_CHOICES_CREATED_TFI',
  FEEDBACK_QUESTION_CREATED_TFI: 'FEEDBACK_QUESTION_CREATED_TFI',
  ATTACH_BUTTON_CLICKED_TFI: 'ATTACH_BUTTON_CLICKED_TFI',
  POST_ATTACHED_TFI: 'POST_ATTACHED_TFI',
  POST_ATTACHMENT_ERROR_TFI: 'POST_ATTACHMENT_ERROR_TFI',
  POST_ATTACHMENT_DELETED_TFI: 'POST_ATTACHMENT_DELETED_TFI',
  EXIT_POST_POPUP_SHOWN_TFI: 'EXIT_POST_POPUP_SHOWN_TFI',
  EXIT_POST_POPUP_CLICKED_TFI: 'EXIT_POST_POPUP_CLICKED_TFI',
  USER_SEGMENT_SELECTED_TFI: 'USER_SEGMENT_SELECTED_TFI',
  POST_CHANNEL_SELECTED_TFI: 'POST_CHANNEL_SELECTED_TFI',
  POLL_RESULTS_VISIBILITY_CONFIRMATION_TFI:
    'POLL_RESULTS_VISIBILITY_CONFIRMATION_TFI',
  ANONYMOUS_RESPONSE_CONFIRMATION_TFI: 'ANONYMOUS_RESPONSE_CONFIRMATION_TFI',
  VIEW_ATTACHMENT_CLICKED_TFI: 'VIEW_ATTACHMENT_CLICKED_TFI',
  FEE_REPORT_CLICKED_TFI: 'FEE_REPORT_CLICKED_TFI',
  FEE_REPORT_NODE_CLICKED_TFI: 'FEE_REPORT_NODE_CLICKED_TFI',
  FEE_REPORT_CARD_TFI: 'FEE_REPORT_CARD_TFI',

  // Exam planner
  EXAM_PLANNER_SIDE_BAR_CLICKED_TFI: 'EXAM_PLANNER_SIDE_BAR_CLICKED_TFI',
  CREATE_SCHEDULE_CLICKED_TFI: 'CREATE_SCHEDULE_CLICKED_TFI',
  SAVE_EXAM_SCHEDULE_CLICKED_TFI: 'SAVE_EXAM_SCHEDULE_CLICKED_TFI',
  EDIT_EXAM_STRUCTURE_CLICKED_TFI: 'EDIT_EXAM_STRUCTURE_CLICKED_TFI',
  DELETE_EXAM_SCHEDULE_CLICKED_TFI: 'DELETE_EXAM_SCHEDULE_CLICKED_TFI',
  EXAM_SCHEDULE_DELETED_TFI: 'EXAM_SCHEDULE_DELETED_TFI',
  ADD_SUBJECT_EXAM_SCHEDULE_TFI: 'ADD_SUBJECT_EXAM_SCHEDULE_TFI',
  MARK_HOLIDAY_CLICKED_TFI: 'MARK_HOLIDAY_CLICKED_TFI',
  HOLIDAY_MARKED_TFI: 'HOLIDAY_MARKED_TFI',
  SAVE_SUBJECT_EXAM_SCHEDULE_TFI: 'SAVE_SUBJECT_EXAM_SCHEDULE_TFI',
  PUBLISH_EXAM_SCHEDULE_CLICKED_TFI: 'PUBLISH_EXAM_SCHEDULE_CLICKED_TFI',
  EXAM_SCHEDULE_PUBLISHED_TFI: 'EXAM_SCHEDULE_PUBLISHED_TFI',
  DELETE_SUBJECT_EXAM_CLICKED_TFI: 'DELETE_SUBJECT_EXAM_CLICKED_TFI',
  VIEW_EXAM_RESULT_CLICKED_TFI: 'VIEW_EXAM_RESULT_CLICKED_TFI',
  SUBJECT_EXAM_DELETED_TFI: 'SUBJECT_EXAM_DELETED_TFI',

  // Content MVP
  CONTENT_SIDE_BAR_CLICKED: 'CONTENT_SIDE_BAR_CLICKED',
  REPORT_CARD_SIDE_BAR_CLICKED: 'REPORT_CARD_SIDE_BAR_CLICKED',
  EXAM_CLICKED_TFI: 'EXAM_CLICKED_TFI',
  EXAM_MANAGEMENT_SIDE_BAR_CLICKED: 'EXAM_MANAGEMENT_SIDE_BAR_CLICKED',
  CONTENT_CLICKED_TFI: 'CONTENT_CLICKED_TFI',
  PC_LANG_SELECTED: 'PC_LANG_SELECTED',
  PC_CLASS_SELECTED: 'PC_CLASS_SELECTED',
  PC_SUBJECT_SELECTED: 'PC_SUBJECT_SELECTED',
  PC_TOPIC_SELECTED: 'PC_TOPIC_SELECTED',
  PC_MATERIAL_CLICKED: 'PC_MATERIAL_CLICKED',
  PC_VIEW_ALL_CLICKED: 'PC_VIEW_ALL_CLICKED',
  PC_REPORT_CONTENT_CLICKED: 'PC_REPORT_CONTENT_CLICKED',
  PC_REPORT_BUTTON_CLICKED: 'PC_REPORT_BUTTON_CLICKED',
  PC_REPORT_OKAY_CLICKED: 'PC_REPORT_OKAY_CLICKED',
  PC_VIDEO_PLAY_EVENT: 'PC_VIDEO_PLAY_EVENT',
  PC_VIDEO_CLOSE_POPUP: 'PC_VIDEO_CLOSE_POPUP',
  FEATURE_LOCKED_POP_UP_SHOWN: 'FEATURE_LOCKED_POP_UP_SHOWN',
  CONTACT_SALES_LOCKED_FEATURE_POPUP: 'CONTACT_SALES_LOCKED_FEATURE_POPUP',
  ENGLISH_SAMPLE_VIDEO_CLICKED_TFI: 'ENGLISH_SAMPLE_VIDEO_CLICKED_TFI',
  HINDI_SAMPLE_VIDEO_CLICKED: 'HINDI_SAMPLE_VIDEO_CLICKED',
  CONTACT_SALES_CLICKED_TFI: 'CONTACT_SALES_CLICKED_TFI',
  BUY_NOW_CLICKED_TFI: 'BUY_NOW_CLICKED_TFI',

  // Yearly Calendar
  YEARLY_CALENDAR_CLICKED_TFI: 'YEARLY_CALENDAR_CLICKED_TFI',
  LINK_COPIED_VIA_BANNER: 'LINK_COPIED_VIA_BANNER',
  //Document Generation
  CERTIFICATE_CLICKED_TFI: 'CERTIFICATE_CLICKED_TFI',
  BONAFIDE_CERTIFICATE_CLICKED_TFI: 'BONAFIDE_CERTIFICATE_CLICKED_TFI',
  CHARACTER_CERTIFICATE_CLICKED_TFI: 'CHARACTER_CERTIFICATE_CLICKED_TFI',
  TRANSFER_CERTIFICATE_CLICKED_TFI: 'TRANSFER_CERTIFICATE_CLICKED_TFI',
  GENERATE_NEW_CERTIFICATE_CLICKED_TFI: 'GENERATE_NEW_CERTIFICATE_CLICKED_TFI',
  PROCEED_CLICKED_TFI: 'PROCEED_CLICKED_TFI',
  ENTER_STUDENT_DETAILS_TFI: 'ENTER_STUDENT_DETAILS_TFI',
  PREVIEW_CLICKED_TFI: 'PREVIEW_CLICKED_TFI',
  CERTIFICATE_GENERATE_CLICKED_TFI: 'CERTIFICATE_GENERATE_CLICKED_TFI',
  CERTIFICATE_GENERATED_TFI: 'CERTIFICATE_GENERATED_TFI',
  PRINT_CERTIFICATE_CLICKED_TFI: 'PRINT_CERTIFICATE_CLICKED_TFI',
  DOWNLOAD_CERTIFICATE_CLICKED_TFI: 'DOWNLOAD_CERTIFICATE_CLICKED_TFI',
  CERTIFICATE_DOWNLOADED_TFI: 'CERTIFICATE_DOWNLOADED_TFI',
  GENERATED_CERTIFICATES_CLICKED_TFI: 'GENERATED_CERTIFICATES_CLICKED_TFI',
  ALL_CERTIFICATE_CLICKED_TFI: 'ALL_CERTIFICATE_CLICKED_TFI',
  // ALL_PENDING_REQUESTS_CLICKED_TFI :'',
  // DENY_CERTIFICATE_REQUEST_CLICKED_TFI :'',
  // DENY_REQUEST_POPUP_APPEARED_TFI :'',
  // DENY_REASON_SELECTED_TFI :'',
  // CERTIFICATE_DENIED_TFI :'',
  // STUDENT_STATUS_MESSAGE_CLICKED_TFI :'',
  // ADD_FILTERS_CLICKED_TFI :'',
  // VIEW_STUDENT_PROFILE_CLICKED_TFI :'',
  // STUDENT_DETAILS_APPEAR_TFI :'',
  // CERTIFICATE_RPINTED_TFI :'',
  // PENDING_REQUESTS_CLCIKED_TFI :'',
  // NOTIFY_TO_COLLECT_CLICKED_TFI :''

  //Multiple Paymentgateway
  PAYMENT_GATEWAY_SELECTED_TFI: 'PAYMENT_GATEWAY_SELECTED_TFI',
  FEE_PAYMENT_GATEWAY_EDIT_DETAILS_CLICKED_TFI:
    'FEE_PAYMENT_GATEWAY_EDIT_DETAILS_CLICKED_TFI',
  ACCESS_TEACHPAY_DASHBOARD_CLICKED_TFI:
    'ACCESS_TEACHPAY_DASHBOARD_CLICKED_TFI',
  CHANGE_GATEWAY_CLICKED_TFI: 'CHANGE_GATEWAY_CLICKED_TFI',
  REGISTER_FOR_GATEWAY_CLICKED_TFI: 'REGISTER_FOR_GATEWAY_CLICKED_TFI',
  VERIFY_API_CREDS_CLICKED_TFI: 'VERIFY_API_CREDS_CLICKED_TFI',
  RAZORPAY_DASHBOARD_OPENED_TFI: 'RAZORPAY_DASHBOARD_OPENED_TFI',
  DOWNLOAD_REPORT_CLICKED_TFI: 'DOWNLOAD_REPORT_CLICKED_TFI',

  // Attendnce
  ATTENDANCE_CLICKED_TFI: 'ATTENDANCE_CLICKED_TFI',
  ATTENDANCE_DATE_CLICKED_TFI: 'ATTENDANCE_DATE_CLICKED_TFI',
  DOWNLOAD_ATTENDANCE_REPORT_CLICKED_TFI:
    'DOWNLOAD_ATTENDANCE_REPORT_CLICKED_TFI',
  ATTENDANCE_REPORT_DOWNLOADED_TFI: 'ATTENDANCE_REPORT_DOWNLOADED_TFI',
  VIEW_ATTENDANCE_CLICKED_TFI: 'VIEW_ATTENDANCE_CLICKED_TFI',
  ATTENDANCE_DATE_ENTERED_TFI: 'ATTENDANCE_DATE_ENTERED_TFI',
  MANAGE_ATTENDANCE_CLICKED_TFI: 'MANAGE_ATTENDANCE_CLICKED_TFI',
  ADD_CLASS_TEACHER_CLICKED_TFI: 'ADD_CLASS_TEACHER_CLICKED_TFI',
  LEAVE_MANAGEMENT_CLICKED_TFI: 'LEAVE_MANAGEMENT_CLICKED_TFI',
  CLASSROOM_REPORTS_CLICKED_TFI: 'CLASSROOM_REPORTS_CLICKED_TFI',
  SHOW_FULL_ACADEMIC_SESSION_FEE_CLICKED_TFI:
    'SHOW_FULL_ACADEMIC_SESSION_FEE_CLICKED_TFI',
  MARK_ATTENDANCE_CLICKED_TFI: 'MARK_ATTENDANCE_CLICKED_TFI',
  SAVE_ATTENDANCE_CLICKED_TFI: 'SAVE_ATTENDANCE_CLICKED_TFI',
  ATTENDANCE_SAVED_TFI: 'ATTENDANCE_SAVED_TFI',
  // Leave management
  CONFIRM_LEAVE_BALANCE_CLICKED_TFI: 'CONFIRM_LEAVE_BALANCE_CLICKED_TFI',
  ADD_LEAVE_FOR_EMPLOYEE_CLICKED_TFI: 'ADD_LEAVE_FOR_EMPLOYEE_CLICKED_TFI',
  SELECT_LEAVE_EMPLOYEE_TFI: 'SELECT_LEAVE_EMPLOYEE_TFI',
  SELECT_LEAVE_TYPE_TFI: 'SELECT_LEAVE_TYPE_TFI',
  ADD_LEAVE_CLICKED_TFI: 'ADD_LEAVE_CLICKED_TFI',
  PENDING_LEAVE_REQUEST_CLICKED_TFI: 'PENDING_LEAVE_REQUEST_CLICKED_TFI',
  APPROVE_LEAVE_CLICKED_TFI: 'APPROVE_LEAVE_CLICKED_TFI',
  LEAVE_APPROVED_TFI: 'LEAVE_APPROVED_TFI',
  REJECT_LEAVE_CLICKED_TFI: 'REJECT_LEAVE_CLICKED_TFI',
  LEAVE_REJECTED_TFI: 'LEAVE_REJECTED_TFI',
  PAST_LEAVES_CLICKED_TFI: 'PAST_LEAVES_CLICKED_TFI',
  VIEW_LEAVE_HISTORY_CLICKED_TFI: 'VIEW_LEAVE_HISTORY_CLICKED_TFI',
  SELECT_LEAVE_DATE_TFI: 'SELECT_LEAVE_DATE_TFI',
  CANCEL_LEAVE_CLICKED_TFI: 'CANCEL_LEAVE_CLICKED_TFI',
  LEAVE_ADDED_TFI: 'LEAVE_ADDED_TFI',
  APPROVE_LEAVE_POPUP_CANCEL_CLICKED_TFI:
    'APPROVE_LEAVE_POPUP_CANCEL_CLICKED_TFI',
  REJECT_LEAVE_POPUP_CANCEL_CLICKED_TFI:
    'REJECT_LEAVE_POPUP_CANCEL_CLICKED_TFI',
  LEAVE_LIMIT_EXCEED_TFI: 'LEAVE_LIMIT_EXCEED_TFI',
  LEAVE_NOT_AVAILABLE_TFI: 'LEAVE_NOT_AVAILABLE_TFI',
  REDIRECTED_TO_MANAGE_LEAVE_TFI: 'REDIRECTED_TO_MANAGE_LEAVE_TFI',
  UPDATE_LEAVE_LIMIT_CLICKED_TFI: 'UPDATE_LEAVE_LIMIT_CLICKED_TFI',
  MANAGE_LEAVE_BALANCE_CLICKED_TFI: 'MANAGE_LEAVE_BALANCE_CLICKED_TFI',
  REASON_FOR_LEAVE_FILLED_TFI: 'REASON_FOR_LEAVE_FILLED_TFI',
  REQUEST_LEAVE_CLICKED_TFI: 'REQUEST_LEAVE_CLICKED_TFI',
  LEAVE_REQUESTED_TFI: 'LEAVE_REQUESTED_TFI',
  LEAVE_REQUEST_CANCEL_TFI: 'LEAVE_REQUEST_CANCEL_TFI',
  LEAVE_CANCELED_TFI: 'LEAVE_CANCELED_TFI',
  REQUEST_LEAVE_FOR_SELF_CLICKED_TFI: 'REQUEST_LEAVE_FOR_SELF_CLICKED_TFI',
  DOWNLOAD_LEAVE_DATA_CLICKED_TFI: 'DOWNLOAD_LEAVE_DATA_CLICKED_TFI',
  LEAVE_DATA_DOWNLOAD_COMPLETED_TFI: 'LEAVE_DATA_DOWNLOAD_COMPLETED_TFI',
  EDIT_LEAVE_CLICKED_TFI: 'EDIT_LEAVE_CLICKED_TFI',
  LEAVE_EDITED_TFI: 'LEAVE_EDITED_TFI',
  EDIT_LEAVE_FOR_SELF_CLICKED_TFI: 'EDIT_LEAVE_FOR_SELF_CLICKED_TFI',
  EDIT_LEAVE_FOR_EMPLOYEE_CLICKED_TFI: 'EDIT_LEAVE_FOR_EMPLOYEE_CLICKED_TFI',
  UPCOMING_LEAVE_DATA_DURATION_SELECTED_TFI:
    'UPCOMING_LEAVE_DATA_DURATION_SELECTED_TFI',
  ON_LEAVE_DATA_DURATION_SELECTED_TFI: 'ON_LEAVE_DATA_DURATION_SELECTED_TFI',

  // Staff Attendance
  STAFF_ATTENDANCE_CLICKED_TFI: 'STAFF_ATTENDANCE_CLICKED_TFI',
  STAFF_ATTENDANCE_DATE_CLICKED_TFI: 'STAFF_ATTENDANCE_DATE_CLICKED_TFI',
  DOWNLOAD_STAFF_ATTENDANCE_REPORT_CLICKED_TFI:
    'DOWNLOAD_STAFF_ATTENDANCE_REPORT_CLICKED_TFI',
  STAFF_ATTENDANCE_REPORT_DOWNLOADED_TFI:
    'STAFF_ATTENDANCE_REPORT_DOWNLOADED_TFI',
  UPDATE_STAFF_ATTENDANCE_CLICKED_TFI: 'UPDATE_STAFF_ATTENDANCE_CLICKED_TFI',
  SAVE_STAFF_ATTENDANCE_CLICKED_TFI: 'SAVE_STAFF_ATTENDANCE_CLICKED_TFI',
  STAFF_ATTENDANCE_SAVED_TFI: 'STAFF_ATTENDANCE_SAVED_TFI',
  MARK_STAFF_ATTENDANCE_CLICKED_TFI: 'MARK_STAFF_ATTENDANCE_CLICKED_TFI',
  MARK_ALL_STAFF_PRESENT_CLICKED_TFI: 'MARK_ALL_STAFF_PRESENT_CLICKED_TFI',
  MARK_ALL_STAFF_ABSENT_CLICKED_TFI: 'MARK_ALL_STAFF_ABSENT_CLICKED_TFI',
  STAFF_ATTENDANCE_TOTAL_STAFF_TAB_CLICKED_TFI:
    'STAFF_ATTENDANCE_TOTAL_STAFF_TAB_CLICKED_TFI',
  STAFF_ATTENDANCE_PRESENT_STAFF_TAB_CLICKED_TFI:
    'STAFF_ATTENDANCE_PRESENT_STAFF_TAB_CLICKED_TFI',
  STAFF_ATTENDANCE_ABSENT_STAFF_TAB_CLICKED_TFI:
    'STAFF_ATTENDANCE_ABSENT_STAFF_TAB_CLICKED_TFI',
  STAFF_ATTENDANCE_NOT_MARKED_STAFF_TAB_CLICKED_TFI:
    'STAFF_ATTENDANCE_NOT_MARKED_STAFF_TAB_CLICKED_TFI',
  STAFF_ATTENDANCE_MARK_ALL_AS_PRESENT_CLICKED_TFI:
    'STAFF_ATTENDANCE_MARK_ALL_AS_PRESENT_CLICKED_TFI',
  STAFF_ATTENDANCE_MARK_PRESENT_CLICKED_TFI:
    'STAFF_ATTENDANCE_MARK_PRESENT_CLICKED_TFI',
  STAFF_ATTENDANCE_MARK_ABSENT_CLICKED_TFI:
    'STAFF_ATTENDANCE_MARK_ABSENT_CLICKED_TFI',
  STAFF_ATTENDANCE_NOT_MARKED_CLICKED_TFI:
    'STAFF_ATTENDANCE_NOT_MARKED_CLICKED_TFI',
  STAFF_LEAVE_DETAILS_VIEW_CLICKED_TFI: 'STAFF_LEAVE_DETAILS_VIEW_CLICKED_TFI',
  SAVE_STAFF_ATTENDANCE_POP_UP_CLICKED_TFI:
    'SAVE_STAFF_ATTENDANCE_POP_UP_CLICKED_TFI',
  STAFF_ATTENDANCE_UNSAVED_CHANGES_POPUP_CLICKED_TFI:
    'STAFF_ATTENDANCE_UNSAVED_CHANGES_POPUP_CLICKED_TFI',
  STAFF_ATTENDANCE_EDIT_CLICKED_TFI: 'STAFF_ATTENDANCE_EDIT_CLICKED_TFI',
  MARK_LEAVE_CLICKED_TFI: 'MARK_LEAVE_CLICKED_TFI',
  MARK_LEAVE_CONFIRM_CLICKED_TFI: 'MARK_LEAVE_CONFIRM_CLICKED_TFI',
  EDIT_STAFF_ATTENDANCE_CLICKED_TFI: 'EDIT_STAFF_ATTENDANCE_CLICKED_TFI',
  EDIT_STAFF_ATTENDANCE_SAVE_CLICKED_TFI:
    'EDIT_STAFF_ATTENDANCE_SAVE_CLICKED_TFI',
  HRMS_VIEW_ATTENDANCE_REQUESTS_CLICKED_TFI:
    'HRMS_VIEW_ATTENDANCE_REQUESTS_CLICKED_TFI',
  HRMS_ATTENDANCE_REQUESTS_ACCEPTED_TFI:
    'HRMS_ATTENDANCE_REQUESTS_ACCEPTED_TFI',
  HRMS_ATTENDANCE_REQUESTS_REJECTED_TFI:
    'HRMS_ATTENDANCE_REQUESTS_REJECTED_TFI',
  STAFF_ATTENDANCE_TAB_CLICKED_TFI: 'STAFF_ATTENDANCE_TAB_CLICKED_TFI',
  MY_ATTENDANCE_TAB_CLICKED_TFI: 'MY_ATTENDANCE_TAB_CLICKED_TFI',
  GEOFENCE_MARK_ATTENDANCE_CLICKED: 'GEOFENCE_MARK_ATTENDANCE_CLICKED',

  // Dashboard reports
  DASHBOARD_REPORT_CLICKED_TFI: 'DASHBOARD_REPORT_CLICKED_TFI',
  FEE_REPORT_DOWNLOAD_CLICKED_TFI: 'FEE_REPORT_DOWNLOAD_CLICKED_TFI',
  FEE_REPORT_SESSION_TFI: 'FEE_REPORT_SESSION_TFI',
  FEE_REPORT_SESSION_APPLIED_TFI: 'FEE_REPORT_SESSION_APPLIED_TFI',
  FEE_REPORT_FILTER_TFI: 'FEE_REPORT_FILTER_TFI',
  FEE_REPORT_APPLY_FILTER_TFI: 'FEE_REPORT_APPLY_FILTER_TFI',
  FEE_REPORT_DOWNLOAD_OVERVIEW_TFI: 'FEE_REPORT_DOWNLOAD_OVERVIEW_TFI',
  CLASS_ATTENDANCE_REPORT_DOWNLOAD_CLICKED_TFI:
    'CLASS_ATTENDANCE_REPORT_DOWNLOAD_CLICKED_TFI',
  PERFORMANCE_REPORT_DOWNLOAD_CLICKED_TFI:
    'PERFORMANCE_REPORT_DOWNLOAD_CLICKED_TFI',
  VIEW_DOWNLOAD_LOG_CLICKED_TFI: 'VIEW_DOWNLOAD_LOG_CLICKED_TFI',
  CLASS_ATTENDANCE_REPORT_POPUP_CLICKED_TFI:
    'CLASS_ATTENDANCE_REPORT_POPUP_CLICKED_TFI',
  CLASS_ATTENDANCE_REPORT_DOWNLOADED_TFI:
    'CLASS_ATTENDANCE_REPORT_DOWNLOADED_TFI',
  FEE_TRANSACTION_REPORT_CLICKED_TFI: 'FEE_TRANSACTION_REPORT_CLICKED_TFI',
  FEE_COLLECTION_REPORT_CLICKED_TFI: 'FEE_COLLECTION_REPORT_CLICKED_TFI',

  //Exam Structure
  EXAM_STRUCTURE_SIDEBAR_CLICKED_TFI: 'EXAM_STRUCTURE_SIDEBAR_CLICKED_TFI',
  EXAM_STRUCTURE_CREATE_CLICKED_TFI: 'EXAM_STRUCTURE_CREATE_CLICKED_TFI',
  EXAM_STRUCTURE_IMPORT_CLICKED_TFI: 'EXAM_STRUCTURE_IMPORT_CLICKED_TFI',
  EXAM_STRUCTURE_IMPORT_EXISTING_CLICKED_TFI:
    'EXAM_STRUCTURE_IMPORT_EXISTING_CLICKED_TFI',
  EXAM_STRUCTURE_ADD_PASS_CRITERIA_TFI: 'EXAM_STRUCTURE_ADD_PASS_CRITERIA_TFI',
  EXAM_STRUCTURE_DELETE_TERM_NAME_TFI: 'EXAM_STRUCTURE_DELETE_TERM_NAME_TFI',
  EXAM_STRUCTURE_DELETE_EXAM_NAME_TFI: 'EXAM_STRUCTURE_DELETE_EXAM_NAME_TFI',
  EXAM_STRUCTURE_ADD_TERM_TFI: 'EXAM_STRUCTURE_ADD_TERM_TFI',
  EXAM_STRUCTURE_ADD_EXAM_TFI: 'EXAM_STRUCTURE_ADD_EXAM_TFI',
  EXAM_STRUCTURE_SAVE_CLICKED_TFI: 'EXAM_STRUCTURE_SAVE_CLICKED_TFI',
  EXAM_STRUCTURE_EDIT_PATTERN_CLICKED_TFI:
    'EXAM_STRUCTURE_EDIT_PATTERN_CLICKED_TFI',
  EXAM_STRUCTURE_EDIT_PATTERN_POPUP_CLICKED_TFI:
    'EXAM_STRUCTURE_EDIT_PATTERN_POPUP_CLICKED_TFI',
  EXAM_STRUCTURE_EXAM_PATTERN_EDIT_SAVE_POPUP_TFI:
    'EXAM_STRUCTURE_EXAM_PATTERN_EDIT_SAVE_POPUP_TFI',
  EXAM_STRUCTURE_ADDITIONAL_EXAMS_VIEW_RESULTS_CLICKED_TFI:
    'EXAM_STRUCTURE_ADDITIONAL_EXAMS_VIEW_RESULTS_CLICKED_TFI',
  EXAM_STRUCTURE_PATTERN_PRINT_CLICKED_TFI:
    'EXAM_STRUCTURE_PATTERN_PRINT_CLICKED_TFI',
  EXAM_STRUCTURE_ADD_TO_TERM_CLICKED_TFI:
    'EXAM_STRUCTURE_ADD_TO_TERM_CLICKED_TFI',
  EXAM_STRUCTURE_SELECT_TERM_POPUP_CLICKED_TFI:
    'EXAM_STRUCTURE_SELECT_TERM_POPUP_CLICKED_TFI',
  EXAM_STRUCTURE_EXIT_WITHOUT_COMPLETE_POPUP:
    'EXAM_STRUCTURE_EXIT_WITHOUT_COMPLETE_POPUP',
  EXAM_STRUCTURE_CONFIGURE_CLICKED_TFI: 'EXAM_STRUCTURE_CONFIGURE_CLICKED_TFI',
  EXAM_STRUCTURE_GRADE_CLICKED_TFI: 'EXAM_STRUCTURE_GRADE_CLICKED_TFI',
  EXAM_STRUCTURE_GRADE_SAVE_CLIKCED_TFI:
    'EXAM_STRUCTURE_GRADE_SAVE_CLIKCED_TFI',
  EXAM_STRUCTURE_ACADEMIC_SESSION_LEVEL_SELECTED_TFI:
    'EXAM_STRUCTURE_ACADEMIC_SESSION_LEVEL_SELECTED_TFI',
  EXAM_STRUCTURE_TERM_LEVEL_SELECTED_TFI:
    'EXAM_STRUCTURE_TERM_LEVEL_SELECTED_TFI',
  EXAM_STRUCTURE_EXAM_LEVEL_SELECTED_TFI:
    'EXAM_STRUCTURE_EXAM_LEVEL_SELECTED_TFI',
  EXAM_STRUCTURE_ADD_MORE_GRADE_SCALE_CLICKED_TFI:
    'EXAM_STRUCTURE_ADD_MORE_GRADE_SCALE_CLICKED_TFI',
  EXAM_STRUCTURE_ADD_MORE_GRADE_SCALE_DELETE_CLICKED_TFI:
    'EXAM_STRUCTURE_ADD_MORE_GRADE_SCALE_DELETE_CLICKED_TFI',
  EXAM_STRUCTURE_PASSING_CRITERIA_NODE_CLICKED_TFI:
    'EXAM_STRUCTURE_PASSING_CRITERIA_NODE_CLICKED_TFI',

  // Report Card
  REPORT_CARD_SIDEBAR_CLICKED_TFI: 'REPORT_CARD_SIDEBAR_CLICKED_TFI',
  REPORT_CARD_GO_TO_EXAM_STRUCTURE_CLICKED_TFI:
    'REPORT_CARD_GO_TO_EXAM_STRUCTURE_CLICKED_TFI',
  REPORT_CARD_STD_GO_TO_EXAM_STRUCTURE_CLICKED_TFI:
    'REPORT_CARD_STD_GO_TO_EXAM_STRUCTURE_CLICKED_TFI',
  REPORT_CARD_CREATE_OR_CHOOSE_TEMPLATE_CLICKED_TFI:
    'REPORT_CARD_CREATE_OR_CHOOSE_TEMPLATE_CLICKED_TFI',
  REPORT_CARD_CREATE_NEW_CLICKED_TFI: 'REPORT_CARD_CREATE_NEW_CLICKED_TFI',
  REPORT_CARD_TEMPLATE_PROCEED_CLICKED_TFI:
    'REPORT_CARD_TEMPLATE_PROCEED_CLICKED_TFI',
  REPORT_CARD_SAVE_TEMPLATE_CLICKED_TFI:
    'REPORT_CARD_SAVE_TEMPLATE_CLICKED_TFI',
  REPORT_CARD_CANCEL_CLICKED_TFI: 'REPORT_CARD_CANCEL_CLICKED_TFI',
  REPORT_CARD_SECTION_REPORT_CARD_VIEW_CLICKED_TFI:
    'REPORT_CARD_SECTION_REPORT_CARD_VIEW_CLICKED_TFI',
  REPORT_CARD_EDIT_TEMPLATE_CLICKED_TFI:
    'REPORT_CARD_EDIT_TEMPLATE_CLICKED_TFI',
  REPORT_CARD_CHANGE_CLICKED_TFI: 'REPORT_CARD_CHANGE_CLICKED_TFI',
  REPORT_CARD_GENERATE_CARDS_CLICKED_TFI:
    'REPORT_CARD_GENERATE_CARDS_CLICKED_TFI',
  REPORT_CARD_PRINT_REPORT_CARDS_CLICKED_TFI:
    'REPORT_CARD_PRINT_REPORT_CARDS_CLICKED_TFI',
  REPORT_CARD_DOWNLOAD_CLICKED_TFI: 'REPORT_CARD_DOWNLOAD_CLICKED_TFI',
  REPORT_CARD_UPDATE_AVAILABLE_CLICKED_TFI:
    'REPORT_CARD_UPDATE_AVAILABLE_CLICKED_TFI',
  REPORT_CARD_CLOSE_PREVIEW_MARKS_CLICKED_TFI:
    'REPORT_CARD_CLOSE_PREVIEW_MARKS_CLICKED_TFI',
  REPORT_CARD_PREVIEW_MARKS_CLICKED_TFI:
    'REPORT_CARD_PREVIEW_MARKS_CLICKED_TFI',
  ID_CARD_SIDEBAR_CLICKED_TFI: 'ID_CARD_SIDEBAR_CLICKED_TFI',
  DOWNLOAD_DEMAND_LETTER_CLICKED_TFI: 'DOWNLOAD_DEMAND_LETTER_CLICKED_TFI',
  DEMAND_LETTER_DOWNLOADED_TFI: 'DEMAND_LETTER_DOWNLOADED_TFI',
  REPORT_CARD_SAVE_TEMPLATE_INITIATED_TFI:
    'REPORT_CARD_SAVE_TEMPLATE_INITIATED_TFI',
  REPORT_CARD_EVALUATION_TAB_CLICKED_TFI:
    'REPORT_CARD_EVALUATION_TAB_CLICKED_TFI',
  REPORT_CARD_REPORT_CARD_TAB_CLICKED_TFI:
    'REPORT_CARD_REPORT_CARD_TAB_CLICKED_TFI',
  REPORT_CARD_EVALUATION_TERM_TAB_CLICKED_TFI:
    'REPORT_CARD_EVALUATION_TERM_TAB_CLICKED_TFI',
  REPORT_CARD_EVALUATION_SUBJECT_TAB_CLICKED_TFI:
    'REPORT_CARD_EVALUATION_SUBJECT_TAB_CLICKED_TFI',
  REPORT_CARD_EVALUATION_WORKING_DAYS_EDIT_CLICKED_TFI:
    'REPORT_CARD_EVALUATION_WORKING_DAYS_EDIT_CLICKED_TFI',
  REPORT_CARD_EVALUATION_TOTAL_MARKS_EDIT_CLICKED_TFI:
    'REPORT_CARD_EVALUATION_TOTAL_MARKS_EDIT_CLICKED_TFI',
  REPROT_CARD_EVALUATION_SAVE_CHANGES_CLICKED_TFI:
    'REPROT_CARD_EVALUATION_SAVE_CHANGES_CLICKED_TFI',
  REPORT_CARD_EVALUATION_CHANGES_SAVED_TFI:
    'REPORT_CARD_EVALUATION_CHANGES_SAVED_TFI',
  REPORT_CARD_SHOW_PENDING_EVALUATIONS_CLICKED_TFI:
    'REPORT_CARD_SHOW_PENDING_EVALUATIONS_CLICKED_TFI',
  REPORT_CARD_EVALUATION_STUDENT_SORT_FILTER_CLICKED_TFI:
    'REPORT_CARD_EVALUATION_STUDENT_SORT_FILTER_CLICKED_TFI',
  REPORT_CARD_UPLOAD_CSV_CLICKED_TFI: 'REPORT_CARD_UPLOAD_CSV_CLICKED_TFI',
  REPORT_CARD_DOWNLOAD_MARKSHEET_CSV_CLICKED_TFI:
    'REPORT_CARD_DOWNLOAD_MARKSHEET_CSV_CLICKED_TFI',
  REPORT_CARD_UPLOAD_CSV_INITIATED_TFI: 'REPORT_CARD_UPLOAD_CSV_INITIATED_TFI',
  REPORT_CARD_CSV_UPLOADED_TFI: 'REPORT_CARD_CSV_UPLOADED_TFI',
  REPORT_CARD_CSV_REUPLOAD_CLICKED_TFI: 'REPORT_CARD_CSV_REUPLOAD_CLICKED_TFI',
  REPORT_CARD_CSV_DELETE_CLICKED_TFI: 'REPORT_CARD_CSV_DELETE_CLICKED_TFI',
  REPORT_CARD_CSV_PROCEED_CLICKED_TFI: 'REPORT_CARD_CSV_PROCEED_CLICKED_TFI',
  REPORT_CARD_DOWNLOAD_CSV_ERROR_CLICKED_TFI:
    'REPORT_CARD_DOWNLOAD_CSV_ERROR_CLICKED_TFI',
  REPORT_CARD_IMPORT_INITIALIZED_CLICKED_TFI:
    'REPORT_CARD_IMPORT_INITIALIZED_CLICKED_TFI',
  REPORT_CARD_IMPORT_TEMPLATE_SELECTED_TFI:
    'REPORT_CARD_IMPORT_TEMPLATE_SELECTED_TFI',
  REPORT_CARD_IMPORT_FINALIZED_CLICKED_TFI:
    'REPORT_CARD_IMPORT_FINALIZED_CLICKED_TFI',
  REPORT_CARD_IMPORT_CROSS_CLICKED_TFI: 'REPORT_CARD_IMPORT_CROSS_CLICKED_TFI',
  REPORT_CARD_IMPORTED_TFI: 'REPORT_CARD_IMPORTED_TFI',
  REPORT_CARD_EDIT_SCHOOL_DETAILS_CLICKED_TFI:
    'REPORT_CARD_EDIT_SCHOOL_DETAILS_CLICKED_TFI',
  REPORT_CARD_SCHOOL_DETAILS_UPDATE_CLICKED_TFI:
    'REPORT_CARD_SCHOOL_DETAILS_UPDATE_CLICKED_TFI',
  REPORT_CARD_SCHOOL_DETAILS_UPDATED_TFI:
    'REPORT_CARD_SCHOOL_DETAILS_UPDATED_TFI',
  REPORT_CARD_MANAGE_CLICKED_TFI: 'REPORT_CARD_MANAGE_CLICKED_TFI',
  REPORT_CARD_APPLY_CLICKED_TFI: 'REPORT_CARD_APPLY_CLICKED_TFI',
  REPORT_CARD_SCHOLASTIC_CONVERT_TO_GRADE_CLICKED_TFI:
    'REPORT_CARD_SCHOLASTIC_CONVERT_TO_GRADE_CLICKED_TFI',
  REPORT_CARD_SCHOLASTIC_SETUP_PASSING_PERCENTAGE_CLICKED_TFI:
    'REPORT_CARD_SCHOLASTIC_SETUP_PASSING_PERCENTAGE_CLICKED_TFI',
  REPORT_CARD_SCHOLASTIC_GRADE_CATEGORY_ACTION_CLICKED_TFI:
    'REPORT_CARD_SCHOLASTIC_GRADE_CATEGORY_ACTION_CLICKED_TFI',
  REPORT_CARD_SCHOLASTIC_SETUP_PASSING_GRADE_CLICKED_TFI:
    'REPORT_CARD_SCHOLASTIC_SETUP_PASSING_GRADE_CLICKED_TFI',
  REPORT_CARD_SCHOLASTIC_SUBJECT_MARKS_SET_SAME_CLICKED_TFI:
    'REPORT_CARD_SCHOLASTIC_SUBJECT_MARKS_SET_SAME_CLICKED_TFI',
  REPORT_CARD_ADD_NEW_EXAM_CLICKED_TFI: 'REPORT_CARD_ADD_NEW_EXAM_CLICKED_TFI',
  REPORT_CARD_ADD_NEW_TERM_CLICKED_TFI: 'REPORT_CARD_ADD_NEW_TERM_CLICKED_TFI',
  REPORT_CARD_DUPLICATE_TERM_CLICKED_TFI:
    'REPORT_CARD_DUPLICATE_TERM_CLICKED_TFI',
  REPORT_CARD_CO_SCHOLASTIC_ACTIVITIES_ACTION_CLICKED_TFI:
    'REPORT_CARD_CO_SCHOLASTIC_ACTIVITIES_ACTION_CLICKED_TFI',
  REPORT_CARD_SHOW_IN_REPORTCARD_CLICKED_TFI:
    'REPORT_CARD_SHOW_IN_REPORTCARD_CLICKED_TFI',
  REPORT_CARD_ORDER_CHANGE_CLICKED_TFI: 'REPORT_CARD_ORDER_CHANGE_CLICKED_TFI',
  REPORT_CARD_SAVE_DRAFT_CLICKED_TFI: 'REPORT_CARD_SAVE_DRAFT_CLICKED_TFI',
  REPORT_CARD_PUBLISH_CLICKED_TFI: 'REPORT_CARD_PUBLISH_CLICKED_TFI',
  REPORT_CARD_CREATE_STRUCTURE_CLICKED_TFI:
    'REPORT_CARD_CREATE_STRUCTURE_CLICKED_TFI',
  REPORT_CARD_TAB_CLICKED_TFI: 'REPORT_CARD_TAB_CLICKED_TFI',
  REPORT_CARD_TEMPLATE_PREVIEW_ZOOM_CLICKED_TFI:
    'REPORT_CARD_TEMPLATE_PREVIEW_ZOOM_CLICKED_TFI',
  REPORT_CARD_PREVIEW_CLICKED_TFI: 'REPORT_CARD_PREVIEW_CLICKED_TFI',
  REPORT_CARD_EDIT_CLICKED_TFI: 'REPORT_CARD_EDIT_CLICKED_TFI',
  REPORT_CARD_CONTINUE_DRAFT_CLICKED_TFI:
    'REPORT_CARD_CONTINUE_DRAFT_CLICKED_TFI',

  // Ad hoc discount
  STANDARD_DISCOUNT_VIEW_CLICKED_TFI: 'STANDARD_DISCOUNT_VIEW_CLICKED_TFI',
  AD_HOC_DISCOUNT_VIEW_CLICKED_TFI: 'AD_HOC_DISCOUNT_VIEW_CLICKED_TFI',
  AD_HOC_DISCOUNT_CLICKED_TFI: 'AD_HOC_DISCOUNT_CLICKED_TFI',
  EDIT_AD_HOC_DISCOUNT_CLICKED_TFI: 'EDIT_AD_HOC_DISCOUNT_CLICKED_TFI',
  ADD_ADHOC_DISCOUNT_CLICKED_TFI: 'ADD_ADHOC_DISCOUNT_CLICKED_TFI',
  UPDATE_ADD_HOC_DISCOUNT_CLICKED_TFI: 'UPDATE_ADD_HOC_DISCOUNT_CLICKED_TFI',
  ADHOC_DISCOUNT_ADDED_TFI: 'ADHOC_DISCOUNT_ADDED_TFI',
  FEE_SETTINGS_CLICKED_TFI: 'FEE_SETTINGS_CLICKED_TFI',
  FEE_HEAD_SETTING_CLICKED_TFI: 'FEE_HEAD_SETTING_CLICKED_TFI',
  FEE_SUB_HEAD_SETTING_CLICKED_TFI: 'FEE_SUB_HEAD_SETTING_CLICKED_TFI',
  FEE_TOGGLE_SETTING_CLICKED_TFI: 'FEE_TOGGLE_SETTING_CLICKED_TFI',
  AD_HOC_DISCOUNT_UPDATED_TFI: 'AD_HOC_DISCOUNT_UPDATED_TFI',
  CHEQUE_DD_CLICKED_TFI: 'CHEQUE_DD_CLICKED_TFI',
  CHEQUE_DD_VIEW_TXN_TIMELINE_CLICKED_TFI:
    'CHEQUE_DD_VIEW_TXN_TIMELINE_CLICKED_TFI',
  CHEQUE_DD_TXN_STATUS_UPDATED_TFI: 'CHEQUE_DD_TXN_STATUS_UPDATED_TFI',
  CHEQUE_DD_UPDATE_TXN_STATUS_CLICKED_TFI:
    'CHEQUE_DD_UPDATE_TXN_STATUS_CLICKED_TFI',
  CHEQUE_DD_DOWNLOAD_RECEIPT_CLICKED_TFI:
    'CHEQUE_DD_DOWNLOAD_RECEIPT_CLICKED_TFI',
  CHEQUE_DD_DOWNLOAD_CANCELLED_RECEIPT_CLICKED_TFI:
    'CHEQUE_DD_DOWNLOAD_CANCELLED_RECEIPT_CLICKED_TFI',
  CHEQUE_DD_CANCEL_TRANSACTION_CLICKED_TFI:
    'CHEQUE_DD_CANCEL_TRANSACTION_CLICKED_TFI',
  CHEQUE_DD_CANCEL_TRANSACTION_POP_CLICKED_TFI:
    'CHEQUE_DD_CANCEL_TRANSACTION_POP_CLICKED_TFI',
  CHEQUE_DD_DELETE_RECEIPT_POPUP_CLICKED_TFI:
    'CHEQUE_DD_DELETE_RECEIPT_POPUP_CLICKED_TFI',
  CHEQUE_DD_DELETE_RECEIPT_CLICKED_TFI: 'CHEQUE_DD_DELETE_RECEIPT_CLICKED_TFI',
  CHEQUE_DD_TRANSACTION_CANCELLED_TFI: 'CHEQUE_DD_TRANSACTION_CANCELLED_TFI',
  CHEQUE_DD_RECEIPT_DELETED_TFI: 'CHEQUE_DD_RECEIPT_DELETED_TFI',
  // Fee Fine
  FEE_FINE_COLLECTION_CLICKED_TFI: 'FEE_FINE_COLLECTION_CLICKED_TFI',
  FINE_RULES_SAVE_BUTTON_CLICKED_TFI: 'FINE_RULES_SAVE_BUTTON_CLICKED_TFI',
  FINE_RULES_SAVED_TFI: 'FINE_RULES_SAVED_TFI',
  FINE_RULES_DELETE_BUTTON_CLICKED_TFI: 'FINE_RULES_DELETE_BUTTON_CLICKED_TFI',
  FINE_RULES_DELETE_BUTTON_POP_UP_CLICKED_TFI:
    'FINE_RULES_DELETE_BUTTON_POP_UP_CLICKED_TFI',
  FINE_RULES_DELETED_TFI: 'FINE_RULES_DELETED_TFI ',

  //Inventory Events
  INVENTORY_MANAGEMENT_TAB_CLICKED_TFI: 'INVENTORY_MANAGEMENT_TAB_CLICKED_TFI',
  IM_INVENTORY_OVERVIEW_TAB_CLICKED: 'IM_INVENTORY_OVERVIEW_TAB_CLICKED',
  IM_GET_STARTED_CLICKED_TFI: 'IM_GET_STARTED_CLICKED_TFI',
  IM_ADD_MORE_ITEMS_CLICKED_TFI: 'IM_ADD_MORE_ITEMS_CLICKED_TFI',
  IM_ADD_NEW_CATEGORY_CLICKED_TFI: 'IM_ADD_NEW_CATEGORY_CLICKED_TFI',
  'IM_CATEGORY_&_ITEMS_ADDED_TFI': 'IM_CATEGORY_&_ITEMS_ADDED_TFI',
  IM_CATEGORY_OVERVIEW_SUBTAB_CLICKED_TFI:
    'IM_CATEGORY_OVERVIEW_SUBTAB_CLICKED_TFI',
  IM_CATEGORY_DROPDOWN_CLICKED_TFI: 'IM_CATEGORY_DROPDOWN_CLICKED_TFI',
  IM_ALLOCATE_ITEM_CLICKED_TFI: 'IM_ALLOCATE_ITEM_CLICKED_TFI',
  IM_ITEM_ALLOCATED_TFI: 'IM_ITEM_ALLOCATED_TFI',
  IM_ITEM_OVERVIEW_SUBTAB_CLICKED_TFI: 'IM_ITEM_OVERVIEW_SUBTAB_CLICKED_TFI',
  IM_TOP_FILTER_CLICKED_TFI: 'IM_TOP_FILTER_CLICKED_TFI',
  IM_FILTER_TYPE_CLICKED_TFI: 'IM_FILTER_TYPE_CLICKED_TFI',
  IM_BULK_ALLOCATE_CLICKED_TFI: 'IM_BULK_ALLOCATE_CLICKED_TFI',
  IM_REALLOCATE_UNIT_CLICKED_TFI: 'IM_REALLOCATE_UNIT_CLICKED_TFI',
  IM_REMOVE_ALLOCATION_CLICKED_TFI: 'IM_REMOVE_ALLOCATION_CLICKED_TFI',
  IM_ITEM_STORE_TAB_CLICKED_TFI: 'IM_ITEM_STORE_TAB_CLICKED_TFI',
  IM_ADD_STORE_CLICKED_TFI: 'IM_ADD_STORE_CLICKED_TFI',
  IM_NEW_STORE_ADDED_TFI: 'IM_NEW_STORE_ADDED_TFI',
  IM_EDIT_STORE_CLICKED_TFI: 'IM_EDIT_STORE_CLICKED_TFI',
  IM_STORE_DETAILS_EDITED_TFI: 'IM_STORE_DETAILS_EDITED_TFI',
  IM_VIEW_ITEM_LIST_TFI: 'IM_VIEW_ITEM_LIST_TFI',
  IM_PURCHASE_ORDER_TAB_CLICKED_TFI: 'IM_PURCHASE_ORDER_TAB_CLICKED_TFI',
  IM_ADD_NEW_PO_TFI: 'IM_ADD_NEW_PO_TFI',
  IM_PO_TIMELINE_FILTER_CLICKED_TFI: 'IM_PO_TIMELINE_FILTER_CLICKED_TFI',
  IM_VIEW_PO_DETAIL_CLICKED_TFI: 'IM_VIEW_PO_DETAIL_CLICKED_TFI',
  IM_EDIT_PO_DETAIL_CLICKED_TFI: 'IM_EDIT_PO_DETAIL_CLICKED_TFI',
  IM_PO_EDITED_TFI: 'IM_PO_EDITED_TFI',
  IM_DELETE_INVOICE_CLICKED_TFI: 'IM_DELETE_INVOICE_CLICKED_TFI',
  IM_ITEM_CATEGORY_TAB_SELECTED_TFI: 'IM_ITEM_CATEGORY_TAB_SELECTED_TFI',
  IM_EDIT_CATEGORY_TAB_CLICKED_TFI: 'IM_EDIT_CATEGORY_TAB_CLICKED_TFI',
  IM_CATEGORY_EDITED_TFI: 'IM_CATEGORY_EDITED_TFI',
  IM_DELETE_CATEGORY_TAB_CLICKED_TFI: 'IM_DELETE_CATEGORY_TAB_CLICKED_TFI',
  IM_CATEGORY_DELETED_TFI: 'IM_CATEGORY_DELETED_TFI',
  IM_DELETE_ITEM_CLICKED_TFI: 'IM_DELETE_ITEM_CLICKED_TFI',
  IM_ITEM_DELETE_CONFIRMED_TFI: 'IM_ITEM_DELETE_CONFIRMED_TFI',
  //Hostel Events
  ADD_NEW_HOSTEL_CLICKED_TFI: 'ADD_NEW_HOSTEL_CLICKED_TFI',
  ADD_HOSTEL_CLICKED_TFI: 'ADD_HOSTEL_CLICKED_TFI',
  HOSTEL_CREATED_TFI: 'HOSTEL_CREATED_TFI',
  MANAGE_HOSTEL_CLICKED_TFI: 'MANAGE_HOSTEL_CLICKED_TFI',
  ADD_NEW_ROOM_CLICKED_TFI: 'ADD_NEW_ROOM_CLICKED_TFI',
  ADD_ROOM_CLICKED_TFI: 'ADD_ROOM_CLICKED_TFI',
  DELETE_ROOM_CLICKED_TFI: 'DELETE_ROOM_CLICKED_TFI',
  ROOM_DELETED_TFI: 'ROOM_DELETED_TFI',
  ASSIGN_ROOM_CLICKED_TFI: 'ASSIGN_ROOM_CLICKED_TFI',
  REMOVE_CLICKED_TFI: 'REMOVE_CLICKED_TFI',
  ROOM_ASSIGNED_TFI: 'ROOM_ASSIGNED_TFI',
  STUDENT_REMOVED_TFI: 'STUDENT_REMOVED_TFI',
  DELETE_ROOM_POPUP_CLICKED_TFI: 'DELETE_ROOM_POPUP_CLICKED_TFI',
  REMOVE_STUDENT_CLICKED_TFI: 'REMOVE_STUDENT_CLICKED_TFI',
  DELETE_HOSTEL_CLICKED_TFI: 'DELETE_HOSTEL_CLICKED_TFI',
  DELETE_HOSTEL_POPUP_CLICKED_TFI: 'DELETE_HOSTEL_POPUP_CLICKED_TFI',
  HOSTEL_DELETED_TFI: 'HOSTEL_DELETED_TFI',
  //Library Events
  ADD_BOOK_CLICKED_TFI: 'ADD_BOOK_CLICKED_TFI',
  BOOK_ADDED_TFI: 'BOOK_ADDED_TFI',
  ASSIGN_BOOK_CLICKED_TFI: 'ASSIGN_BOOK_CLICKED_TFI',
  BOOK_ASSIGNED_TFI: 'BOOK_ASSIGNED_TFI',
  RETURN_BOOK_CLICKED_TFI: 'RETURN_BOOK_CLICKED_TFI',
  BOOK_STATUS_UPDATED_TFI: 'BOOK_STATUS_UPDATED_TFI',
  BOOK_REMOVED_TFI: 'BOOK_REMOVED_TFI',
  REMOVE_BOOK_POPUP_CLICKED_TFI: 'REMOVE_BOOK_POPUP_CLICKED_TFI',
  //Transport Events
  PICKUP_POINTS_CLICKED_TFI: 'PICKUP_POINTS_CLICKED_TFI',
  VEHICLES_TAB_CLICKED_TFI: 'VEHICLES_TAB_CLICKED_TFI',
  STAFF_CLICKED_TFI: 'STAFF_CLICKED_TFI',
  VEHICLES_CLICKED_TFI: 'VEHICLES_CLICKED_TFI',
  ADD_VEHICLE_POPUP_CLICKED_TFI: 'ADD_VEHICLE_POPUP_CLICKED_TFI',
  ROUTES_CLICKED_TFI: 'ROUTES_CLICKED_TFI',
  ROUTES_TAB_CLICKED_TFI: 'ROUTES_TAB_CLICKED_TFI',
  ADD_PICKUP_POINT_CLICKED_TFI: 'ADD_PICKUP_POINT_CLICKED_TFI',
  ADD_PICKEUP_POINT_TFI: 'ADD_PICKEUP_POINT_TFI',
  PICKUP_POINT_ADDED_TFI: 'PICKUP_POINT_ADDED_TFI',
  DELETE_PICKUP_POINT_CLICKED_TFI: 'DELETE_PICKUP_POINT_CLICKED_TFI',
  PICKUP_POINT_DELETED_TFI: 'PICKUP_POINT_DELETED_TFI',
  MANAGE_STUDENTS_CLICKED_TFI: 'MANAGE_STUDENTS_CLICKED_TFI',
  UPDATE_TRANSPORT_STUDENT_CLICKED_TFI: 'UPDATE_TRANSPORT_STUDENT_CLICKED_TFI',
  ADD_VEHICLE_CLICKED_TFI: 'ADD_VEHICLE_CLICKED_TFI',
  VEHICLE_ADD_CLICKED_TFI: 'VEHICLE_ADD_CLICKED_TFI',
  VEHICLE_ADDED_TFI: 'VEHICLE_ADDED_TFI',
  DELETE_VEHICLE_CLICKED_TFI: 'DELETE_VEHICLE_CLICKED_TFI',
  VEHICLE_DELETED_TFI: 'VEHICLE_DELETED_TFI',
  ADD_STAFF_CLICKED_TFI: 'ADD_STAFF_CLICKED_TFI',
  STAFF_ADDED_TFI: 'STAFF_ADDED_TFI',
  DELETE_STAFF_CLICKED_TFI: 'DELETE_STAFF_CLICKED_TFI',
  STAFF_DELETED_TFI: 'STAFF_DELETED_TFI',
  ADD_ROUTE_CLICKED_TFI: 'ADD_ROUTE_CLICKED_TFI',
  ROUTE_ADD_TFI: 'ROUTE_ADD_TFI',
  ROUTE_ADDED_TFI: 'ROUTE_ADDED_TFI',
  DELETE_ROUTE_CLICKED_TFI: 'DELETE_ROUTE_CLICKED_TFI',
  ROUTE_DELETED_TFI: 'ROUTE_DELETED_TFI',
  ADD_REMOVE_CLICKED_TFI: 'ADD_REMOVE_CLICKED_TFI',
  WAY_POINT_ADDED_TFI: 'WAY_POINT_ADDED_TFI',
  DELETE_PICKUP_POINT_POPUP_CLICKED_TFI:
    'DELETE_PICKUP_POINT_POPUP_CLICKED_TFI',
  DELETE_VEHICLE_POPUP_CLICKED_TFI: 'DELETE_VEHICLE_POPUP_CLICKED_TFI',
  DELETE_STAFF_POPUP_CLICKED_TFI: 'DELETE_STAFF_POPUP_CLICKED_TFI',
  DELETE_ROUTE_POPUP_CLICKED_TFI: 'DELETE_ROUTE_POPUP_CLICKED_TFI',
  TRANSPORT_OVERVIEW_TAB_CLICKED_TFI: 'TRANSPORT_OVERVIEW_TAB_CLICKED_TFI',
  STOPS_TAB_CLICKED_TFI: 'STOPS_TAB_CLICKED_TFI',
  TRANSPORT_STAFF_TAB_CLICKED_TFI: 'TRANSPORT_STAFF_TAB_CLICKED_TFI',
  SCHOOL_ADDRESS_ADDED_TFI: 'SCHOOL_ADDRESS_ADDED_TFI',
  ADD_ANOTHER_VEHICLE_CLICKED_TFI: 'ADD_ANOTHER_VEHICLE_CLICKED_TFI',
  REQUEST_GPS_CLICKED_TFI: 'REQUEST_GPS_CLICKED_TFI',
  MANAGE_PASSENGERS_CLICKED_TFI: 'MANAGE_PASSENGERS_CLICKED_TFI',
  VIEW_PICKUP_AND_DROP_SCHEDULE_TFI: 'VIEW_PICKUP_AND_DROP_SCHEDULE_TFI',
  SETUP_SCHOOL_ADDRESS_CLICKED_TFI: 'SETUP_SCHOOL_ADDRESS_CLICKED_TFI',
  ADD_STOPS_CLICKED_TFI: 'ADD_STOPS_CLICKED_TFI',
  STOPS_KMENU_OPTIONS_CLICKED_TFI: 'STOPS_KMENU_OPTIONS_CLICKED_TFI',
  STOP_EDITED_TFI: 'STOP_EDITED_TFI',
  STOP_DELETED_TFI: 'STOP_DELETED_TFI',
  ADD_LOCATION_NEXT_CLICKED_TFI: 'ADD_LOCATION_NEXT_CLICKED_TFI',
  ADD_PASSENGERS_POPUP_CLICKED_TFI: 'ADD_PASSENGERS_POPUP_CLICKED_TFI',
  VEHICLE_DETAILS_EDITED_TFI: 'VEHICLE_DETAILS_EDITED_TFI',
  VEHICLE_KMENU_OPTIONS_CLICKED_TFI: 'VEHICLE_KMENU_OPTIONS_CLICKED_TFI',
  ADD_TRANSPORT_STAFF_CLICKED_TFI: 'ADD_TRANSPORT_STAFF_CLICKED_TFI',
  TRANSPORT_STAFF_KMENU_OPTIONS_CLICKED_TFI:
    'TRANSPORT_STAFF_KMENU_OPTIONS_CLICKED_TFI',
  TRANSPORT_STAFF_DELETED_TFI: 'TRANSPORT_STAFF_DELETED_TFI',
  ADD_ANOTHER_STAFF_CLICKED_TFI: 'ADD_ANOTHER_STAFF_CLICKED_TFI',
  TRANSPORT_STAFF_ADDED_TFI: 'TRANSPORT_STAFF_ADDED_TFI',
  TRANSPORT_STAFF_EDITED_TFI: 'TRANSPORT_STAFF_EDITED_TFI',
  ADD_ROUTE_STOP_CLICKED_TFI: 'ADD_ROUTE_STOP_CLICKED_TFI',
  ROUTE_EDITED_TFI: 'ROUTE_EDITED_TFI',
  ROUTE_KMENU_OPTIONS_CLICKED_TFI: 'ROUTE_KMENU_OPTIONS_CLICKED_TFI',
  TRANSPORT_CLICKED_TFI: 'TRANSPORT_CLICKED_TFI',
  DOWNLOAD_PASSENGERS_CLICKED_TFI: 'DOWNLOAD_PASSENGERS_CLICKED_TFI',
  ADD_TRANSPORT_STAFF_POPUP_CLICKED_TFI:
    'ADD_TRANSPORT_STAFF_POPUP_CLICKED_TFI',
  ADD_ROUTE_POPUP_CLICKED_TFI: 'ADD_ROUTE_POPUP_CLICKED_TFI',
  GPS_REQUEST_POPUP_CLICKED_TFI: 'GPS_REQUEST_POPUP_CLICKED_TFI',
  GPS_REQUESTED_TFI: 'GPS_REQUESTED_TFI',
  TRANSPORT_BULKUPLOAD_INITIATED_TFI: 'TRANSPORT_BULKUPLOAD_INITIATED_TFI',
  TRANSPORT_BULKUPLOAD_CLICKED_TFI: 'TRANSPORT_BULKUPLOAD_CLICKED_TFI',
  TRANSPORT_BULKUPLOAD_POPUP_CLICKED_TFI:
    'TRANSPORT_BULKUPLOAD_POPUP_CLICKED_TFI',
  TRANSPORT_SETUP_GUIDE_CLICKED_TFI: 'TRANSPORT_SETUP_GUIDE_CLICKED_TFI',
  ASSIGN_STOP_CLICKED_TFI: 'ASSIGN_STOP_CLICKED_TFI',
  ASSIGN_ROUTE_CLICKED_TFI: 'ASSIGN_ROUTE_CLICKED_TFI',
  ASSIGN_TRANSPORT_CONFIRM_CLICKED_TFI: 'ASSIGN_TRANSPORT_CONFIRM_CLICKED_TFI',

  //Calendar Events
  CALENDAR_WEEKLY_OFF_CLICKED_TFI: 'CALENDAR_WEEKLY_OFF_CLICKED_TFI',
  CALENDAR_HOLIDAY_CLICKED_TFI: 'CALENDAR_HOLIDAY_CLICKED_TFI',
  CALENDAR_EVENT_AND_ACTIVITY_CLICKED_TFI:
    'CALENDAR_EVENT_AND_ACTIVITY_CLICKED_TFI',
  EXAM_PLANNER_CALENDAR_CLICKED_TFI: 'EXAM_PLANNER_CALENDAR_CLICKED_TFI',
  CREATE_WEEKLY_OFF_CLICKED_TFI: 'CREATE_WEEKLY_OFF_CLICKED_TFI',
  WEEKLY_OFF_SAVE_CLICKED_TFI: 'WEEKLY_OFF_SAVE_CLICKED_TFI',
  DELETE_WEEKLY_OFF_CLICKED_TFI: 'DELETE_WEEKLY_OFF_CLICKED_TFI',
  DELETE_WEEKLY_OFF_POPUP_CLICKED_TFI: 'DELETE_WEEKLY_OFF_POPUP_CLICKED_TFI',
  WEEKLY_OFF_DELETED_TFI: 'WEEKLY_OFF_DELETED_TFI',
  EDIT_WEEKLY_OFF_CLICKED_TFI: 'EDIT_WEEKLY_OFF_CLICKED_TFI',
  CREATE_HOLIDAY_CLICKED_TFI: 'CREATE_HOLIDAY_CLICKED_TFI',
  HOLIDAY_SAVE_CLICKED_TFI: 'HOLIDAY_SAVE_CLICKED_TFI',
  DELETE_HOLIDAY_CLICKED_TFI: 'DELETE_HOLIDAY_CLICKED_TFI',
  DELETE_HOLIDAY_POPUP_CLICKED_TFI: 'DELETE_HOLIDAY_POPUP_CLICKED_TFI',
  HOLIDAY_CALENDAR_DELETED_TFI: 'HOLIDAY_CALENDAR_DELETED_TFI',
  EDIT_HOLIDAY_CLICKED_TFI: 'EDIT_HOLIDAY_CLICKED_TFI',
  CREATE_EVENT_AND_ACTIVITY_CLICKED_TFI:
    'CREATE_EVENT_AND_ACTIVITY_CLICKED_TFI',
  EVENT_AND_ACTIVITY_SAVE_CLICKED_TFI: 'EVENT_AND_ACTIVITY_SAVE_CLICKED_TFI',
  DELETE_EVENT_AND_ACTIVITY_CLICKED_TFI:
    'DELETE_EVENT_AND_ACTIVITY_CLICKED_TFI',
  DELETE_EVENT_AND_ACTIVITY_POPUP_CLICKED_TFI:
    'DELETE_EVENT_AND_ACTIVITY_POPUP_CLICKED_TFI',
  EVENT_AND_ACTIVITY_DELETED_TFI: 'EVENT_AND_ACTIVITY_DELETED_TFI',
  EDIT_EVENT_AND_ACTIVITY_CLICKED_TFI: 'EDIT_EVENT_AND_ACTIVITY_CLICKED_TFI',
  REGISTER_FOR_PRODUCT_TRAINING: 'REGISTER_FOR_PRODUCT_TRAINING',
  NUDGE_DONT_SHOW_ME_AGAIN_SELECTED_TFI:
    'NUDGE_DONT_SHOW_ME_AGAIN_SELECTED_TFI',
  NUDGE_CANCEL_CLICKED_TFI: 'NUDGE_CANCEL_CLICKED_TFI',
  NUDGE_LET_TEACHERS_KNOW_CLICKED_TFI: 'NUDGE_LET_TEACHERS_KNOW_CLICKED_TFI',
  FINE_CREATE_NEW_RULE_CLICKED_TFI: 'FINE_CREATE_NEW_RULE_CLICKED_TFI',
  FEE_ATTEND_WEBINAR_CLICK_TFI: 'FEE_ATTEND_WEBINAR_CLICK_TFI',
  FEE_WEBINAR_FEEDBACK_CLICK_TFI: 'FEE_WEBINAR_FEEDBACK_CLICK_TFI',
  FEE_SEND_REMINDER_CLICKED_TFI: 'FEE_SEND_REMINDER_CLICKED_TFI',
  FEE_REMINDER_SENT_TFI: 'FEE_REMINDER_SENT_TFI',
  //Communication events
  COMM_POST_MANAGE_CLICKED: 'COMM_POST_MANAGE_CLICKED',
  COMM_POST_SHARE_CLICKED: 'COMM_POST_SHARE_CLICKED',
  COMM_POST_EDIT_CLICKED: 'COMM_POST_EDIT_CLICKED',
  COMM_POST_REMOVE_CLICKED: 'COMM_POST_REMOVE_CLICKED',
  COMM_POST_REMOVE_CONFIRMED: 'COMM_POST_REMOVE_CONFIRMED',
  POST_SEND_REMINDER_ALL_RECEPIENTS: 'POST_SEND_REMINDER_ALL_RECEPIENTS',
  POST_SEND_REMINDER_PENDING_RECEPIENTS:
    'POST_SEND_REMINDER_PENDING_RECEPIENTS',
  POST_SEND_REMINDER_INITIATED: 'POST_SEND_REMINDER_INITIATED',
  FEE_COLLECTION_HELP_VIDEO_TFI: 'FEE_COLLECTION_HELP_VIDEO_TFI',
  STUDENT_ATTENDANCE_DETAILED_REPORTS: 'STUDENT_ATTENDANCE_DETAILED_REPORTS',
  PAYMENT_CONFIRMATION_RECEIPT_TFI: 'PAYMENT_CONFIRMATION_RECEIPT_TFI',
  GO_TO_TRANSACTION_CLICKED_TFI: 'GO_TO_TRANSACTION_CLICKED_TFI',
  COMMS_QUICK_ACTION_TEMPLATE_CLICKED: 'COMMS_QUICK_ACTION_TEMPLATE_CLICKED',
  VOICE_NOTE_RECORDING_STARTED_TFI: 'VOICE_NOTE_RECORDING_STARTED_TFI',
  VOICE_NOTE_RECORDING_PAUSE_TFI: 'VOICE_NOTE_RECORDING_PAUSE_TFI',
  VOICE_NOTE_RECORDING_PLAYED_TFI: 'VOICE_NOTE_RECORDING_PLAYED_TFI',
  VOICE_NOTE_PLAYING_PAUSED_TFI: 'VOICE_NOTE_PLAYING_PAUSED_TFI',
  VOICE_NOTE_RECORDING_RESTARTED_TFI: 'VOICE_NOTE_RECORDING_RESTARTED_TFI',
  VOICE_NOTE_RECORDING_DELETED_TFI: 'VOICE_NOTE_RECORDING_DELETED_TFI',

  // SIS Profile Setup Start
  PROFILE_SETTINGS_CLICKED_TFI: 'PROFILE_SETTINGS_CLICKED_TFI',
  STUDENT_PROFILE_SETTING_CLICKED_TFI: 'STUDENT_PROFILE_SETTING_CLICKED_TFI',
  STAFF_PROFILE_SETTING_CLICKED_TFI: 'STAFF_PROFILE_SETTING_CLICKED_TFI',

  ADD_NEW_PROFILE_SECTION_CLICKED_TFI: 'ADD_NEW_PROFILE_SECTION_CLICKED_TFI',
  SAVE_NEW_PROFILE_SECTION_CLICKED_TFI: 'SAVE_NEW_PROFILE_SECTION_CLICKED_TFI',
  NEW_PROFILE_SECTION_SAVED_TFI: 'NEW_PROFILE_SECTION_SAVED_TFI',

  PREVIEW_PROFILE_SECTION_CLICKED_TFI: 'PREVIEW_PROFILE_SECTION_CLICKED_TFI',
  PROFILE_SECTION_NODE_CLICKED_TFI: 'PROFILE_SECTION_NODE_CLICKED_TFI',
  ADD_NEW_PROFILE_FIELD_CLICKED_TFI: 'ADD_NEW_PROFILE_FIELD_CLICKED_TFI',
  SAVE_NEW_PROFILE_FIELD_CLICKED_TFI: 'SAVE_NEW_PROFILE_FIELD_CLICKED_TFI',
  NEW_PROFILE_FIELD_SAVED_TFI: 'NEW_PROFILE_FIELD_SAVED_TFI',
  EDIT_PROFILE_FIELD_CLICKED_TFI: 'EDIT_PROFILE_FIELD_CLICKED_TFI',
  PROFILE_FIELD_UPDATE_CLICKED_TFI: 'PROFILE_FIELD_UPDATE_CLICKED_TFI',
  PROFILE_FIELD_EDITED_TFI: 'PROFILE_FIELD_EDITED_TFI',
  PROFILE_SECTION_EXIT_WITHOUT_ADDING_CLICKED_TFI:
    'PROFILE_SECTION_EXIT_WITHOUT_ADDING_CLICKED_TFI',
  PROFILE_FIELD_EXIT_WITHOUT_ADDING_CLICKED_TFI:
    'PROFILE_FIELD_EXIT_WITHOUT_ADDING_CLICKED_TFI',
  PROFILE_FIELD_EXIT_WITHOUT_EDITING_CLICKED_TFI:
    'PROFILE_FIELD_EXIT_WITHOUT_EDITING_CLICKED_TFI',

  ADD_NEW_DOCUMENT_SECTION_CLICKED_TFI: 'ADD_NEW_DOCUMENT_SECTION_CLICKED_TFI',
  SAVE_NEW_DOCUMENTS_SECTION_CLICKED_TFI:
    'SAVE_NEW_DOCUMENTS_SECTION_CLICKED_TFI',
  NEW_DOCUMENTS_SECTION_SAVED_TFI: 'NEW_DOCUMENTS_SECTION_SAVED_TFI',
  PREVIEW_DOCUMENT_SECTION_CLICKED_TFI: 'PREVIEW_DOCUMENT_SECTION_CLICKED_TFI',
  PROFILE_DOCUMENT_NODE_CLICKED_TFI: 'PROFILE_DOCUMENT_NODE_CLICKED_TFI',
  PREVIEW_PROFILE_DOCUMENTS_CLICKED_TFI:
    'PREVIEW_PROFILE_DOCUMENTS_CLICKED_TFI',
  ADD_NEW_PROFILE_DOCUMENTS_CLICKED_TFI:
    'ADD_NEW_PROFILE_DOCUMENTS_CLICKED_TFI',
  SAVE_NEW_PROFILE_DOCUMENTS_CLICKED_TFI:
    'SAVE_NEW_PROFILE_DOCUMENTS_CLICKED_TFI',
  NEW_PROFILE_DOCUMENTS_SAVED_TFI: 'NEW_PROFILE_DOCUMENTS_SAVED_TFI',
  EDIT_PROFILE_DOCUMENTS_CLICKED_TFI: 'EDIT_PROFILE_DOCUMENTS_CLICKED_TFI',
  PROFILE_DOCUMENT_UPDATE_CLICKED_TFI: 'PROFILE_DOCUMENT_UPDATE_CLICKED_TFI',
  PROFILE_DOCUMENTS_EDITED_TFI: 'PROFILE_DOCUMENTS_EDITED_TFI',
  PROFILE_DOCUMENT_SECTION_EXIT_WITHOUT_ADDING_CLICKED_TFI:
    'PROFILE_DOCUMENT_SECTION_EXIT_WITHOUT_ADDING_CLICKED_TFI',
  PROFILE_DOCUMENT_EXIT_WITHOUT_ADDING_CLICKED_TFI:
    'PROFILE_DOCUMENT_EXIT_WITHOUT_ADDING_CLICKED_TFI',
  PROFILE_DOCUMENT_EXIT_WITHOUT_EDITING_CLICKED_TFI:
    'PROFILE_DOCUMENT_EXIT_WITHOUT_EDITING_CLICKED_TFI',

  // SIS Profile Setup End

  // Profile Documents start
  PROFILE_DETAILS_TAB_CLICKED_TFI: 'PROFILE_DETAILS_TAB_CLICKED_TFI',
  PROFILE_DETAILS_DOCUMENTS_TAB_CLICKED_TFI:
    'PROFILE_DETAILS_DOCUMENTS_TAB_CLICKED_TFI',
  PROFILE_DETAILS_FEE_TAB_CLICKED_TFI: 'PROFILE_DETAILS_FEE_TAB_CLICKED_TFI',
  PROFILE_DOCUMENT_UPLOAD_NODE_CLICKED_TFI:
    'PROFILE_DOCUMENT_UPLOAD_NODE_CLICKED_TFI',
  PROFILE_DOCUMENT_UPLOADED_TFI: 'PROFILE_DOCUMENT_UPLOADED_TFI',
  PROFILE_DOCUMENT_UPLOAD_CLICKED_TFI: 'PROFILE_DOCUMENT_UPLOAD_CLICKED_TFI',
  PROFILE_DOCUMENT_PREVIEW_CLICKED_TFI: 'PROFILE_DOCUMENT_PREVIEW_CLICKED_TFI',
  PROFILE_DOCUMENT_DOWNLOAD_CLICKED_TFI:
    'PROFILE_DOCUMENT_DOWNLOAD_CLICKED_TFI',
  PROFILE_DOCUMENT_DOWNLOADED_TFI: 'PROFILE_DOCUMENT_DOWNLOADED_TFI',
  PROFILE_DOCUMENT_RE_UPLOAD_CLICKED_TFI:
    'PROFILE_DOCUMENT_RE_UPLOAD_CLICKED_TFI',
  PROFILE_DOCUMENT_REMOVE_CLICKED_TFI: 'PROFILE_DOCUMENT_REMOVE_CLICKED_TFI',

  // Profile Documents end

  COMM_READ_SPLIT_OPENED: 'COMM_READ_SPLIT_OPENED',
  COMM_READ_SPLIT_TAB_SWITCHED: 'COMM_READ_SPLIT_TAB_SWITCHED',
  COMM_READ_SPLIT_SEARCH_USED: 'COMM_READ_SPLIT_SEARCH_USED',
  COMM_READ_SPLIT_WHATSAPP_SHARE: 'COMM_READ_SPLIT_WHATSAPP_SHARE',
  NPS_MODAL_LAUNCHED_TFI: 'NPS_MODAL_LAUNCHED_TFI',
  NPS_INTRO_NEXT_CLICKED_TFI: 'NPS_INTRO_NEXT_CLICKED_TFI',
  NPS_INTRO_REMIND_CLICKED_TFI: 'NPS_INTRO_REMIND_CLICKED_TFI',
  NPS_EXIT_CLICKED_TFI: 'NPS_EXIT_CLICKED_TFI',
  NPS_BACK_CLICKED_TFI: 'NPS_BACK_CLICKED_TFI',
  NPS_MAIN_FEATURE_CLICKED_TFI: 'NPS_MAIN_FEATURE_CLICKED_TFI',
  NPS_MAIN_FEATURE_SELECTED_TFI: 'NPS_MAIN_FEATURE_SELECTED_TFI',
  NPS_SUBFEATURE_CLICKED_TFI: 'NPS_SUBFEATURE_CLICKED_TFI',
  NPS_TEXTBOX_USED_TFI: 'NPS_TEXTBOX_USED_TFI',
  NPS_FEATURE_SELECT_SUBMIT_CLICKED_TFI:
    'NPS_FEATURE_SELECT_SUBMIT_CLICKED_TFI',
  NPS_FINAL_SCREEN_DONE_CLICKED_TFI: 'NPS_FINAL_SCREEN_DONE_CLICKED_TFI',
  RECORD_BY_TYPE_TFI: 'RECORD_BY_TYPE_TFI',
  RECORD_BY_ADD_DISCOUNT_TFI: 'RECORD_BY_ADD_DISCOUNT_TFI',
  RECORD_BY_ADD_DUE_FINE_TFI: 'RECORD_BY_ADD_DUE_FINE_TFI',
  RECORD_BY_DELETE_DISCOUNT_TFI: 'RECORD_BY_DELETE_DISCOUNT_TFI',
  RECORD_BY_DELETE_DUE_FINE_TFI: 'RECORD_BY_DELETE_DUE_FINE_TFI',
  REPORTS_AND_ANALYTICS_CLICKED_TFI: 'REPORTS_AND_ANALYTICS_CLICKED_TFI',

  // Backdated payment collect
  FEE_COLLECT_BACKDATED_BUTTON_CLICKED_TFI:
    'FEE_COLLECT_BACKDATED_BUTTON_CLICKED_TFI',
  FEE_BACKDATED_DOWNLOAD_STUDENT_LIST_CLICKED_TFI:
    'FEE_BACKDATED_DOWNLOAD_STUDENT_LIST_CLICKED_TFI',
  FEE_BACKDATED_ADD_FILE_CLICKED_TFI: 'FEE_BACKDATED_ADD_FILE_CLICKED_TFI',
  FEE_BACKDATED_UPLOAD_CLICKED_TFI: 'FEE_BACKDATED_UPLOAD_CLICKED_TFI',
  FEE_BACKDATED_FILE_DELETED_TFI: 'FEE_BACKDATED_FILE_DELETED_TFI',
  FEE_BACKDATED_FILE_ERROR_TFI: 'FEE_BACKDATED_FILE_ERROR_TFI',
  FEE_BACKDATED_CLOSE_BUTTON_TFI: 'FEE_BACKDATED_CLOSE_BUTTON_TFI',
  FEE_BACKDATED_UPLOADED_TFI: 'FEE_BACKDATED_UPLOADED_TFI',
  COMM_USER_SEGMENT_CLICKED: 'COMM_USER_SEGMENT_CLICKED',
  FEE_SIDEBAR_CONFIGURATION_CLICKED_TFI:
    'FEE_SIDEBAR_CONFIGURATION_CLICKED_TFI',
  FEE_SIDEBAR_COLLECTION_CLICKED_TFI: 'FEE_SIDEBAR_COLLECTION_CLICKED_TFI',
  STUDENT_PROFILE_TAB_CLICKED_TFI: 'STUDENT_PROFILE_TAB_CLICKED_TFI',
  STUDENT_FEE_VIEW_UPDATE_HISTORY_CLICKED_TFI:
    'STUDENT_FEE_VIEW_UPDATE_HISTORY_CLICKED_TFI',
  STUDENT_FEE_VIEW_PAYMENT_HISTORY_CLICKED_TFI:
    'STUDENT_FEE_VIEW_PAYMENT_HISTORY_CLICKED_TFI',
  STUDENT_FEE_SHOW_DETAILS_CLICKED_TFI: 'STUDENT_FEE_SHOW_DETAILS_CLICKED_TFI',
  STUDENT_FEE_VIEW_RECEIPTS_CLICKED_TFI:
    'STUDENT_FEE_VIEW_RECEIPTS_CLICKED_TFI',
  REFUND_WALLET_BALANCE_CLICKED_TFI: 'REFUND_WALLET_BALANCE_CLICKED_TFI',
  MARK_AS_REFUNDED_CLICKED_TFI: 'MARK_AS_REFUNDED_CLICKED_TFI',
  ISSUE_REFUND_CANCEL_CLICKED_TFI: 'ISSUE_REFUND_CANCEL_CLICKED_TFI',
  STUDENT_FEE_VIEW_DISCOUNT_CLICKED_TFI:
    'STUDENT_FEE_VIEW_DISCOUNT_CLICKED_TFI',

  // setting  > classroom setting
  CLASSROOMS_SETTINGS_CLICKED_TFI: 'CLASSROOMS_SETTINGS_CLICKED_TFI',
  // setting  > roles and permission
  ROLES_AND_PERMISSION_CLICKED_TFI: 'ROLES_AND_PERMISSION_CLICKED_TFI',
  PREFERENCES_CLICKED_TFI: 'PREFERENCES_CLICKED_TFI',
  COMMS_SMS_TEMPLATE_SELECTED_TFI: 'COMMS_SMS_TEMPLATE_SELECTED_TFI',
  FEE_STUDENT_NAME_CLICKED_TFI: 'FEE_STUDENT_NAME_CLICKED_TFI',
  USER_TIME_SPENT_ON_A_ROUTE_TFI: 'USER_TIME_SPENT_ON_A_ROUTE_TFI',

  FEE_RECEIPT_SIGN_ADD_FILE_CLICKED_TFI:
    'FEE_RECEIPT_SIGN_ADD_FILE_CLICKED_TFI',
  FEE_RECEIPT_SIGN_SAVE_DETAILS_CLICKED_TFI:
    'FEE_RECEIPT_SIGN_SAVE_DETAILS_CLICKED_TFI',
  FEE_RECEIPT_SIGN_DELETE_CLICKED_TFI: 'FEE_RECEIPT_SIGN_DELETE_CLICKED_TFI',

  COMMS_SMS_RECHARGE_BALANCE_CLICKED_TFI:
    'COMMS_SMS_RECHARGE_BALANCE_CLICKED_TFI',
  COMMS_SMS_PAY_BUTTON_CLICKED_TFI: 'COMMS_SMS_PAY_BUTTON_CLICKED_TFI',
  COMMS_SMS_RECHARGE_BALANCE_CLOSED_TFI:
    'COMMS_SMS_RECHARGE_BALANCE_CLOSED_TFI',

  //AdmissionCrm Events
  ADMISSION_MANAGEMENT_CLICKED_TFI: 'ADMISSION_MANAGEMENT_CLICKED_TFI',
  ADMISSION_LEADLIST_CLICKED_TFI: 'ADMISSION_LEADLIST_CLICKED_TFI',
  ADMISSION_TRANSACTIONS_CLICKED_TFI: 'ADMISSION_TRANSACTIONS_CLICKED_TFI',
  ADMISSION_FOLLOWUPS_CLICKED_TFI: 'ADMISSION_FOLLOWUPS_CLICKED_TFI',
  ADMISSION_SETTINGS_CLICKED_TFI: 'ADMISSION_SETTINGS_CLICKED_TFI',

  LEAD_NODE_CLICKED_TFI: 'LEAD_NODE_CLICKED_TFI',
  LEAD_NODE_MOVED_TFI: 'LEAD_NODE_MOVED_TFI',
  LEAD_CONFIRM_ADMISSION_CLICKED_TFI: 'LEAD_CONFIRM_ADMISSION_CLICKED_TFI',
  LEAD_FOLLOW_UP_SAVE_CLICKED_TFI: 'LEAD_FOLLOW_UP_SAVE_CLICKED_TFI',

  ADMISSION_SETUP_INITIATED_TFI: 'ADMISSION_SETUP_INITIATED_TFI',

  ADMISSION_SESSION_SETUP_INITIATED_TFI:
    'ADMISSION_SESSION_SETUP_INITIATED_TFI',
  ADMISSION_LEADSTAGE_SETUP_INITIATED_TFI:
    'ADMISSION_LEADSTAGE_SETUP_INITIATED_TFI',
  ADMISSION_WEBPAGE_SETUP_INITIATED_TFI:
    'ADMISSION_WEBPAGE_SETUP_INITIATED_TFI',
  ADMISSION_ENQUIRYFORM_SETUP_INITIATED_TFI:
    'ADMISSION_ENQUIRYFORM_SETUP_INITIATED_TFI',
  ADMISSION_FORM_SETUP_INITIATED_TFI: 'ADMISSION_FORM_SETUP_INITIATED_TFI',
  ADMISSION_DOCUMENTS_SETUP_INITIATED_TFI:
    'ADMISSION_DOCUMENTS_SETUP_INITIATED_TFI',
  ADMISSION_FEES_SETUP_INITIATED_TFI: 'ADMISSION_FEES_SETUP_INITIATED_TFI',

  ADMISSION_SESSION_SETUP_COMPLETED_TFI:
    'ADMISSION_SESSION_SETUP_COMPLETED_TFI',
  ADMISSION_SESSION_SETUP_UPDATED_TFI: 'ADMISSION_SESSION_SETUP_UPDATED_TFI',
  ADMISSION_LEADSTAGE_SETUP_COMPLETED_TFI:
    'ADMISSION_LEADSTAGE_SETUP_COMPLETED_TFI',
  ADMISSION_LEADSTAGE_SETUP_UPDATED_TFI:
    'ADMISSION_LEADSTAGE_SETUP_UPDATED_TFI',
  ADMISSION_WEBPAGE_SETUP_COMPLETED_TFI:
    'ADMISSION_WEBPAGE_SETUP_COMPLETED_TFI',
  ADMISSION_WEBPAGE_SETUP_UPDATED_TFI: 'ADMISSION_WEBPAGE_SETUP_UPDATED_TFI',
  ADMISSION_ENQUIRYFORM_SETUP_COMPLETED_TFI:
    'ADMISSION_ENQUIRYFORM_SETUP_COMPLETED_TFI',
  ADMISSION_ENQUIRYFORM_SETUP_UPDATED_TFI:
    'ADMISSION_ENQUIRYFORM_SETUP_UPDATED_TFI',
  ADMISSION_FORM_SETUP_COMPLETED_TFI: 'ADMISSION_FORM_SETUP_COMPLETED_TFI',
  ADMISSION_FORM_SETUP_UPDAED_TFI: 'ADMISSION_FORM_SETUP_UPDATED_TFI',
  ADMISSION_DOCUMENTS_SETUP_COMPLETED_TFI:
    'ADMISSION_DOCUMENTS_SETUP_COMPLETED_TFI',
  ADMISSION_DOCUMENTS_SETUP_UPDATED_TFI:
    'ADMISSION_DOCUMENTS_SETUP_UPDATED_TFI',
  ADMISSION_FEES_SETUP_COMPLETED_TFI: 'ADMISSION_FEES_SETUP_COMPLETED_TFI',
  ADMISSION_FEES_SETUP_UPDATED_TFI: 'ADMISSION_FEES_SETUP_UPDATED_TFI',

  ADD_NEW_LEAD_ENQUIRY_DONE_CLICKED_TFI:
    'ADD_NEW_LEAD_ENQUIRY_DONE_CLICKED_TFI',

  NEW_LEAD_ADMISSION_FORM_NEXT_CLICKED_TFI:
    'NEW_LEAD_ADMISSION_FORM_NEXT_CLICKED_TFI',
  NEW_LEAD_ADMISSION_FORM_DOCUMENTS_NEXT_CLICKED_TFI:
    'NEW_LEAD_ADMISSION_FORM_DOCUMENTS_NEXT_CLICKED_TFI',
  NEW_LEAD_ADMISSION_FORM_RECORD_FORM_FEE_NEXT_CLICKED_TFI:
    'NEW_LEAD_ADMISSION_FORM_RECORD_FORM_FEE_NEXT_CLICKED_TFI',
  NEW_LEAD_ADMISSION_FORM_DONE_CLICKED_TFI:
    'NEW_LEAD_ADMISSION_FORM_DONE_CLICKED_TFI',

  LEAD_FOLLOW_UP_MARK_COMPLETE_CLICKED_TFI:
    'LEAD_FOLLOW_UP_MARK_COMPLETE_CLICKED_TFI',
  LEAD_FOLLOW_UP_RESCHEDULE_CLICKED_TFI:
    'LEAD_FOLLOW_UP_RESCHEDULE_CLICKED_TFI',

  FEE_RECEIPT_DOWNLOAD_CLICKED_TFI: 'FEE_RECEIPT_DOWNLOAD_CLICKED_TFI',
  FEE_TRANSACTION_STATUS_REFRESH_CLICKED_TFI:
    'FEE_TRANSACTION_STATUS_REFRESH_CLICKED_TFI',
  ADMISSION_TRANSACTION_FILTERS_CLICKED_TFI:
    'ADMISSION_TRANSACTION_FILTERS_CLICKED_TFI',
  ADMISSION_TRANSACTION_APPLY_FILTER_CLICKED_TFI:
    'ADMISSION_TRANSACTION_APPLY_FILTER_CLICKED_TFI',
  ADMISSION_PG_SETUP_INITIATED_TFI: 'ADMISSION_PG_SETUP_INITIATED_TFI',

  ADMISSION_LEAD_LIST_PROFILE_ALL_VIEW_CLICKED_TFI:
    'ADMISSION_LEAD_LIST_PROFILE_ALL_VIEW_CLICKED_TFI',
  ADMISSION_LEAD_LIST_PROFILE_STUDENT_VIEW_CLICKED_TFI:
    'ADMISSION_LEAD_LIST_PROFILE_STUDENT_VIEW_CLICKED_TFI',
  ADMISSION_LEAD_LIST_PROFILE_ADMIN_VIEW_CLICKED_TFI:
    'ADMISSION_LEAD_LIST_PROFILE_ADMIN_VIEW_CLICKED_TFI',

  ADMISSION_LEAD_PROFILE_CHANGE_STAGE_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_CHANGE_STAGE_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_CHANGE_CONFIRM_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_CHANGE_CONFIRM_CLICKED_TFI',

  ADMISSION_LEAD_PROFILE_ADMISSION_FORM_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_ADMISSION_FORM_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_FORM_FEE_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_FORM_FEE_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_ADMISSION_FEE_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_ADMISSION_FEE_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_FOLLOWUP_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_FOLLOWUP_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_SEND_SMS_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_SEND_SMS_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_TOTAL_FOLLOWUPS_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_TOTAL_FOLLOWUPS_CLICKED_TFI',
  ADMISSION_STUDENT_NAME_CLICKED_TFI: 'ADMISSION_STUDENT_NAME_CLICKED_TFI',

  ADMISSION_SESSION_EDIT_CLICKED_TFI: 'ADMISSION_SESSION_EDIT_CLICKED_TFI',
  ADMISSION_LEAD_STAGE_EDIT_CLICKED_TFI:
    'ADMISSION_LEAD_STAGE_EDIT_CLICKED_TFI',
  ADMISSION_WEB_PAGE_EDIT_CLICKED_TFI: 'ADMISSION_WEB_PAGE_EDIT_CLICKED_TFI',
  ADMISSION_ENQUIRY_FORM_EDIT_CLICKED_TFI:
    'ADMISSION_ENQUIRY_FORM_EDIT_CLICKED_TFI',
  ADMISSION_ADMISSION_FORM_EDIT_CLICKED_TFI:
    'ADMISSION_ADMISSION_FORM_EDIT_CLICKED_TFI',
  ADMISSION_DOCUMENTS_EDIT_CLICKED_TFI: 'ADMISSION_DOCUMENTS_EDIT_CLICKED_TFI',
  ADMISSION_FEE_EDIT_CLICKED_TFI: 'ADMISSION_FEE_EDIT_CLICKED_TFI',
  ADD_NEW_LEAD_CLICKED_TFI: 'ADD_NEW_LEAD_CLICKED_TFI',
  ADMISSION_LEAD_LIST_FILTER_CLICKED_TFI:
    'ADMISSION_LEAD_LIST_FILTER_CLICKED_TFI',
  ADMISSION_LEAD_APPLY_FILTER_CLICKED_TFI:
    'ADMISSION_LEAD_APPLY_FILTER_CLICKED_TFI',
  ADD_NEW_LEAD_ENQUIRY_FORM_CLICKED_TFI:
    'ADD_NEW_LEAD_ENQUIRY_FORM_CLICKED_TFI',
  ADD_NEW_LEAD_ADMISSION_FORM_CLICKED_TFI:
    'ADD_NEW_LEAD_ADMISSION_FORM_CLICKED_TFI',

  LEAD_FOLLOW_UP_ALL_VIEW_CLICKED_TFI: 'LEAD_FOLLOW_UP_ALL_VIEW_CLICKED_TFI',
  LEAD_FOLLOW_UP_MISSED_VIEW_CLICKED_TFI:
    'LEAD_FOLLOW_UP_MISSED_VIEW_CLICKED_TFI',
  LEAD_FOLLOW_UP_PLANNED_VIEW_CLICKED_TFI:
    'LEAD_FOLLOW_UP_PLANNED_VIEW_CLICKED_TFI',
  LEAD_FOLLOW_UP_COMPLETED_VIEW_CLICKED_TFI:
    'LEAD_FOLLOW_UP_COMPLETED_VIEW_CLICKED_TFI',
  ADMISSION_REPORT_DOWNLOAD_CLICKED_TFI:
    'ADMISSION_REPORT_DOWNLOAD_CLICKED_TFI',
  ADMISSION_FEE_SYNCNOW_CLICKED_TFI: 'ADMISSION_FEE_SYNCNOW_CLICKED_TFI',
  ADMISSION_FEE_SYNCED_TFI: 'ADMISSION_FEE_SYNCED_TFI',

  // Steppers Event of admission form
  NEW_LEAD_FILL_FORM_CLICKED_TFI: 'NEW_LEAD_FILL_FORM_CLICKED_TFI',
  NEW_LEAD_UPLOAD_DOCUMENTS_CLICKED_TFI:
    'NEW_LEAD_UPLOAD_DOCUMENTS_CLICKED_TFI',
  NEW_LEAD_RECORD_FORM_FEES_CLICKED_TFI:
    'NEW_LEAD_RECORD_FORM_FEES_CLICKED_TFI',
  NEW_LEAD_CHOOSE_STAGE_CLICKED_TFI: 'NEW_LEAD_CHOOSE_STAGE_CLICKED_TFI',

  LEAD_SMS_CLICKED_TFI: 'LEAD_SMS_CLICKED_TFI',
  LEAD_SMS_SEND_CLICKED_TFI: 'LEAD_SMS_SEND_CLICKED_TFI',

  ADMISSION_SORT_FILTER_CLICKED_TFI: 'ADMISSION_SORT_FILTER_CLICKED_TFI',
  ADMISSION_SORT_FILTER_SELECTED_TFI: 'ADMISSION_SORT_FILTER_SELECTED_TFI',
  ADMISSION_UPLOADED_DOCUMENT_PRINT_CLICKED_TFI:
    'ADMISSION_UPLOADED_DOCUMENT_PRINT_CLICKED_TFI',
  ADMISSION_UPLOADED_DOCUMENT_DOWNLOAD_CLICKED_TFI:
    'ADMISSION_UPLOADED_DOCUMENT_DOWNLOAD_CLICKED_TFI',

  ADMISSION_LEAD_PROFILE_VIEW_RECEIPT_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_VIEW_RECEIPT_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_VIEW_FORM_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_VIEW_FORM_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_VIEW_DOCUMENTS_CLICKED_TFI:
    'ADMISSION_LEAD_PROFILE_VIEW_DOCUMENTS_CLICKED_TFI',
  ADMISSION_LEAD_PROFILE_DOCUMENT_VIEWED_TFI:
    'ADMISSION_LEAD_PROFILE_DOCUMENT_VIEWED_TFI',
  ADMISSION_FORM_DOWNLOAD_CLICKED_TFI: 'ADMISSION_FORM_DOWNLOAD_CLICKED_TFI',
  ADMISSION_QR_CODE_CLICKED_TFI: 'ADMISSION_QR_CODE_CLICKED_TFI',
  ADMISSION_QR_CODE_DOWNLOADED_TFI: 'ADMISSION_QR_CODE_DOWNLOADED_TFI',

  //comms scheduler events
  COMMS_RULES_CREATION_SCHEDULE_CLICKED_TFI:
    'COMMS_RULES_CREATION_SCHEDULE_CLICKED_TFI',
  COMMS_HEAD_TOGGLE_CLICKED_TFI: 'COMMS_HEAD_TOGGLE_CLICKED_TFI',
  COMMS_RULES_TOGGLED_TFI: 'COMMS_RULES_TOGGLED_TFI',
  COMMS_RULES_TAB_SWITCHED_TFI: 'COMMS_RULES_TAB_SWITCHED_TFI',
  COMMS_RULES_CREATED_NEW_TFI: 'COMMS_RULES_CREATED_NEW_TFI',
  COMMS_RULES_MANAGE_CLICKED: 'COMMS_RULES_MANAGE_CLICKED',
  COMMS_RULES_VIEW_SENT_MESSAGES_TFI: 'COMMS_RULES_VIEW_SENT_MESSAGES_TFI',
  COMMS_RULES_EDIT_TFI: 'COMMS_RULES_EDIT_TFI',
  COMMS_RULES_DELETE_TFI: 'COMMS_RULES_DELETE_TFI',
  COMMS_RULES_MENU_CLICKED: 'COMMS_RULES_MENU_CLICKED',
  COMMS_RULES_RULE_DELETED: 'COMMS_RULES_RULE_DELETED',
  COMMS_RULES_SENT_MESSAGES_VIEWERS_SPLIT_TFI:
    'COMMS_RULES_SENT_MESSAGES_VIEWERS_SPLIT_TFI',
  COMMS_RULES_SENT_MESSAGES_VIEWERS_SEARCH_USED_TFI:
    'COMMS_RULES_SENT_MESSAGES_VIEWERS_SEARCH_USED_TFI',
  COMMS_MANAGE_DAY_TAB_CHANGED_TFI: 'COMMS_MANAGE_DAY_TAB_CHANGED_TFI',
  COMMS_RULES_MANAGE_SAVEANDEXIT_TFI: 'COMMS_RULES_MANAGE_SAVEANDEXIT_TFI',
  COMMS_SMS_RECHARGE_BALANCE_CLICKED: 'COMMS_SMS_RECHARGE_BALANCE_CLICKED',
  COMMS_RULES_CREATION_HOW_TO_SEND_NEXT_TFI:
    'COMMS_RULES_CREATION_HOW_TO_SEND_NEXT_TFI',
  COMMS_RULES_CREATION_WHEN_TO_SEND_NEXT_TFI:
    'COMMS_RULES_CREATION_WHEN_TO_SEND_NEXT_TFI',
  COMMS_RULES_CREATION_WHOM_TO_SEND_FINISH_TFI:
    'COMMS_RULES_CREATION_WHOM_TO_SEND_FINISH_TFI',
  COMMS_RULES_CREATION_EXIT_TFI: 'COMMS_RULES_CREATION_EXIT_TFI',
  COMMS_RULES_CREATION_STEPS_TFI: 'COMMS_RULES_CREATION_STEPS_TFI',
  // Fee structure delete and edit
  CANNOT_DELETE_STRUCUTURE_CLICKED_TFI: 'CANNOT_DELETE_STRUCUTURE_CLICKED_TFI',
  CANNOT_EDIT_STRUCTURE_CLICKED_TFI: 'CANNOT_EDIT_STRUCTURE_CLICKED_TFI',
  DELETE_RECEIPTS_DOWNLOAD_CSV_CLICKED_TFI:
    'DELETE_RECEIPTS_DOWNLOAD_CSV_CLICKED_TFI',
  DELETE_ALL_RECEIPTS_CLICKED_TFI: 'DELETE_ALL_RECEIPTS_CLICKED_TFI',
  DELETE_ALL_RECEIPTS_CANCEL_CLICKED_TFI:
    'DELETE_ALL_RECEIPTS_CANCEL_CLICKED_TFI',
  DELETE_ALL_RECEIPTS_POPUP_CLICKED_TFI:
    'DELETE_ALL_RECEIPTS_POPUP_CLICKED_TFI',
  ALL_RECEIPTS_DELETED_TFI: 'ALL_RECEIPTS_DELETED_TFI',
  DELETE_FEE_STRUCTURE_CANCEL_CLICKED_TFI:
    'DELETE_FEE_STRUCTURE_CANCEL_CLICKED_TFI',
  // ---
  DELETE_RECEIPT_CLICKED_TFI: 'DELETE_RECEIPT_CLICKED_TFI',
  DELETE_RECEIPT_POPUP_CLICKED_TFI: 'DELETE_RECEIPT_POPUP_CLICKED_TFI',
  FEE_RECEIPT_DELETED_TFI: 'FEE_RECEIPT_DELETED_TFI',

  // FEE company and account
  FEE_SIDEBAR_COMPANY_AND_ACCOUNT_CLICKED_TFI:
    'FEE_SIDEBAR_COMPANY_AND_ACCOUNT_CLICKED_TFI',
  FEE_ACCOUNT_MAPPING_INITIATED_TFI: 'FEE_ACCOUNT_MAPPING_INITIATED_TFI',
  FEE_ACCOUNT_MAPPING_SAVED_TFI: 'FEE_ACCOUNT_MAPPING_SAVED_TFI',
  FEE_ACCOUNT_MAPPING_RESET_TFI: 'FEE_ACCOUNT_MAPPING_RESET_TFI',
  FEE_CREATE_COMPANY_INITIALISED_TFI: 'FEE_CREATE_COMPANY_INITIALISED_TFI',
  FEE_CREATE_COMPANY_CLICKED_TFI: 'FEE_CREATE_COMPANY_CLICKED_TFI',
  FEE_COMPANY_ADDED_TFI: 'FEE_COMPANY_ADDED_TFI',
  FEE_ADD_ACCOUNT_INITIALISED_TFI: 'FEE_ADD_ACCOUNT_INITIALISED_TFI',
  FEE_ADD_ACCOUNT_CLICKED_TFI: 'FEE_ADD_ACCOUNT_CLICKED_TFI',
  FEE_ACCOUNT_ADDED_TFI: 'FEE_ACCOUNT_ADDED_TFI',
  FEE_COMPANY_KMENU_CLICKED_TFI: 'FEE_COMPANY_KMENU_CLICKED_TFI',
  FEE_ACCOUNT_KMENU_CLICKED_TFI: 'FEE_ACCOUNT_KMENU_CLICKED_TFI',
  FEE_COMPANY_STATUS_CHANGED_TFI: 'FEE_COMPANY_STATUS_CHANGED_TFI',
  FEE_ACCOUNT_STATUS_CHANGED_TFI: 'FEE_ACCOUNT_STATUS_CHANGED_TFI',
  FEE_COMPANIES_AND_ACCOUNTS_TAB_CLICKED_TFI:
    'FEE_COMPANIES_AND_ACCOUNTS_TAB_CLICKED_TFI',
  FEE_ACCOUNTS_MAPPING_TAB_CLICKED_TFI: 'FEE_ACCOUNTS_MAPPING_TAB_CLICKED_TFI',
  FEE_ACCOUNT_MAPPING_CLASSES_GROUP_INITIATED_TFI:
    'FEE_ACCOUNT_MAPPING_CLASSES_GROUP_INITIATED_TFI',
  FEE_ACCOUNT_MAPPING_CLASSES_GROUP_CLICKED_TFI:
    'FEE_ACCOUNT_MAPPING_CLASSES_GROUP_CLICKED_TFI',
  FEE_ACCOUNT_ACTIVITY_LOG_VIEW_CLICKED_TFI:
    'FEE_ACCOUNT_ACTIVITY_LOG_VIEW_CLICKED_TFI',

  // FEE COLLECTION REVAMP
  FEE_COLLECTION_SEARCH_BAR_CLICKED_TFI:
    'FEE_COLLECTION_SEARCH_BAR_CLICKED_TFI',
  BROWSE_STUDENTS_BY_CLASS_CLICKED_TFI: 'BROWSE_STUDENTS_BY_CLASS_CLICKED_TFI',
  HIDE_CLASSES_CLICKED_TFI: 'HIDE_CLASSES_CLICKED_TFI',
  RECORD_FEE_ADD_MORE_DETAILS_CLICKED_TFI:
    'RECORD_FEE_ADD_MORE_DETAILS_CLICKED_TFI',
  RECORD_FEE_ADD_NOTE_CLICKED_TFI: 'RECORD_FEE_ADD_NOTE_CLICKED_TFI',
  // ---
  // New dashboard events
  DASHBOARD_QUICK_ACTIONS_EDIT_CLICKED_TFI:
    'DASHBOARD_QUICK_ACTIONS_EDIT_CLICKED_TFI',
  DASHBOARD_QUICK_ACTIONS_EDIT_POPUP_CLICKED_TFI:
    'DASHBOARD_QUICK_ACTIONS_EDIT_POPUP_CLICKED_TFI',
  DASHBOARD_PENDING_LEAVE_TAB_CLICKED_TFI:
    'DASHBOARD_PENDING_LEAVE_TAB_CLICKED_TFI',
  DASHBOARD_MARK_ATTENDANCE_CLICKED_TFI:
    'DASHBOARD_MARK_ATTENDANCE_CLICKED_TFI',
  DASHBOARD_PENDING_TASK_MORE_OPTION_VIEW_CLICKED_TFI:
    'DASHBOARD_PENDING_TASK_MORE_OPTION_VIEW_CLICKED_TFI',
  DASHBOARD_QUICK_ACTIONS_NODE_CLICKED_TFI:
    'DASHBOARD_QUICK_ACTIONS_NODE_CLICKED_TFI',
  DASHBOARD_SCHOOL_OVERVIEW_DIRECTORY_VIEW_CLICKED_TFI:
    'DASHBOARD_SCHOOL_OVERVIEW_DIRECTORY_VIEW_CLICKED_TFI',
  DASHBOARD_FEES_REPORTS_VIEW_CLICKED_TFI:
    'DASHBOARD_FEES_REPORTS_VIEW_CLICKED_TFI',
  DASHBOARD_LEAVE_VIEW_CLICKED_TFI: 'DASHBOARD_LEAVE_VIEW_CLICKED_TFI',
  DASHBOARD_CLASS_ATTENDANCE_REPORTS_VIEW_CLICKED_TFI:
    'DASHBOARD_CLASS_ATTENDANCE_REPORTS_VIEW_CLICKED_TFI',
  DASHBOARD_CLASS_ATTENDANCE_REPORTS_POPUP_CLICKED_TFI:
    'DASHBOARD_CLASS_ATTENDANCE_REPORTS_POPUP_CLICKED_TFI',
  DASHBOARD_CLASS_HOMEWORK_REPORTS_VIEW_CLICKED_TFI:
    'DASHBOARD_CLASS_HOMEWORK_REPORTS_VIEW_CLICKED_TFI',
  CLASS_HOMEWORK_REPORTS_POPUP_CLICKED_TFI:
    'CLASS_HOMEWORK_REPORTS_POPUP_CLICKED_TFI',
  DASHBOARD_COMMUNICATION_VIEW_CLICKED_TFI:
    'DASHBOARD_COMMUNICATION_VIEW_CLICKED_TFI',
  DASHBOARD_REPORTS_NOTIFY_CLASS_TEACHER_CLICKED_TFI:
    'DASHBOARD_REPORTS_NOTIFY_CLASS_TEACHER_CLICKED_TFI',
  DASHBOARD_REPORTS_NOTIFY_STUDENT_CLICKED_TFI:
    'DASHBOARD_REPORTS_NOTIFY_STUDENT_CLICKED_TFI',
  DASHBOARD_QUICK_ACTIONS_EDIT_TOGGLE_SUBMITTED_TFI:
    'DASHBOARD_QUICK_ACTIONS_EDIT_TOGGLE_SUBMITTED_TFI',
  STUDENT_ATTENDANCE_REPORT_STATUS_CLICKED_TFI:
    'STUDENT_ATTENDANCE_REPORT_STATUS_CLICKED_TFI',
  STUDENT_ATTENDANCE_REPORT_CLICKED_TFI:
    'STUDENT_ATTENDANCE_REPORT_CLICKED_TFI',

  // Biometric Events list
  HRMS_CONFIGURATION_CLICKED_TFI: 'HRMS_CONFIGURATION_CLICKED_TFI',
  HRMS_BIOMETRIC_CONFIGURATION_REQUEST_CLICKED_TFI:
    'HRMS_BIOMETRIC_CONFIGURATION_REQUEST_CLICKED_TFI',
  HRMS_BIOMETRIC_CONFIGURATION_REQUEST_INITIATED_TFI:
    'HRMS_BIOMETRIC_CONFIGURATION_REQUEST_INITIATED_TFI',
  HRMS_BIOMETRIC_CONFIGURATION_REQUESTED_TFI:
    'HRMS_BIOMETRIC_CONFIGURATION_REQUESTED_TFI',
  HRMS_USER_MAPPING_BULK_UPLOAD_INITIATE_CLICKED_TFI:
    'HRMS_USER_MAPPING_BULK_UPLOAD_INITIATE_CLICKED_TFI',
  HRMS_USER_MAPPING_BULK_UPLOAD_SAMPLE_CSV_DOWNLOAD_CLICKED_TFI:
    'HRMS_USER_MAPPING_BULK_UPLOAD_SAMPLE_CSV_DOWNLOAD_CLICKED_TFI',
  HRMS_USER_MAPPING_BULK_CSV_UPLOAD_CLICKED_TFI:
    'HRMS_USER_MAPPING_BULK_CSV_UPLOAD_CLICKED_TFI',
  HRMS_USER_MAPPING_BULK_CSV_UPLOADED_TFI:
    'HRMS_USER_MAPPING_BULK_CSV_UPLOADED_TFI',
  HRMS_USER_MAPPING_BULK_CSV_UPLOADED_REMOVE_CLICKED_TFI:
    'HRMS_USER_MAPPING_BULK_CSV_UPLOADED_REMOVE_CLICKED_TFI',
  HRMS_USER_MAPPING_BULK_CSV_UPLOAD_NEXT_CLICKED_TFI:
    'HRMS_USER_MAPPING_BULK_CSV_UPLOAD_NEXT_CLICKED_TFI',
  HRMS_USER_MAPPING_BULK_CSV_UPLOAD_DUPLICATE_ENTRIES_CLICKED_TFI:
    'HRMS_USER_MAPPING_BULK_CSV_UPLOAD_DUPLICATE_ENTRIES_CLICKED_TFI',
  HRMS_USER_MAPPING_BULK_CSV_UPLOAD_UPDATE_CLICKED_TFI:
    'HRMS_USER_MAPPING_BULK_CSV_UPLOAD_UPDATE_CLICKED_TFI',
  HRMS_USER_MAPPING_FILTER_CLICKED_TFI: 'HRMS_USER_MAPPING_FILTER_CLICKED_TFI',
  HRMS_EDIT_USER_ID_CLICKED_TFI: 'HRMS_EDIT_USER_ID_CLICKED_TFI',
  HRMS_SAVE_USER_ID_CLICKED_TFI: 'HRMS_SAVE_USER_ID_CLICKED_TFI',
  HRMS_DELETE_USER_CLICKED_TFI: 'HRMS_DELETE_USER_CLICKED_TFI',
  HRMS_ADD_NEW_MACHINE_CLICKED_TFI: 'HRMS_ADD_NEW_MACHINE_CLICKED_TFI',
  HRMS_ADD_NEW_MACHINE_SAVE_CLICKED_TFI:
    'HRMS_ADD_NEW_MACHINE_SAVE_CLICKED_TFI',
  HRMS_DOWNLOAD_ATTENDANCE_LOG_CLICKED_TFI:
    'HRMS_DOWNLOAD_ATTENDANCE_LOG_CLICKED_TFI',
  HRMS_USER_MAPPING_ALL_USERS_TAB_CLICKED_TFI:
    'HRMS_USER_MAPPING_ALL_USERS_TAB_CLICKED_TFI',
  HRMS_USER_MAPPING_REGISTERED_USERS_TAB_CLICKED_TFI:
    'HRMS_USER_MAPPING_REGISTERED_USERS_TAB_CLICKED_TFI',
  HRMS_USER_MAPPING_UNREGISTERED_USERS_TAB_CLICKED_TFI:
    'HRMS_USER_MAPPING_UNREGISTERED_USERS_TAB_CLICKED_TFI',
  // Admit Card Events
  ADMIT_CARD_CLICKED_TFI: 'ADMIT_CARD_CLICKED_TFI',
  ADMIT_CARD_STANDARD_TAB_CLICKED_TFI: 'ADMIT_CARD_STANDARD_TAB_CLICKED_TFI',
  ADMIT_CARD_SECTION_SELECTED_TFI: 'ADMIT_CARD_SECTION_SELECTED_TFI',
  ADMIT_CARD_TEMPLATE_PREVIEW_CLICKED_TFI:
    'ADMIT_CARD_TEMPLATE_PREVIEW_CLICKED_TFI',
  ADMIT_CARD_GENERATE_CLICKED_TFI: 'ADMIT_CARD_GENERATE_CLICKED_TFI',
  ADMIT_CARD_SUBMIT_CLICKED_TFI: 'ADMIT_CARD_SUBMIT_CLICKED_TFI',
  ADMIT_CARD_BULK_DOWNLOAD_CLICKED_TFI: 'ADMIT_CARD_BULK_DOWNLOAD_CLICKED_TFI',
  ADMIT_CARD_STUDENT_PREVIEW_TAB_CLICKED_TFI:
    'ADMIT_CARD_STUDENT_PREVIEW_TAB_CLICKED_TFI',
  ADMIT_CARD_STUDENT_DOWNLOAD_CLICKED_TFI:
    'ADMIT_CARD_STUDENT_DOWNLOAD_CLICKED_TFI',
  ADMIT_CARD_STUDENT_PRINT_CLICKED_TFI: 'ADMIT_CARD_STUDENT_PRINT_CLICKED_TFI',
  ADMIT_CARD_UPDATE_CLICKED_TFI: 'ADMIT_CARD_UPDATE_CLICKED_TFI',
  FEE_REPORTS_TAB_CLICKED_TFI: 'FEE_REPORTS_TAB_CLICKED_TFI',
  FEE_REPORTS_CREATE_CUSTOM_CLICKED_TFI:
    'FEE_REPORTS_CREATE_CUSTOM_CLICKED_TFI',
  FEE_REPORTS_CREATE_CUSTOM_PROCEED_CLICKED_TFI:
    'FEE_REPORTS_CREATE_CUSTOM_PROCEED_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_NAME_EDIT_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_NAME_EDIT_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_RESET_CLICKED_TFI: 'FEE_REPORTS_CUSTOM_RESET_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_RESET_POPUP_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_RESET_POPUP_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_SELECTION_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_SELECTION_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_FILTER_SELECTION_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_FILTER_SELECTION_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_FILTER_SELECTION_APPLY_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_FILTER_SELECTION_APPLY_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_DATE_RANGE_SELECTION_TFI:
    'FEE_REPORTS_CUSTOM_DATE_RANGE_SELECTION_TFI',
  FEE_REPORTS_CUSTOM_UPDATE_TABLE_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_UPDATE_TABLE_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_CHIP_CANCEL_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_CHIP_CANCEL_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_EDIT_CLICKED_TFI: 'FEE_REPORTS_CUSTOM_EDIT_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_DELETE_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_DELETE_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_DELETE_POPUP_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_DELETE_POPUP_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_PUBLISH_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_PUBLISH_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_EXIT_POPUP_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_EXIT_POPUP_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_DOWNLOAD_CLICKED_TFI:
    'FEE_REPORTS_CUSTOM_DOWNLOAD_CLICKED_TFI',
  FEE_REPORTS_CUSTOM_SEARCH_TFI: 'FEE_REPORTS_CUSTOM_SEARCH_TFI',
  FEE_REPORTS_CUSTOM_SEARCH_CANCELLED_TFI:
    'FEE_REPORTS_CUSTOM_SEARCH_CANCELLED_TFI',

  // Previous Session Dues
  FEE_PREVIOUS_SESSION_DUES_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_IMPORT_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_IMPORT_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_IMPORT_SELECTED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_IMPORT_SELECTED_TFI',
  FEE_PREVIOUS_SESSION_DUES_IMPORTED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_IMPORTED_TFI',
  FEE_PREVIOUS_SESSION_DUES_CSV_UPLOAD_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_CSV_UPLOAD_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_DOWNLOAD_STUDENT_LIST_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_DOWNLOAD_STUDENT_LIST_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_CHOOSE_FILE_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_CHOOSE_FILE_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_FILE_DELETED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_FILE_DELETED_TFI',
  FEE_PREVIOUS_SESSION_DUES_FILE_ERROR_TFI:
    'FEE_PREVIOUS_SESSION_DUES_FILE_ERROR_TFI',
  FEE_PREVIOUS_SESSION_DUES_FILE_UPLOADED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_FILE_UPLOADED_TFI',
  FEE_PREVIOUS_SESSION_DUES_CSV_UPLOAD_SELECTED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_CSV_UPLOAD_SELECTED_TFI',
  FEE_PREVIOUS_SESSION_DUES_CSV_UPLOADED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_CSV_UPLOADED_TFI',
  FEE_PREVIOUS_SESSION_DUES_CSV_UPDATE_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_CSV_UPDATE_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_MODIFY_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_MODIFY_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_DELETE_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_DELETE_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_FOR_ALL_STUDENTS_DELETE_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_FOR_ALL_STUDENTS_DELETE_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_FOR_ALL_STUDENTS_DELETE_POP_UP_CLICKED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_FOR_ALL_STUDENTS_DELETE_POP_UP_CLICKED_TFI',
  FEE_PREVIOUS_SESSION_DUES_FOR_ALL_STUDENTS_DELETED_TFI:
    'FEE_PREVIOUS_SESSION_DUES_FOR_ALL_STUDENTS_DELETED_TFI',
  // PLR - Instant Impact Events
  PAY_OVERDUE_AMOUNT_NOW_TFI: 'PAY_OVERDUE_AMOUNT_NOW_TFI',
  PAY_OVERDUE_AMOUNT_NOW_PAY_DUES_NOW_TFI:
    'PAY_OVERDUE_AMOUNT_NOW_PAY_DUES_NOW_TFI',
  PAY_OVERDUE_AMOUNT_NOW_POPUP_DISMISSED_TFI:
    'PAY_OVERDUE_AMOUNT_NOW_POPUP_DISMISSED_TFI',

  // Student management
  SIS_SEARCH_FILTER_TYPE_SELECTED_TFI: 'SIS_SEARCH_FILTER_TYPE_SELECTED_TFI',
  SIS_SEARCH_BAR_FOCUSSED_TFI: 'SIS_SEARCH_BAR_FOCUSSED_TFI',
  SIS_STATUS_FILTER_SELECTED_TFI: 'SIS_STATUS_FILTER_SELECTED_TFI',
  SIS_CLASS_FILTER_SELECTED_TFI: 'SIS_CLASS_FILTER_SELECTED_TFI',
  SIS_GENDER_FILTER_SELECTED_TFI: 'SIS_GENDER_FILTER_SELECTED_TFI',
  SIS_DOWNLOAD_LIST_CLICKED_TFI: 'SIS_DOWNLOAD_LIST_CLICKED_TFI',
  SIS_SEND_ANNOUNCEMENT_CLICKED_TFI: 'SIS_SEND_ANNOUNCEMENT_CLICKED_TFI',
  SIS_SEND_INVITE_CLICKED_TFI: 'SIS_SEND_INVITE_CLICKED_TFI',
  SIS_DOWNLOAD_EXISTING_LIST_CLICKED_TFI:
    'SIS_DOWNLOAD_EXISTING_LIST_CLICKED_TFI',
  SIS_SEND_INVITE_POPUP_CLICKED_TFI: 'SIS_SEND_INVITE_POPUP_CLICKED_TFI',
  SIS_USER_PROFILE_OPENED_TFI: 'SIS_USER_PROFILE_OPENED_TFI',
  SIS_VIEW_FULL_INFORMATION_CLICKED_TFI:
    'SIS_VIEW_FULL_INFORMATION_CLICKED_TFI',
  SIS_OVERVIEW_DELETE_USER_CLICKED_TFI: 'SIS_OVERVIEW_DELETE_USER_CLICKED_TFI',
  SIS_PROFILE_CHANGE_SECTION_CLICKED_TFI:
    'SIS_PROFILE_CHANGE_SECTION_CLICKED_TFI',
  SIS_PROFILE_CHANGE_SECTION_SAVE_CLICKED_TFI:
    'SIS_PROFILE_CHANGE_SECTION_SAVE_CLICKED_TFI',
  SIS_PROFILE_ASSIGN_SECTION_CLICKED_TFI:
    'SIS_PROFILE_ASSIGN_SECTION_CLICKED_TFI',
  SIS_PROFILE_ASSIGN_SECTION_SAVE_CLICKED_TFI:
    'SIS_PROFILE_ASSIGN_SECTION_SAVE_CLICKED_TFI',

  SIS_VIEW_DOCUMENT_CLICKED_TFI: 'SIS_VIEW_DOCUMENT_CLICKED_TFI',
  SIS_VIEW_FEE_SUMMARY_CLICKED_TFI: 'SIS_VIEW_FEE_SUMMARY_CLICKED_TFI',
  SIS_EDIT_TRANSPORT_DETAILS_CLICKED_TFI:
    'SIS_EDIT_TRANSPORT_DETAILS_CLICKED_TFI',
  SIS_VIEW_ISSUED_ITEMS_CLICKED_TFI: 'SIS_VIEW_ISSUED_ITEMS_CLICKED_TFI',

  STAFF_ATTENDANCE_CARD_LOADED_TFI: 'STAFF_ATTENDANCE_CARD_LOADED_TFI',
  LEAVE_CARD_LOADED_TFI: 'LEAVE_CARD_LOADED_TFI',
  LEAVE_VIEW_CLICKED_TFI: 'LEAVE_VIEW_CLICKED_TFI',
  LEAVE_SETUP_CLICKED_TFI: 'LEAVE_SETUP_CLICKED_TFI',
  LAST_ANNOUNCEMENT_VIEW_CLICKED_TFI: 'LAST_ANNOUNCEMENT_VIEW_CLICKED_TFI',
  ANNOUNCEMENT_STATUS_CARD_CLICKED_TFI: 'ANNOUNCEMENT_STATUS_CARD_CLICKED_TFI',
  ADMIN_ONBOARDING_CLICKED_TFI: 'ADMIN_ONBOARDING_CLICKED_TFI',
  DASHBOARD_WIDGETS_LOADED: 'DASHBOARD_WIDGETS_LOADED',
  STUDENT_ONBOARDING_CLICKED_TFI: 'STUDENT_ONBOARDING_CLICKED_TFI',

  //Attendance Shifts
  SETUP_AUTOMATED_ATTENDANCE_CLICKED_TFI:
    'SETUP_AUTOMATED_ATTENDANCE_CLICKED_TFI',
  SETUP_SHIFT_NEXT_CLICKED_TFI: 'SETUP_SHIFT_NEXT_CLICKED_TFI',
  SELECT_STAFF_NEXT_CLICKED_TFI: 'SELECT_STAFF_NEXT_CLICKED_TFI',
  ATTENDANCE_METHOD_SAVE_CLICKED_TFI: 'ATTENDANCE_METHOD_SAVE_CLICKED_TFI',
  SETUP_ATTENDANCE_CONFIG_EXIT_POPUP_CLICKED_TFI:
    'SETUP_ATTENDANCE_CONFIG_EXIT_POPUP_CLICKED_TFI',
  CREATE_NEW_SHIFT_CLICKED_TFI: 'CREATE_NEW_SHIFT_CLICKED_TFI',
  ATTENDANCE_SHIFTS_TAB_CLICKED_TFI: 'ATTENDANCE_SHIFTS_TAB_CLICKED_TFI',
  ATTENDANCE_SHIFTS_KMENU_CLICKED_TFI: 'ATTENDANCE_SHIFTS_KMENU_CLICKED_TFI',
  ATTENDANCE_SHIFT_DELETED_TFI: 'ATTENDANCE_SHIFT_DELETED_TFI',
  BIOMETRIC_CONFIGURATION_TAB_CLICKED_TFI:
    'BIOMETRIC_CONFIGURATION_TAB_CLICKED_TFI',
  SHIFT_MANAGE_USERS_CLICKED_TFI: 'SHIFT_MANAGE_USERS_CLICKED_TFI',

  FEE_COLLECTION_DATE_FILTER_CLICKED_TFI:
    'FEE_COLLECTION_DATE_FILTER_CLICKED_TFI',

  //Session Transfer
  IMPORT_SESSION_SELECTED_DROPDOWN_TFI: 'IMPORT_SESSION_SELECTED_DROPDOWN_TFI',
  SESSION_IMPORT_START_CLICKED_TFI: 'SESSION_IMPORT_START_CLICKED_TFI',
  SESSION_TRANSFER_COMPLTED_TFI: 'SESSION_TRANSFER_COMPLTED_TFI',

  // Id card checkout
  IDCARD_ORDER_BANNER_CLICKED_TFI: 'IDCARD_ORDER_BANNER_CLICKED_TFI',
  IDCARD_ORDER_POPUP_USER_SELECTION_CLICKED_TFI:
    'IDCARD_ORDER_POPUP_USER_SELECTION_CLICKED_TFI',
  IDCARD_ORDER_POPUP_CARD_PREVIEW_CLICKED_TFI:
    'IDCARD_ORDER_POPUP_CARD_PREVIEW_CLICKED_TFI',
  IDCARD_ORDER_POPUP_CARD_TYPE_SELECTION_CLICKED_TFI:
    'IDCARD_ORDER_POPUP_CARD_TYPE_SELECTION_CLICKED_TFI',
  IDCARD_ORDER_POPUP_LEYNARD_SELECTION_CLICKED_TFI:
    'IDCARD_ORDER_POPUP_LEYNARD_SELECTION_CLICKED_TFI',
  IDCARD_ORDER_POPUP_CARD_HOLDER_SELECTION_CLICKED_TFI:
    'IDCARD_ORDER_POPUP_CARD_HOLDER_SELECTION_CLICKED_TFI',
  IDCARD_ORDER_CHECKOUT_POPUP_CLICKED_TFI:
    'IDCARD_ORDER_CHECKOUT_POPUP_CLICKED_TFI',
  PURCHASE_HISTORY_OPENED_TFI: 'PURCHASE_HISTORY_OPENED_TFI',
  VIEW_ID_CARD_ORDER_DETAILS_TFI: 'VIEW_ID_CARD_ORDER_DETAILS_TFI',
  DOWNLOAD_ID_CARD_ORDER_RECEIPT_CLICKED_TFI:
    'DOWNLOAD_ID_CARD_ORDER_RECEIPT_CLICKED_TFI',
  STUDENT_ATTENDANCE_DATE_SELECTED_TFI: 'STUDENT_ATTENDANCE_DATE_SELECTED_TFI',
  SESSION_IMPORT_SAVE_EXIT_CLICKED_TFI: 'SESSION_IMPORT_SAVE_EXIT CLICKED_TFI',
  SESSION_IMPORT_NEXT_CLICKED_TFI: 'SESSION_IMPORT_NEXT CLICKED_TFI',
  IMPORT_SESSION_CLICKED_TFI: 'IMPORT_SESSION_CLICKED_TFI',
}

export const fbEvents = [
  events.SIGNUP_SUCCESSFUL,
  events.PROFILE_CREATION_INITIALIZED_TFI,
  events.TEACHER_ADDED_TFI,
  events.TEACHER_ADDED_IN_COACHING_TFI,
  events.TEACHER_ADDED_IN_SCHOOL_TFI,
  events.TEACHER_ADDED_IN_COLLEGE_TFI,
]
