// Screens
export const SCN_SLI_CREATE_EXAM = 'SCN_SLI_CREATE_EXAM'
export const SCN_SLI_UPDATE_EXAM = 'SCN_SLI_UPDATE_EXAM'
export const SCN_SLI_CREATE_SUBJECT_ASSESSMENT =
  'SCN_SLI_CREATE_SUBJECT_ASSESSMENT'
export const SCN_SLI_VIEW_SUBJECT_ASSESSMENT_RESULT =
  'SCN_SLI_VIEW_SUBJECT_ASSESSMENT_RESULT'

// Actions
export const ACT_EXAM_EDIT = 'ACT_EXAM_EDIT'
export const ACT_EXAM_DELETE = 'ACT_EXAM_DELETE'

// Constants
export const EXAM_TYPES = {DRAFT: 1, HOLIDAY: 2, PUBLISHED: 3, DELETED: 4}
export const TIME_FORMAT = 'hh:mm a'
