import {DateTime} from 'luxon'
import {employmentTypeOptions, genderOptions} from './SampleCSVRows'

export const teacherFields = {
  name: {
    fieldType: 'text',
    title: 'Teacher Name*',
    placeholder: 'Enter Teacher Name',
    fieldName: 'name',
    errorString: 'Enter a valid input',
  },
  phone_number: {
    fieldType: 'phone',
    title: 'Phone Number*',
    placeholder: 'Enter Phone Number',
    fieldName: 'phone_number',
    errorString: 'Enter a valid input',
  },
  country_code: {
    fieldType: 'country_code',
    placeholder: '91',
    fieldName: 'country_code',
    errorString: 'Enter a valid input',
  },
  gender: {
    fieldType: 'radio',
    title: 'Gender',
    placeholder: '',
    fieldName: 'gender',
    errorString: 'Enter a valid input',
    dropdownItems: genderOptions,
  },
  email: {
    fieldType: 'text',
    title: 'Email',
    placeholder: 'Enter Teacher Email',
    fieldName: 'email',
    errorString: 'Enter a valid input',
  },
  designation: {
    fieldType: 'text',
    title: 'Designation',
    placeholder: 'Enter Designation',
    fieldName: 'designation',
    errorString: 'Enter a valid input',
  },
  qualification: {
    fieldType: 'text',
    title: 'Qualification',
    placeholder: 'Enter Qualification',
    fieldName: 'qualification',
    errorString: 'Enter a valid input',
  },
  employee_id: {
    fieldType: 'text',
    title: 'Employee ID',
    placeholder: 'Enter Employee ID',
    fieldName: 'employee_id',
    errorString: 'Enter a valid input',
  },
  aadhar_number: {
    fieldType: 'text',
    title: 'Aadhar Number',
    placeholder: 'Enter Aadhar Number',
    fieldName: 'aadhar_number',
    errorString: 'Enter a valid input',
  },
  pan_number: {
    fieldType: 'text',
    title: 'PAN Number',
    placeholder: 'Enter PAN Number',
    fieldName: 'pan_number',
    errorString: 'Enter a valid input',
  },
  address: {
    fieldType: 'text',
    title: 'Address',
    placeholder: 'Enter Address',
    fieldName: 'address',
    errorString: 'Enter a valid input',
  },
  pincode: {
    fieldType: 'text',
    title: 'Pincode',
    placeholder: 'Enter Pincode',
    fieldName: 'pincode',
    errorString: 'Enter a valid input',
  },
  employment_type: {
    fieldType: 'dropdown',
    dropdownItems: employmentTypeOptions,
    title: 'Employment Type',
    placeholder: 'Enter Employment Type',
    fieldName: 'employment_type',
    errorString: 'Enter a valid input',
  },
  date_of_birth: {
    fieldType: 'date',
    title: 'Date of Birth',
    placeholder: 'Enter Date of Birth',
    fieldName: 'date_of_birth',
    errorString: 'Enter a valid input',
  },
  experience: {
    fieldType: 'text',
    title: 'Teaching Experience(years)',
    placeholder: 'Enter Teaching Experience',
    fieldName: 'experience',
    errorString: 'Enter a valid input',
  },
  date_of_appointment: {
    fieldType: 'date',
    title: 'Appointment Date',
    placeholder: 'Enter Appointment Date',
    fieldName: 'date_of_appointment',
    errorString: 'Enter a valid input',
  },
}

export const defaultTeacherFieldValues = {
  name: '',
  phone_number: '',
  country_code: '91',
  gender: '',
  email: '',
  designation: '',
  qualification: '',
  employee_id: '',
  aadhar_number: '',
  pan_number: '',
  address: '',
  pincode: '',
  employment_type: 'Select',
  date_of_birth: '',
  experience: '',
  date_of_appointment: '',
}

export const teacher_headers = [
  'First Name*',
  'Middle Name',
  'Last Name',
  'Country Code*',
  'Teacher Mobile Number*',
  'Employment ID',
  'Date of Birth',
  'Email ID',
  'Gender',
  'Aadhaar Number',
  'PAN Number',
  'Address Line 1',
  'Address Line 2',
  'Country',
  'State',
  'City/Town',
  'Pincode',
]

export const studentFields = {
  name: {
    fieldType: 'text',
    title: 'First Name',
    placeholder: 'Enter First Name',
    fieldName: 'name',
    errorString: 'Enter a valid input',
    width: '1/3',
    isRequired: true,
  },
  middleName: {
    fieldType: 'text',
    title: 'Middle Name',
    placeholder: 'Enter Middle Name',
    fieldName: 'middle_name',
    errorString: 'Enter a valid input',
    width: '1/3',
  },
  lastName: {
    fieldType: 'text',
    title: 'Last Name',
    placeholder: 'Enter Last Name',
    fieldName: 'last_name',
    errorString: 'Enter a valid input',
    width: '1/3',
  },
  phone_number: {
    fieldType: 'phoneNumber',
    title: 'Student Mobile Number',
    placeholder: 'Enter mobile Number',
    fieldName: 'phone_number',
    errorString: 'Enter a valid input',
    width: '2/3',
    isRequired: true,
  },
  country_code: {
    fieldType: 'country_code',
    placeholder: '91',
    fieldName: 'country_code',
    errorString: 'Enter a valid input',
  },
  gender: {
    title: 'Gender',
    fieldType: 'radio',
    placeholder: '',
    fieldName: 'gender',
    errorString: 'Enter a valid input',
    dropdownItems: genderOptions,
  },
  email: {
    fieldType: 'text',
    title: 'Email',
    placeholder: 'Enter Student Email',
    fieldName: 'email',
    errorString: 'Enter a valid input',
  },
  standard: {
    fieldType: 'text',
    title: 'Class',
    placeholder: 'Enter Class',
    fieldName: 'standard',
    errorString: 'Enter a valid input',
    isRequired: true,
  },
  section: {
    fieldType: 'text',
    title: 'Section',
    placeholder: 'Enter Section',
    fieldName: 'section',
    errorString: 'Enter a valid input',
    isRequired: true,
  },
  enrollment_number: {
    fieldType: 'text',
    title: 'Enrollment Number',
    placeholder: 'Enter Enrollment Number',
    fieldName: 'enrollment_number',
    errorString: 'Enter a valid input',
  },
  guardian_name: {
    fieldType: 'text',
    title: 'Guardian Name',
    placeholder: 'Enter Guardian Name',
    fieldName: 'guardian_name',
    errorString: 'Enter a valid input',
  },
  guardian_number: {
    fieldType: 'phone',
    title: 'Guardian Phone Number',
    placeholder: 'Enter Phone Number',
    fieldName: 'guardian_number',
    errorString: 'Enter a valid input',
  },
  guardian_country_code: {
    fieldType: 'country_code',
    placeholder: '91',
    fieldName: 'guardian_country_code',
    errorString: 'Enter a valid input',
  },
  address: {
    fieldType: 'text',
    title: 'Address',
    placeholder: 'Enter Address',
    fieldName: 'address',
    errorString: 'Enter a valid input',
  },
  pincode: {
    fieldType: 'text',
    title: 'Pincode',
    placeholder: 'Enter Pincode',
    fieldName: 'pincode',
    errorString: 'Enter a valid input',
  },
  date_of_birth: {
    fieldType: 'date',
    title: 'Date of Birth',
    placeholder: 'Enter Date of Birth',
    fieldName: 'date_of_birth',
    errorString: 'Enter a valid input',
  },
  is_transport_required: {
    fieldType: 'toogle',
    title: 'Transport Fee',
    fieldName: 'is_transport_required',
    errorString: 'Enter a valid input',
  },
  transport_waypoint: {
    fieldType: 'dropdown',
    dropdownItems: [],
    title: 'Enter Pickup Point',
    placeholder: '',
    fieldName: 'transport_waypoint',
    errorString: 'Enter a valid input',
  },
  admission_timestamp: {
    fieldType: 'date',
    title: 'Admission Date',
    placeholder: 'Enter Admission Date',
    fieldName: 'admission_timestamp',
    errorString: 'Enter a valid input',
  },
}

export const student_headers = [
  'First Name*',
  'Middle Name',
  'Last Name',
  'Country Code*',
  'Phone*',
  'Enrollment ID*',
  'Date of Admission*',
  'Class',
  'Section',
  'Email',
  'Class Roll Number',
  'Date of Birth',
  'Gender',
  'Address Line 1',
  'Address Line 2',
  'Country',
  'State',
  'City/Town',
  'Pincode',
]

export const defaultStudentFieldValues = {
  name: '',
  phone_number: '',
  admission_timestamp: DateTime.now().toFormat('yyyy-MM-dd'),
  country_code: '91',
  gender: '',
  email: '',
  standard: '',
  section: '',
  enrollment_number: '',
  guardian_name: '',
  guardian_number: '',
  guardian_country_code: '91',
  address: '',
  pincode: '',
  date_of_birth: '',
  is_transport_required: false,
  transport_distance: '',
  transport_waypoint: '',
}
