import {INSTITUTE_TYPES} from './../constants/institute.constants'

export const sampleCSV = {
  teachers: [
    {
      'First Name*': 'Rajeev',
      'Middle Name': 'Kumar',
      'Last Name': 'Mishra',
      'Country Code*': '91',
      'Teacher Mobile Phone*': '9000900090',
      'Employment ID': 'EMP001',
      'Date of Birth': '09/08/1990',
      'Email Address': 'teachermishra@tfi.com',
      Gender: 'male',
      'Aadhaar Number': '323412341234',
      'PAN Number': 'BHOPT5764R',
      'Address Line 1': 'R-101',
      'Address Line 2': 'Vijayanagar',
      Country: 'India',
      State: 'Karnataka',
      'City/Town': 'Bangalore',
      Pincode: '890890',
      'Job Title': 'Teacher',
      Designation: 'Senior Teacher',
      'Employment Type': 'Permanent',
      'Date of Appointment': '04/02/2021',
      'Teaching Experience': '3',
    },
  ],
  students: [
    {
      'First Name*': 'Raghav',
      'Middle Name': 'Kumar',
      'Last Name': 'Chadda',
      'Country Code*': '91',
      'Phone*': '6666666666',
      'Enrollment ID*': '123123',
      'Date of Admission*': '03/04/2012',
      Class: '10',
      Section: 'B',
      Email: 'raghav.chadda@tfi.com',
      'Class Roll Number': '0031',
      'Date of Birth': '03/07/1998',
      Gender: 'male',
      'Address Line 1': 'A-103',
      'Address Line 2': 'Sarjapur Road',
      Country: 'India',
      State: 'Karnataka',
      'City/Town': 'Bangalore',
      Pincode: '560103',
      'Father Contact Number': '9999999987',
      'Father Name': 'Lal Singh Chadda',
      'Father Occupation': 'Business',
      'Mother Contact Number': '9999999986',
      'Mother Name': 'Lali Kaur',
      'Mother Occupation': 'House wife',
      'Guardian Contact Number': '',
      'Guardian Name': '',
      'Guardian Relationship': '',
      Religion: '',
      Category: '',
      'Right To Education (RTE Quota)': 'No',
      'Person with Disability (PwD)': 'No',
    },
  ],
}

export const addBooksSampleCSV = {
  addBooks: [
    {
      'Name*': 'Rich Dad Poor Dad',
      'ISBN Number*': '42000000000000000001',
      'Author Name*': 'Robert T. Kiyosaki',
    },
    {
      'Name*': 'The 3 Mistakes of My Life',
      'ISBN Number*': '42000000000000000002',
      'Author Name*': 'Chetan Bhagat',
    },
    {
      'Name*': 'Chanakya Neeti',
      'ISBN Number*': '42000000000000000003',
      'Author Name*': 'Chanakya',
    },
  ],
}

export const getStudentSampleCSV = (instiType) => {
  let json = {...sampleCSV.students[0]}
  if (instiType === INSTITUTE_TYPES.COLLEGE) {
    json['Program'] = ''
    json['Stream'] = ''
    json['Year'] = ''
    json['Classroom Ids'] = []
    delete json.Section
    delete json.Class
    return [json]
  }
  if (instiType === INSTITUTE_TYPES.TUITION) {
    json['Department'] = 'Department 1'
    json['Batch'] = 'Batch 1'
    delete json.Section
    delete json.Class
    return [json]
  }
  json['Last School Attended'] = ''
  json['Last School Affiliated to'] = ''
  json['Last Class Passed'] = ''
  return [json]
}

export const employmentTypeOptions = [
  {key: 'Select', value: 'Select'},
  {key: 'Permanent', value: 'Permanent'},
  {key: 'Contract', value: 'Contract'},
]

export const genderOptions = [
  {key: 'Male', value: 'Male'},
  {key: 'Female', value: 'Female'},
  {key: 'Others', value: 'Others'},
]

export const classOptions = [
  {value: 'PLAY SCHOOL', label: 'Play School', weight: -5},
  {value: 'PRE NURSERY', label: 'Pre Nursery', weight: -4},
  {value: 'NURSERY', label: 'Nursery', weight: -3},
  {value: 'LKG', label: 'LKG', weight: -2},
  {value: 'UKG', label: 'UKG', weight: -1},
  {value: '1', label: '1st', weight: 1},
  {value: '2', label: '2nd', weight: 2},
  {value: '3', label: '3rd', weight: 3},
  {value: '4', label: '4th', weight: 4},
  {value: '5', label: '5th', weight: 5},
  {value: '6', label: '6th', weight: 6},
  {value: '7', label: '7th', weight: 7},
  {value: '8', label: '8th', weight: 8},
  {value: '9', label: '9th', weight: 9},
  {value: '10', label: '10th', weight: 10},
  {value: '11', label: '11th', weight: 11},
  {value: '12', label: '12th', weight: 12},
]

export const userTypeOptions = {
  teachers: {key: 'teachers', value: 'All Teachers'},
  students: {key: 'students', value: 'All Students'},
  all: {key: 'all', value: 'All Teachers and Students'},
}

export const subjectOptions = [
  'Abacus',
  'Accountancy',
  'Acting',
  'Agriculture',
  'Agronomy',
  'Algebra',
  'All Subjects',
  'Analog Electronics',
  'Analytical chemistry',
  'Analytics',
  'Anatomy',
  'Ancient History',
  'Android',
  'Animal Husbandry',
  'Animal physiology',
  'Anthropology',
  'Applied mathematics',
  'Applied Mechanics',
  'Applied physics',
  'Aptitude',
  'Arabic',
  'Arithematic',
  'Art',
  'Art & Craft',
  'Art & Culture',
  'Artificial Intelligence',
  'Assamese',
  'Astrology',
  'Astronomy',
  'Audit',
  'Autocad',
  'Automobile',
  'Ayurveda',
  'Bangla',
  'Banking',
  'Bengali',
  'Bharatnatyam',
  'Bible',
  'Biochemistry',
  'Biography',
  'Biology',
  'Biotechnology',
  'Botany',
  'Building construction',
  'Building materials',
  'Bureau of Energy Efficiency (BEE)',
  'Business',
  'Business Communication',
  'Business Economics',
  'Business Environment',
  'Business Law',
  'Business Management',
  'Business relationship management (BRM)',
  'Business statistics',
  'Business Study',
  'C',
  'C++',
  'Calculus',
  'Campany Law',
  'Chemistry',
  'Chess',
  'Child Development',
  'Child Health Nursing',
  'Child poems',
  'Child Psychology',
  'Circuit theory',
  'Civics',
  'Cloud Computing',
  'Coding',
  'Commerce',
  'Communication',
  'Communication skills',
  'Community Health nursing',
  'Competitive',
  'Complex analysis',
  'Computer',
  'Computer Application',
  'Computer Fundamental',
  'Computer Graphics',
  'Computer Hardware',
  'Computer network',
  'Computer Science',
  'Constitution',
  'Constitution of india',
  'Constitutional Law',
  'Control system',
  'Conversation',
  'Cooking',
  'Corporate Accounting',
  'Cost Accounting',
  'Costing',
  'Creative School',
  'Crop production',
  'Current Affairs',
  'Cyber Security',
  'Dance',
  'Data science',
  'Data Security Standard (DSS)',
  'Data Structure',
  'Database managment system (DBMS)',
  'DE',
  'Defence',
  'Design',
  'Design of machine elements',
  'Digital Electronics',
  'Digital Marketing',
  'Diploma in Advance Accounting (DAA)',
  'Direct Tax',
  'DME',
  'Domestic Data Entry Operator (DDEO)',
  'Drama',
  'Drawing and painting',
  'DSA',
  'Ecology',
  'Economics',
  'Economy',
  'Electrical',
  'Electrical Engineering (EE)',
  'Electrical Machine',
  'Electrical theory',
  'Electrician',
  'Electrician Theory',
  'Electronic',
  'Electronic devices and circuits (EDC)',
  'Emergency Medicine (EM)',
  'Enbedded system',
  'Energy Conservation',
  'Engineering',
  'Engineering Drawing',
  'Engineering Graphics',
  'Engineering maths',
  'Engineering Mechanics',
  'Engineering physics',
  'English',
  'English Grammar',
  'English Language',
  'English Literature',
  'English Shorthand',
  'English Speaking',
  'Enterprise information management (EIM)',
  'Entomology',
  'Entrepreneurship',
  'Environment',
  'Environmental Studies (EVS)',
  'Ethics',
  'Evidence',
  'Fashion designing',
  'Finance',
  'Financial Accounting',
  'Financial Management',
  'Fine Arts',
  'Fitness',
  'Fitter theory',
  'Fluid Mechanics',
  'Food production',
  'French',
  'Fun',
  'Fundamental',
  'General Awareness',
  'General Competition',
  'General Discussion',
  'General Knowledge',
  'General Science',
  'General Studies',
  'Genetics',
  'Geography',
  'Geology',
  'Geometry',
  'Geotechnical Engineering',
  'German',
  'Grammar',
  'Grpahic design',
  'GST',
  'Guitar',
  'Gujrati',
  'Hacking',
  'Handwriting',
  'Health',
  'Healthcare',
  'Heat Transfer',
  'Highway Engineering',
  'Hindi',
  'Hindi Grammar',
  'Hindi Language',
  'Hindi Literature',
  'Hindi Shorthand',
  'Hindu law',
  'History',
  'Home Science',
  'Horticulture',
  'HR',
  'HTML',
  'Humanities',
  'Hydraulics',
  'IELTS',
  'Immunology',
  'Income Tax',
  'Indian Constitution',
  'Indian Geography',
  'Indian Penal Code (IPC)',
  'Indirect Tax',
  'Informatics Practices',
  'Information and Communication Technology (ICT)',
  'Information Protocol',
  'Information Technology',
  'Inorganic Chemistry',
  'Insurance',
  'International Relations',
  'Internet Of Things (IOT)',
  'Irrigation',
  'Islamic',
  'Islamic studies',
  'IT',
  'Japanese',
  'Java',
  'Javascript',
  'Journalism',
  'Juriprudence',
  'Jyotishi',
  'Kannada',
  'Karate',
  'Kashmiri',
  'Kathak',
  'Keyboard',
  'Laboratory',
  'Language',
  'Law',
  'Law of contract',
  'Legal studies',
  'Library and Information Science (LIS)',
  'Library science',
  'LIC',
  'Life Science',
  'Life Skills',
  'Linux',
  'Literature',
  'Machine Design',
  'Machine Drawing',
  'Machine Learning',
  'Macro economics',
  'Malayalam',
  'malyalam',
  'Management',
  'Management Accounting',
  'Managerial Economics',
  'Manipuri',
  'Marathi',
  'Marketing',
  'Marketing Management',
  'Mass Communication',
  'Material Science',
  'Maths',
  'Mathematics',
  'Matlab',
  'MBBS',
  'Mechanical',
  'Mechanical Engineering',
  'Mechanics',
  'Mechatronics',
  'Medical',
  'Medicinal Chemistry',
  'Medicine',
  'Meditation',
  'Meeting',
  'Mental Ability',
  'Mental health nursing',
  'Micro economics',
  'Microbiology',
  'Microcontroller',
  'Microprocessor',
  'Microsoft Excel',
  'Microsoft Office',
  'Microsoft Word',
  'Mining',
  'Moral education',
  'Moral Science',
  'Motivation',
  'Motivational',
  'MS Excel',
  'Music',
  'Nepali',
  'Network Analysis',
  'Network Maketing',
  'Network theory',
  'Networking',
  'NTPC',
  'Number System',
  'Numerical analysis',
  'Nursing',
  'Nutrition',
  'Obstetrics and gynaecology',
  'Odia',
  'Operating structure',
  'Operating System',
  'Operation Research',
  'Organic Chemistry',
  'Painting',
  'Pathology',
  'Pedagogy',
  'Pediatrics',
  'Personality Development',
  'Pharmaceutical Analysis',
  'Pharmaceutics',
  'Pharmacognosy',
  'Pharmacology',
  'Pharmacy',
  'Philosophy',
  'Phonics',
  'Photography',
  'Photoshop',
  'PHP',
  'Physical Chemistry',
  'Physical Education',
  'Physical Science',
  'Physics',
  'Physiology',
  'Piano',
  'Plant Pathalogy',
  'Poetry',
  'Political Science',
  'Power electronics',
  'Power system',
  'Priniciples of Management',
  'Prinicples of Marketing',
  'Programming',
  'Psychology',
  'Physical training',
  'Public Administration',
  'Public Speaking',
  'Punjabi',
  'Pysiotheraphy',
  'Python',
  'Quantitative Aptitude',
  'Quantum Mechanics',
  'Quran',
  'Relationa Database managment system (RDBMS)',
  'Reasoning',
  'Research',
  'Research methodology',
  'Retail mangement',
  'Rhymes',
  'Robotics',
  'Sales',
  'Sanskrit',
  'Science',
  'Share market',
  'Shorthand',
  'Signals and Systems',
  'Singing',
  'Skill developement',
  'Social Science',
  'Sociology',
  'Soft skills',
  'Software enginneering',
  'Software Testing',
  'Soil Mechanics',
  'Soil Science',
  'Spanish',
  'Spoken English',
  'Sports',
  'SQL',
  'Statistics',
  'Stenography',
  'Stock Market',
  'Strategic management',
  'Strength of material',
  'Strength of Materials',
  'Structual Design',
  'Surgery',
  'Surgical Nursing',
  'Survey',
  'Tabla',
  'Tajweed',
  'Tally',
  'Tamil',
  'Tax',
  'Teaching',
  'Technical',
  'Technical Analysis',
  'Telegu',
  'Theory',
  'Theory of machine',
  'Thermal engineering',
  'Thermodynamics',
  'Tibetan',
  'Trade Theory',
  'Trading',
  'Train the Trainer (TTT)',
  'Trigonometry',
  'UEEE',
  'Urdu',
  'Value Education',
  'Vedic Maths',
  'Very large scale integration (VLSI)',
  'Vocabulary',
  'Vocal',
  'Web Design',
  'Web developement',
  'Web Technology',
  'Welder',
  'Wireless communication system (WCS)',
  'Wireman',
  'Wordpress',
  'Workshop calculation',
  'Writing',
  'Yoga',
  'Youtube',
  'Zoology',
  'OTHERS',
]

export const affiliatedBoardOptions = [
  {key: 'Select', value: 'Select'},
  {key: 'CBSE', value: 'CBSE'},
  {key: 'ICSE', value: 'ICSE'},
  {key: 'State Board', value: 'State Board'},
  {key: 'Others', value: 'Others'},
]

export const departmentOptions = [
  {
    num: 0,
    code: 'SEN',
    checked: false,
    title: 'Higher/Senior Secondary (11th & 12th class)',
  },
  {
    num: 1,
    code: 'HIG',
    checked: false,
    title: 'Secondary (9th & 10th class)',
  },
  {
    num: 2,
    code: 'SEC',
    checked: false,
    title: 'Middle (6th - 8th class)',
  },
  {num: 3, code: 'PRI', checked: false, title: 'Primary (1st - 5th class)'},
  {
    num: 4,
    code: 'PRE',
    checked: false,
    title: 'Pre - Primary (UKG, LKG, Nursery)',
  },
]

export const languageOptions = [
  {key: 'Select', value: 'Select'},
  {key: 'en-US', value: 'English'},
  {key: 'hi', value: 'Hindi'},
  {key: 'ind', value: 'Indonesian'},
]

export const dynamicStudentSampleData = [
  {
    _id: '1234567890',
    admission_timestamp: '1586284200',
    blood_group: 'A+, A-, B+, B-, AB+, AB-, O+, O-',
    bpl_student: 'Yes, No',
    c_city: 'Bengaluru',
    c_country: 'India',
    c_line_1: '5th Floor, North Wing, SJR The Hub,',
    c_line_2: 'Sarjapur Main Rd',
    c_pin: '560103',
    c_state: 'Karnataka',
    category: 'GEN, GEN-EWS, OBC, OBC-CL, OBC-NCL, SC, ST, Foreigner, Others',
    child_immunisation: 'Complete, Partial, None',
    covid_vaccination: 'Single Dose, Both Doses, None',
    date_of_birth: '1586284200',
    date_of_admission: 'DD/MM/YYYY',
    email: 'rahul.kumar@tfi.com',
    emergency_contact: '91-9370075769',
    enrollment_number: 'TFI/22/1234',
    father_contact_number: '91-9876XXXXXX',
    father_designation: 'CMO',
    father_email: 'aman.sharma@tfi.com',
    father_income: '50XXXX',
    father_name: 'Aman Sharma',
    father_occupation: 'Doctor',
    father_qualification: 'MBBS',
    father_work_contact: '91-9876XXXXXX',
    father_work_organization: 'Government Hospital',
    gender: 'Male, Female, Others',
    grade: '100',
    guardian_designation: 'CMO',
    guardian_email: 'thomas.john@tfi.com',
    guardian_income: '50XXXX',
    guardian_name: 'Thomas John',
    guardian_number: '91-9876XXXXXX',
    guardian_occupation: 'Doctor',
    guardian_qualification: 'MBBS',
    guardian_relationship: 'Uncle',
    guardian_work_contact: '91-9876XXXXXX',
    guardian_work_organization: 'Government Hospital',
    last_name: 'Sharma',
    middle_name: 'Kumar',
    mother_contact_number: '91-9876XXXXXX',
    mother_designation: 'CMO',
    mother_email: 'neha.sharma@tfi.com',
    mother_income: '50XXXX',
    mother_name: 'Neha Sharma',
    mother_occupation: 'Doctor',
    mother_qualification: 'MBBS',
    mother_tongue: 'Marathi',
    mother_work_contact: '91-9876XXXXXX',
    mother_work_organization: 'Government Hospital',
    name: 'Rahul',
    nationality: 'Indian',
    p_city: 'Bengaluru',
    p_country: 'India',
    p_line_1: '5th Floor, North Wing, SJR The Hub,',
    p_line_2: 'Sarjapur Main Rd',
    p_pin: '560103',
    p_state: 'Karnataka',
    phone_number: '91-9876XXXXXX',
    pwd: 'Yes, No',
    pwd_type: 'Colour Blind',
    religion: 'Hindu, Muslim, Christian, Sikh, Buddhist, Jain, Other',
    right_to_education: 'Yes, No',
    second_language: 'English',
    section: 'B',
    standard: '11',
    single_parent_child: 'Yes, No',
    single_parent: 'Father, Mother',
    sponsered_student: 'Yes, No',
  },
]

export const dynamicStaffSampleData = [
  {
    aadhar_number: '9876XXXXXXXX',
    blood_group: 'A+, A-, B+, B-, AB+, AB-, O+, O-',
    category: 'GEN, GEN-EWS, OBC, OBC-CL, OBC-NCL, SC, ST, Foreigner, Others',
    c_city: 'Bengaluru',
    c_country: 'India',
    c_line_1: '5th Floor, North Wing, SJR The Hub,',
    c_line_2: 'Sarjapur Main Rd',
    c_pin: '560103',
    c_state: 'Karnataka',
    date_of_appointment: '1568712147',
    date_of_birth: '413457747',
    designation: 'HOD',
    email: 'rahul.kumar@teachmint.com',
    employee_id: 'TFI/22/1235',
    employment_type: 'full-time',
    experience: '5',
    gender: 'Male, Female, Other',
    highest_qualification: 'BA',
    job_profile: 'Primary Teacher',
    last_date_of_joining: '',
    last_date_of_relieving: '',
    last_institute_name: '',
    last_job_title: '',
    last_location: '',
    last_name: 'Sharma',
    middle_name: 'Kumar',
    name: 'Rahul',
    pan_number: 'MNOPPXXXXD',
    p_city: 'Bengaluru',
    p_country: 'India',
    p_line_1: '5th Floor, North Wing, SJR The Hub,',
    p_line_2: 'Sarjapur Main Rd',
    p_pin: '560103',
    p_state: 'Karnataka',
    phone_number: '91-985XXXXXXX',
    religion: 'Hindu, Muslim, Christian, Sikh, Buddhist, Jain, Other',
    staff_emergency_phone_number: '91-94810XXXXX',
  },
]
