// Hierarchy Nodes
export const NODE_NON = 'NON'
export const NODE_INSTITUTE = 'INSTITUTE'
export const NODE_SESSION = 'SESSION'
export const NODE_DEPARTMENT = 'DEPARTMENT'
export const NODE_CLASS = 'STANDARD'
export const NODE_SECTION = 'SECTION'
export const NODE_SUBJECT = 'SUBJECT'
export const NODE_CLASSROOM = 'CLS'
export const NODE_SCHOOL_SYSTEM_OVERVIEW = 'SSO'
export const NODE_SCHOOL_ARCHIVE = 'SAE'
export const NODE_UNASSIGNED_CLASSES = 'UAC'
export const NODE_ADD_SEC = 'ADD_SEC'

// Hierarchy Nodes Types
export const NODE_TYPE_HIG = 'HIG'
export const NODE_TYPE_SEN = 'SEN'
export const NODE_TYPE_SEC = 'SEC'
export const NODE_TYPE_PRI = 'PRI'
export const NODE_TYPE_PRE = 'PRE'

// Screens
export const SCN_SCHOOL_SETUP = 'SCN_SCHOOL_SETUP'
export const SCN_CLASSROOM_PAGE = 'SCN_CLASSROOM_PAGE'
export const SCN_TEACHER_DIRECTORY = 'SCN_TEACHER_DIRECTORY'
export const SCN_STUDENT_DIRECTORY = 'SCN_STUDENT_DIRECTORY'
export const SCN_SECTION = 'SCN_SECTION'
export const SCN_ARCHIVED = 'SCN_ARCHIVED'
export const SCN_UNASSIGNED = 'SCN_UNASSIGNED'
export const SCN_SLI_TEACHER = 'SCN_SLI_TEACHER'
export const SCN_SLI_CLASS_TEACHER = 'SCN_SLI_CLASS_TEACHER'
export const SCN_SLI_CO_TEACHER = 'SCN_SLI_CO_TEACHER'
export const SCN_SLI_REMOVE_CO_TEACHER = 'SCN_SLI_REMOVE_CO_TEACHER'
export const SCN_SLI_ADD_CO_TEACHER = 'SCN_SLI_ADD_CO_TEACHER'
export const SCN_SLI_ADD_TEACHER = 'SCN_SLI_ADD_TEACHER'
export const SCN_SLI_TEACHER_DIRECTORY = 'SCN_SLI_TEACHER_DIRECTORY'
export const SCN_SLI_STUDENT = 'SCN_SLI_STUDENT'
export const SCN_SLI_EDIT_SEC_NAME = 'SCN_SLI_EDIT_SEC_NAME'
export const SCN_SLI_SEC_ADD_SUBJECT = 'SCN_SLI_SEC_ADD_SUBJECT'
export const SCN_SLI_SEC_MOVE_STUDENT = 'SCN_SLI_SEC_MOVE_STUDENT'
export const SCN_SLI_OPTIONAL_STUDENT = 'SCN_SLI_OPTIONAL_STUDENT'
export const SCN_SLI_SECTION_ATTENDANCE = 'SCN_SLI_SECTION_ATTENDANCE'

export const SCN_SLI_ADD_DIR_TEACHER = 'SCN_SLI_ADD_DIR_TEACHER'
export const SCN_SLI_TEACHER_DETAIL = 'SCN_SLI_TEACHER_DETAIL'

export const SCN_SLI_ADD_DIR_STUDENT = 'SCN_SLI_ADD_DIR_STUDENT'
export const SCN_SLI_STUDENT_DETAIL = 'SCN_SLI_STUDENT_DETAIL'

export const SCN_SLI_ADD_DIR_CLASSROOM = 'SCN_SLI_ADD_DIR_CLASSROOM'

export const SCN_SLI_EDIT_CLASSROOM_NAME = 'SCN_SLI_EDIT_CLASSROOM_NAME'
export const SCN_SLI_STUDENT_UPDATE_CSV = 'SCN_SLI_STUDENT_UPDATE_CSV'

/*
 * Actions
 */

export const ACT_SUB_SEARCH_SELECT = 'ACT_SUB_SEARCH_SELECT'

// Section Details Page Actions
export const ACT_SEC_EDIT_SUBJECT_TYPE = 'ACT_SEC_EDIT_SUBJECT_TYPE'
export const ACT_SEC_ASSIGN_SUB_TEACHER = 'ACT_SEC_ASSIGN_SUB_TEACHER'
export const ACT_SEC_CLASS_ASSIGN_TEACHER = 'ACT_SEC_CLASS_ASSIGN_TEACHER'
export const ACT_SEC_CLASS_SUB_ASSIGN_TEACHER =
  'ACT_SEC_CLASS_SUB_ASSIGN_TEACHER'
export const ACT_SEC_DELETE_SEC = 'ACT_SEC_DELETE_SEC'
export const ACT_SEC_CLASS_ASSIGN_STUDENTS = 'ACT_SEC_CLASS_ASSIGN_STUDENTS'
export const ACT_SEC_ADD_SUBJECT = 'ACT_SEC_ADD_SUBJECT'
export const ACT_SEC_EDIT_NAME = 'ACT_SEC_EDIT_NAME'
export const ACT_SEC_REMOVE_SUB_TEACHER = 'ACT_SEC_REMOVE_SUB_TEACHER'
export const ACT_SEC_VIEW_CO_TEACHER = 'ACT_SEC_VIEW_CO_TEACHER'
export const ACT_SEC_ADD_CO_TEACHER = 'ACT_SEC_ADD_CO_TEACHER'
export const ACT_SEC_REMOVE_CO_TEACHER = 'ACT_SEC_REMOVE_CO_TEACHER'
export const ACT_SEC_REASSIGN_SUB_TEACHER = 'ACT_SEC_REASSIGN_SUB_TEACHER'
export const ACT_SEC_REMOVE_CLASS_TEACHER = 'ACT_SEC_REMOVE_CLASS_TEACHER'
export const ACT_SEC_REASSIGN_CLASS_TEACHER = 'ACT_SEC_REASSIGN_CLASS_TEACHER'
export const ACT_SEC_EDIT_SUB_NAME = 'ACT_SEC_EDIT_SUB_NAME'
export const ACT_SEC_REMOVE_SUB = 'ACT_SEC_REMOVE_SUB'
export const ACT_SEC_MOVE_STUDENT = 'ACT_SEC_MOVE_STUDENT'
export const ACT_SEC_OPTIONAL_SUB_ASSIGN_STUDENT =
  'ACT_SEC_OPTIONAL_SUB_ASSIGN_STUDENT'
export const ACT_SEC_MANAGE_ATTENDANCE = 'ACT_SEC_MANAGE_ATTENDANCE'

// Teacher Directory Actions
export const ACT_TCH_DIR_ADD_TEACHER = 'ACT_TCH_DIR_ADD_TEACHER'
export const ACT_TCH_DIR_TCH_DETAIL = 'ACT_TCH_DIR_TCH_DETAIL'

// Student Directory Actions
export const ACT_STD_DIR_ADD_STUDENT = 'ACT_STD_DIR_ADD_STUDENT'
export const ACT_STD_DIR_STUDENT_DETAIL = 'ACT_STD_DIR_STUDENT_DETAIL'
export const ACT_STD_MOVE_STUDENT = 'ACT_STD_MOVE_STUDENT'
export const ACT_STD_ASSIGN_STUDENT = 'ACT_STD_ASSIGN_STUDENT'

// Classroom Directory Actions
export const ACT_CLS_DIR_ADD_CLASSROOM = 'ACT_CLS_DIR_ADD_CLASSROOM'

// Uncategorized Classroom Actions
export const ACT_UNC_CLS_EDIT_CLASS_NAME = 'ACT_UNC_CLS_EDIT_CLASS_NAME'
export const ACT_UNC_CLS_ADD_STUDENTS = 'ACT_UNC_CLS_ADD_STUDENTS'
export const ACT_UNC_CLS_VIEW_STUDENTS = 'ACT_UNC_CLS_VIEW_STUDENTS'
export const ACT_UNC_CLS_REPLACE_TEACHER = 'ACT_UNC_CLS_REPLACE_TEACHER'
export const ACT_UNC_CLS_REMOVE_TEACHER = 'ACT_UNC_CLS_REMOVE_TEACHER'
export const ACT_UNC_CLS_DELETE_CLASS = 'ACT_UNC_CLS_DELETE_CLASS'
