export const ExamPlannerActions = {
  FETCH_EXISTING_EXAMS: 'FETCH_EXISTING_EXAMS',
  SET_EXISTING_EXAMS: 'SET_EXISTING_EXAMS',
  POST_EXSITING_EXAM_SCHEDULE: 'POST_EXSITING_EXAM_SCHEDULE',
  FETCH_SUBJECT_LIST_REQUEST: 'FETCH_SUBJECT_LIST_REQUEST',
  FETCH_SUBJECT_LIST_REQUEST_SUCCESS: 'FETCH_SUBJECT_LIST_REQUEST_SUCCESS',
  FETCH_SUBJECT_WITHOUT_STRUCTURE_LIST_REQUEST:
    'FETCH_SUBJECT_WITHOUT_STRUCTURE_LIST_REQUEST',
}
