export const pgListActionType = {
  FETCH_PG_LIST: 'FETCH_PG_LIST',
  FETCH_PG_LIST_SUCCESS: 'FETCH_PG_LIST_SUCCESS',
  FETCH_PG_LIST_FAILURE: 'FETCH_PG_LIST_FAILURE',

  FETCH_PG_LIST_FIELDS: 'FETCH_PG_LIST_FIELDS',
  FETCH_PG_LIST_FIELDS_SUCCESS: 'FETCH_PG_LIST_FIELDS_SUCCESS',
  FETCH_PG_LIST_FIELDS_FAILURE: 'FETCH_PG_LIST_FIELDS_FAILURE',

  UPDATE_PG_DATA_REQUEST: 'UPDATE_PG_DATA_REQUEST',
  UPDATE_PG_DATA_SUCCESS: 'UPDATE_PG_DATA_SUCCESS',
  UPDATE_PG_DATA_FAILURE: 'UPDATE_PG_DATA_FAILURE',
}
