export const TESTDATA_MUTATE = 'TESTDATA_MUTATE'
export const TESTDATA_MUTATE_API = 'TESTDATA_MUTATE_API'

export const GET_LEAVE_BALANCE = 'GET_LEAVE_BALANCE'
export const GET_LEAVE_BALANCE_SUCCESS = 'GET_LEAVE_BALANCE_SUCCESS'
export const GET_LEAVE_BALANCE_FAILURE = 'GET_LEAVE_BALANCE_FAILURE'
export const SUBMIT_SESSION_LEAVE_BALANCE = 'SUBMIT_SESSION_LEAVE_BALANCE'
export const SUBMIT_SESSION_LEAVE_BALANCE_SUCCESS =
  'SUBMIT_SESSION_LEAVE_BALANCE_SUCCESS'
export const SUBMIT_SESSION_LEAVE_BALANCE_FAILURE =
  'SUBMIT_SESSION_LEAVE_BALANCE_FAILURE'
export const RESET_SESSION_LEAVE_BALANCE_RESPONSE =
  'RESET_SESSION_LEAVE_BALANCE_RESPONSE'

export const GET_PENDING_LEAVES = 'GET_PENDING_LEAVES'
export const GET_PENDING_LEAVES_SUCCESS = 'GET_PENDING_LEAVES_SUCCESS'
export const GET_PENDING_LEAVES_FAILURE = 'GET_PENDING_LEAVES_FAILURE'
export const RESET_PENDING_LEAVES = 'RESET_PENDING_LEAVES'

export const GET_PAST_LEAVES = 'GET_PAST_LEAVES'
export const GET_PAST_LEAVES_SUCCESS = 'GET_PAST_LEAVES_SUCCESS'
export const GET_PAST_LEAVES_FAILURE = 'GET_PAST_LEAVES_FAILURE'
export const RESET_PAST_LEAVES = 'RESET_PAST_LEAVES'

export const SEARCH_STAFF = 'SEARCH_STAFF'

export const SHOW_APPROVE_MODAL = 'SHOW_APPROVE_MODAL'
export const SHOW_REJECT_MODAL = 'SHOW_REJECT_MODAL'
export const SHOW_CANCEL_MODAL = 'SHOW_CANCEL_MODAL'

export const HIDE_APPROVE_MODAL = 'HIDE_APPROVE_MODAL'
export const HIDE_REJECT_MODAL = 'HIDE_REJECT_MODAL'
export const HIDE_CANCEL_MODAL = 'HIDE_CANCEL_MODAL'

export const APPROVE_LEAVE = 'APPROVE_LEAVE'
export const APPROVE_LEAVE_SUCCESS = 'APPROVE_LEAVE_SUCCESS'
export const APPROVE_LEAVE_FAILURE = 'APPROVE_LEAVE_FAILURE'
export const REJECT_LEAVE = 'REJECT_LEAVE'
export const REJECT_LEAVE_SUCCESS = 'REJECT_LEAVE_SUCCESS'
export const REJECT_LEAVE_FAILURE = 'REJECT_LEAVE_FAILURE'

export const SHOW_STAFF_HISTORY_MODAL = 'SHOW_STAFF_HISTORY_MODAL'
export const HIDE_STAFF_HISTORY_MODAL = 'HIDE_STAFF_HISTORY_MODAL'

export const GET_STAFF_HISTORY = 'GET_STAFF_HISTORY'
export const GET_STAFF_HISTORY_SUCCESS = 'GET_STAFF_HISTORY_SUCCESS'
export const GET_STAFF_HISTORY_FAILURE = 'GET_STAFF_HISTORY_FAILURE'

export const SHOW_LEAVE_DETAILS_MODAL = 'SHOW_LEAVE_DETAILS_MODAL'
export const HIDE_LEAVE_DETAILS_MODAL = 'HIDE_LEAVE_DETAILS_MODAL'

export const SHOW_ADD_LEAVE_POPUP = 'SHOW_ADD_LEAVE_POPUP'
export const HIDE_ADD_LEAVE_POPUP = 'HIDE_ADD_LEAVE_POPUP'

export const SHOW_REQUEST_LEAVE_POPUP = 'SHOW_REQUEST_LEAVE_POPUP'
export const HIDE_REQUEST_LEAVE_POPUP = 'HIDE_REQUEST_LEAVE_POPUP'

export const SHOW_EDIT_LEAVE_POPUP = 'SHOW_EDIT_LEAVE_POPUP'
export const HIDE_EDIT_LEAVE_POPUP = 'HIDE_EDIT_LEAVE_POPUP'

export const GET_STAFF_LIST = 'GET_STAFF_LIST'
export const GET_STAFF_LIST_SUCCESS = 'GET_STAFF_LIST_SUCCESS'
export const GET_STAFF_LEAVE_BALANCE = 'GET_STAFF_LEAVE_BALANCE'
export const GET_STAFF_LEAVE_BALANCE_SUCCESS = 'GET_STAFF_LEAVE_BALANCE_SUCCESS'
export const GET_STAFF_SELECTED_LEAVE_COUNT = 'GET_STAFF_SELECTED_LEAVE_COUNT'
export const GET_STAFF_SELECTED_LEAVE_COUNT_SUCCESS =
  'GET_STAFF_SELECTED_LEAVE_COUNT_SUCCESS'
export const GET_STAFF_SELECTED_LEAVE_COUNT_FAILURE =
  'GET_STAFF_SELECTED_LEAVE_COUNT_FAILURE'
export const CREATE_LEAVE = 'CREATE_LEAVE'
export const CREATE_LEAVE_SUCCESS = 'CREATE_LEAVE_SUCCESS'
export const CREATE_LEAVE_FAILURE = 'CREATE_LEAVE_FAILURE'

export const REQUEST_LEAVE = 'REQUEST_LEAVE'
export const REQUEST_LEAVE_SUCCESS = 'REQUEST_LEAVE_SUCCESS'
export const REQUEST_LEAVE_FAILURE = 'REQUEST_LEAVE_FAILURE'

export const EDIT_LEAVE = 'EDIT_LEAVE'
export const EDIT_LEAVE_SUCCESS = 'EDIT_LEAVE_SUCCESS'
export const EDIT_LEAVE_FAILURE = 'EDIT_LEAVE_FAILURE'

export const CANCEL_LEAVE = 'CANCEL_LEAVE'
export const CANCEL_LEAVE_SUCCESS = 'CANCEL_LEAVE_SUCCESS'
export const CANCEL_LEAVE_FAILURE = 'CANCEL_LEAVE_FAILURE'

export const CANCEL_LEAVE_BY_STAFF = 'CANCEL_LEAVE_BY_STAFF'
export const CANCEL_LEAVE_BY_STAFF_SUCCESS = 'CANCEL_LEAVE_BY_STAFF_SUCCESS'
export const CANCEL_LEAVE_BY_STAFF_FAILURE = 'CANCEL_LEAVE_BY_STAFF_FAILURE'

export const GET_TOTAL_LEAVE_STATS = 'GET_TOTAL_LEAVE_STATS'
export const GET_TOTAL_LEAVE_STATS_SUCCESS = 'GET_TOTAL_LEAVE_STATS_SUCCESS'

export const RESET_DATA = 'RESET_DATA'

export const SHOW_LEAVE_BALANCE_UPDATE_FORM = 'SHOW_LEAVE_BALANCE_UPDATE_FORM'
export const HIDE_LEAVE_BALANCE_UPDATE_FORM = 'HIDE_LEAVE_BALANCE_UPDATE_FORM'

export const GET_CURRENT_USER_LEAVE_STATS = 'GET_CURRENT_USER_LEAVE_STATS'
export const GET_CURRENT_USER_LEAVE_STATS_SUCCESS =
  'GET_CURRENT_USER_LEAVE_STATS_SUCCESS'

export const DOWNLOAD_LEAVE_BALANCE_REPORT = 'DOWNLOAD_LEAVE_BALANCE_REPORT'
export const RESET_LEAVE_BALANCE_REPORT = 'RESET_LEAVE_BALANCE_REPORT'
export const DOWNLOAD_LEAVE_BALANCE_REPORT_SUCCESS =
  'DOWNLOAD_LEAVE_BALANCE_REPORT_SUCCESS'

export const GET_STAFF_UPCOMING_LEAVES = 'GET_STAFF_UPCOMING_LEAVES'
export const GET_STAFF_UPCOMING_LEAVES_SUCCESS =
  'GET_STAFF_UPCOMING_LEAVES_SUCCESS'
export const GET_STAFF_UPCOMING_LEAVES_FAILURE =
  'GET_STAFF_UPCOMING_LEAVES_FAILURE'
export const REMOVE_LEAVE_FROM_UPCOMING_LEAVE_LIST =
  'REMOVE_LEAVE_FROM_UPCOMING_LEAVE_LIST'
