const events = {
  MULTI_INSTITUTE_REPORT_DOWNLOADED_TFI:
    'MULTI_INSTITUTE_REPORT_DOWNLOADED_TFI',
  MULTI_INSTITUTE_HOME_TAB_SWITCH_TFI: 'MULTI_INSTITUTE_HOME_TAB_SWITCH_TFI',
}

export default events
