const feeCollectionActionTypes = {
  FETCH_FEE_STATS_REQUESTED: 'FETCH_FEE_STATS_REQUESTED',
  FETCH_FEE_STATS_SUCCEEDED: 'FETCH_FEE_STATS_SUCCEEDED',
  FETCH_FEE_STATS_FAILED: 'FETCH_FEE_STATS_FAILED',
  SEARCH_RESULTS_REQUESTED: 'SEARCH_RESULTS_REQUESTED',
  SEARCH_RESULTS_SUCCEEDED: 'SEARCH_RESULTS_SUCCEEDED',
  SEARCH_RESULTS_FAILED: 'SEARCH_RESULTS_FAILED',
  STUDENT_DUES_REQUESTED: 'STUDENT_DUES_REQUESTED',
  STUDENT_DUES_SUCCEEDED: 'STUDENT_DUES_SUCCEEDED',
  STUDENT_DUES_FAILED: 'STUDENT_DUES_FAILED',
  DOWNLOAD_DEMAND_LETTER_REQUESTED: 'DOWNLOAD_DEMAND_LETTER_REQUESTED',
  DOWNLOAD_DEMAND_LETTER_SUCCEEDED: 'DOWNLOAD_DEMAND_LETTER_SUCCEEDED',
  DOWNLOAD_DEMAND_LETTER_FAILED: 'DOWNLOAD_DEMAND_LETTER_FAILED',
  FEE_REMINDER_REQUESTED: 'FEE_REMINDER_REQUESTED',
  FEE_REMINDER_SUCCEEDED: 'FEE_REMINDER_SUCCEEDED',
  FEE_REMINDER_FAILED: 'FEE_REMINDER_FAILED',
  SET_STUDENT_DUES_FILTERS: 'SET_STUDENT_DUES_FILTERS',
  STUDENT_DUES_TEXT_FILTER: 'STUDENT_DUES_TEXT_FILTER',
  FEE_HISTORY_REQUESTED: 'FEE_HISTORY_REQUESTED',
  FEE_HISTORY_SUCCEEDED: 'FEE_HISTORY_SUCCEEDED',
  FEE_HISTORY_FAILED: 'FEE_HISTORY_FAILED',
  SET_SLIDER_SCREEN: 'SET_SLIDER_SCREEN',
  SET_SELECTED_STUDENT: 'SET_SELECTED_STUDENT',
  COLLECT_FEES_REQUESTED: 'COLLECT_FEES_REQUESTED',
  COLLECT_FEES_SUCCEEDED: 'COLLECT_FEES_SUCCEEDED',
  COLLECT_FEES_FAILED: 'COLLECT_FEES_FAILED',
  SET_COLLECT_FEES_DURATION: 'SET_COLLECT_FEES_DURATION',
  SUBMIT_FEES_REQUESTED: 'SUBMIT_FEES_REQUESTED',
  SUBMIT_FEES_SUCCEEDED: 'SUBMIT_FEES_SUCCEEDED',
  SUBMIT_FEES_FAILED: 'SUBMIT_FEES_FAILED',
  PAYMENT_GATEWAY_SETUP_REQUESTED: 'PAYMENT_GATEWAY_SETUP_REQUESTED',
  PAYMENT_GATEWAY_SETUP_SUCCEEDED: 'PAYMENT_GATEWAY_SETUP_SUCCEEDED',
  PAYMENT_GATEWAY_SETUP_FAILED: 'PAYMENT_GATEWAY_SETUP_FAILED',
  REDIRECT_TO_HISTORY_FEE_TAB: 'REDIRECT_TO_HISTORY_FEE_TAB',
  MULTIPLE_PAYMENT_GATEWAY_CREATE_REQUEST:
    'MULTIPLE_PAYMENT_GATEWAY_CREATE_REQUEST',
  MULTIPLE_PAYMENT_GATEWAY_CREATE_SUCCESS:
    'MULTIPLE_PAYMENT_GATEWAY_CREATE_SUCCESS',
  MULTIPLE_PAYMENT_GATEWAY_CREATE_FAILED:
    'MULTIPLE_PAYMENT_GATEWAY_CREATE_FAILED',
  REDIRECT_TO_PAYMENTGATEWAY_SCREEN: 'REDIRECT_TO_PAYMENTGATEWAY_SCREEN',
  FETCH_FEE_SETTINGS_UPDATE: 'FETCH_FEE_SETTINGS_UPDATE',
  FETCH_FEE_SETTINGS_SUCCEEDED: 'FETCH_FEE_SETTINGS_SUCCEEDED',
  FETCH_FEE_SETTINGS_FAIL: 'FETCH_FEE_SETTINGS_FAIL',
  FETCH_STUDENT_IDS_FOR_FEE_REMINDER_REQUESTED:
    'FETCH_STUDENT_IDS_FOR_FEE_REMINDER_REQUESTED',
  SET_STUDENT_IDS_FOR_FEE_REMINDER: 'SET_STUDENT_IDS_FOR_FEE_REMINDER',
  SET_RECORD_PAYMENT_DETAILS: 'SET_RECORD_PAYMENT_DETAILS',
  FETCH_FEE_RECEIPT_URL: 'FETCH_FEE_RECEIPT_URL',
  FEE_RECEIPT_DOWNLOAD_AND_PRINT_REQUEST:
    'FEE_RECEIPT_DOWNLOAD_AND_PRINT_REQUEST',
  SET_IS_TRANSACTION_POPUP_ALREADY_SHOWN:
    'SET_IS_TRANSACTION_POPUP_ALREADY_SHOWN',
  COLLECT_BACKDATED_PAYMENT_REQUEST: 'COLLECT_BACKDATED_PAYMENT_REQUEST',
  SET_COLLECT_BACKDATED_PAYMENT_STATES: 'SET_COLLECT_BACKDATED_PAYMENT_STATES',
  COLLECT_BACK_DATED_PAYMENT_TASK_REQUEST:
    'COLLECT_BACK_DATED_PAYMENT_TASK_REQUEST',
  COLLECT_BACK_DATED_PAYMENT_TASK_ACKNOWLEDGE_REQUEST:
    'COLLECT_BACK_DATED_PAYMENT_TASK_ACKNOWLEDGE_REQUEST',
}

export default feeCollectionActionTypes
