const feeSettingsActionTypes = {
  UPDATE_DIGITAL_SIGNATURE: 'UPDATE_DIGITAL_SIGNATURE',
  REMOVE_DIGITAL_SIGNATURE_IMAGE: 'REMOVE_DIGITAL_SIGNATURE_IMAGE',
  UPDATE_DIGITAL_SIGNATURE_SUCCEEDED: 'UPDATE_DIGITAL_SIGNATURE_SUCCEEDED',
  UPDATE_DIGITAL_SIGNATURE_FAIL: 'UPDATE_DIGITAL_SIGNATURE_FAIL',
}

export default feeSettingsActionTypes
