const feeTransactionActionTypes = {
  // This for Transaction list
  FETCH_FEE_TRANSACTION_LIST_STATS_REQUESTED:
    'FETCH_FEE_TRANSACTION_LIST_STATS_REQUESTED',
  FETCH_FEE_TRANSACTION_LIST_SUCCEEDED: 'FETCH_FEE_TRANSACTION_LIST_SUCCEEDED',
  FETCH_FEE_TRANSACTION_LIST_STATS_FAILED:
    'FETCH_FEE_TRANSACTION_LIST_STATS_FAILED',
  FETACH_APPLY_FILTER_DATA: 'FETACH_APPLY_FILTER_DATA',

  FETCH_CHEQUE_TRANSACTION_LIST_STATS_REQUESTED:
    'FETCH_CHEQUE_TRANSACTION_LIST_STATS_REQUESTED',
  FETCH_CHEQUE_TRANSACTION_LIST_SUCCEEDED:
    'FETCH_CHEQUE_TRANSACTION_LIST_SUCCEEDED',
  FETCH_CHEQUE_TRANSACTION_LIST_STATS_FAILED:
    'FETCH_CHEQUE_TRANSACTION_LIST_STATS_FAILED',
  FETACH_CHEQUE_TRANSACTION_APPLY_FILTER_DATA:
    'FETACH_CHEQUE_TRANSACTION_APPLY_FILTER_DATA',

  FETCH_FEE_TRANSACTION_SEARCH_TEXT_FILTER:
    'FETCH_FEE_TRANSACTION_SEARCH_TEXT_FILTER',

  // This for Transaction timeline status
  FETCH_FEE_TRANSACTION_TIMELINE_REQUESTED:
    'FETCH_FEE_TRANSACTION_TIMELINE_REQUESTED',
  FETCH_FEE_TRANSACTION_TIMELINE_SUCCEEDED:
    'FETCH_FEE_TRANSACTION_TIMELINE_SUCCEEDED',
  FETCH_FEE_TRANSACTION_TIMELINE_FAILED:
    'FETCH_FEE_TRANSACTION_TIMELINE_FAILED',

  // This for Transaction timeline status update
  UPDATE_FEE_TRANSACTION_TIMELINE_STATUS_REQUESTED:
    'UPDATE_FEE_TRANSACTION_TIMELINE_STATUS_REQUESTED',
  UPDATE_FEE_TRANSACTION_TIMELINE_STATUS_SUCCEEDED:
    'UPDATE_FEE_TRANSACTION_TIMELINE_STATUS_SUCCEEDED',
  UPDATE_FEE_TRANSACTION_TIMELINE_STATUS_FAILED:
    'UPDATE_FEE_TRANSACTION_TIMELINE_STATUS_FAILED',

  // Transaction (normal and cancelled) receipt download
  FEE_TRANSACTION_DOWNLOAD_REQUESTED: 'FEE_TRANSACTION_DOWNLOAD_REQUESTED',
  FEE_TRANSACTION_DOWNLOAD_SUCCEEDED: 'FEE_TRANSACTION_DOWNLOAD_SUCCEEDED',
  FEE_TRANSACTION_DOWNLOAD_FAILED: 'FEE_TRANSACTION_DOWNLOAD_FAILED',

  // Delete/Cancel Transaction
  REVOKE_FEE_TRANSACTION_REQUESTED: 'REVOKE_FEE_TRANSACTION_REQUESTED',
  REVOKE_FEE_TRANSACTION_SUCCEEDED: 'REVOKE_FEE_TRANSACTION_SUCCEEDED',
  REVOKE_FEE_TRANSACTION_FAILED: 'REVOKE_FEE_TRANSACTION_FAILED',

  // Delete/Cancel cheque/dd Transaction
  REVOKE_CHEQUE_TRANSACTION_REQUESTED: 'REVOKE_CHEQUE_TRANSACTION_REQUESTED',
  REVOKE_CHEQUE_TRANSACTION_SUCCEEDED: 'REVOKE_CHEQUE_TRANSACTION_SUCCEEDED',
  REVOKE_CHEQUE_TRANSACTION_FAILED: 'REVOKE_CHEQUE_TRANSACTION_FAILED',

  // Student Profile Slider Open
  SET_SLIDER_SCREEN: 'SET_SLIDER_SCREEN',

  // refresh online Transcation
  REFRESH_ONLINE_FEE_TRANSACTION_REQUESTED:
    'REFRESH_ONLINE_FEE_TRANSACTION_REQUESTED',
  REFRESH_ONLINE_FEE_TRANSACTION_SUCCEEDED:
    'REFRESH_ONLINE_FEE_TRANSACTION_SUCCEEDED',
  REFRESH_ONLINE_FEE_TRANSACTION_FAILED:
    'REFRESH_ONLINE_FEE_TRANSACTION_FAILED',
}

export default feeTransactionActionTypes
