export const CONTENT_ACTION_TYPES = {
  SET_LOADER: 'SET_LOADER',
  SET_PAGE: 'SET_PAGE',
  PAGE: 'PAGE',
  SET_CLASS: 'SET_CLASS',
  CLASS: 'CLASS',
  SET_SUBJECT: 'SET_SUBJECT',
  SUBJECT: 'SUBJECT',
  SET_TOPIC: 'SET_TOPIC',
  TOPIC: 'TOPIC',
  SET_CONTENT: 'SET_CONTENT',
  CONTENT: 'CONTENT',

  SET_CLASS_LIST: 'SET_CLASS_LIST',
  SET_SUJECT_LIST: 'SET_SUJECT_LIST',
  SET_TOPIC_LIST: 'SET_TOPIC_LIST',

  SET_LANGUAGE_LOADER: 'SET_LANGUAGE_LOADER',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_LANGUAGE_LIST: 'SET_LANGUAGE_LIST',

  SET_COURSE: 'SET_COURSE',
  CLEAR_CONTENT: 'CLEAR_CONTENT',
  CLEAR_TOPICS: 'CLEAR_TOPICS',

  FETCH_TAXONOY_REQUESTED: 'FETCH_TAXONOY_REQUESTED',
  FETCH_TAXONOY_SUCCESS: 'FETCH_TAXONOY_SUCCESS',
  FETCH_TAXONOY_FAILED: 'FETCH_TAXONOY_FAILED',

  FETCH_TAXONOY_CLASS_LIST_SUCCESS: 'FETCH_TAXONOY_CLASS_LIST_SUCCESS',

  FETCH_TAXONOY_SUBJECT_LIST_SUCCESS: 'FETCH_TAXONOY_SUBJECT_LIST_SUCCESS',

  SET_CONTENT_LIST_LOADER: 'SET_CONTENT_LIST_LOADER',
  FETCH_CONTENT_LIST_REQUEST: 'FETCH_CONTENT_LIST_REQUEST',
  FETCH_CONTENT_LIST_SUCCESS: 'FETCH_CONTENT_LIST_SUCCESS',
  FETCH_CONTENT_LIST_FAILED: 'FETCH_CONTENT_LIST_FAILED',

  FETCH_CONTENT: 'FETCH_CONTENT',

  FETCH_COURSE_LIST_SUCCESS: 'FETCH_COURSE_LIST_SUCCESS',

  FETCH_CONTENTLIST_LOAD_MORE_DATA: 'FETCH_CONTENTLIST_LOAD_MORE_DATA',

  SET_CONTENT_FOR_REPORT: 'SET_CONTENT_FOR_REPORT',
  REPORT_CONTENT_REQUEST: 'REPORT_CONTENT_REQUEST',
  REPORT_CONTENT_SUCCESS: 'REPORT_CONTENT_SUCCESS',
  REPORT_CONTENT_FAILED: 'REPORT_CONTENT_FAILED',
  SET_IS_CONTENT_REPORTED: 'SET_IS_CONTENT_REPORTED',
  RESET_STATE: 'RESET_STATE',
  CONTENT_ACCESS_CHECK_LOADER: 'CONTENT_ACCESS_CHECK_LOADER',
  CONTENT_ACCESS_CHECK_REQUESTED: 'CONTENT_ACCESS_CHECK_REQUESTED',
  CONTENT_ACCESS_CHECK_SUCCESS: 'CONTENT_ACCESS_CHECK_SUCCESS',
  CONTENT_ACCESS_CHECK_POPUP: 'CONTENT_ACCESS_CHECK_POPUP',

  SET_IS_VIDEO_MODAL_OPEN: 'SET_IS_VIDEO_MODAL_OPEN',
  IS_STUDY_MATERIAL_CONTENT_SET: 'IS_STUDY_MATERIAL_CONTENT_SET',
}
