export const CalendarInfoActionType = {
  FETCH_TAB_DATA_REQUEST: 'FETCH_TAB_DATA_REQUEST',
  FETCH_TAB_DATA_SUCCESS: 'FETCH_TAB_DATA_SUCCESS',
  FETCH_TAB_DATA_FAILURE: 'FETCH_TAB_DATA_FAILURE',
}

export const CalendarBannerInfoActionType = {
  FETCH_TAB_CALENDAR_DATA_REQUEST: 'FETCH_TAB_CALENDAR_DATA_REQUEST',
  FETCH_TAB_CALENDAR_DATA_SUCCESS: 'FETCH_TAB_CALENDAR_DATA_SUCCESS',
  FETCH_TAB_CALENDAR_DATA_FAILURE: 'FETCH_TAB_CALENDAR_DATA_FAILURE',
}

export const CreateCalendarItemTypes = {
  CREATE_CALENDAR_ITEM: 'CREATE_CALENDAR_ITEM',
  CREATE_CALENDAR_ITEM_SUCCESS: 'CREATE_CALENDAR_ITEM_SUCCESS',
  CREATE_CALENDAR_ITEM_FAILURE: 'CREATE_CALENDAR_ITEM_FAILURE',
}

export const DeleteCalendarItemTypes = {
  DELETE_CALENDAR_ITEM: 'DELETE_CALENDAR_ITEM',
  DELETE_CALENDAR_ITEM_SUCCESS: 'DELETE_CALENDAR_ITEM_SUCCESS',
  DELETE_CALENDAR_ITEM_FAILURE: 'DELETE_CALENDAR_ITEM_FAILURE',
}
