export const CERTIFICATE_EVENTS = {
  CERTIFICATE_STUDENT_TAB_CLICKED_TFI: 'CERTIFICATE_STUDENT_TAB_CLICKED_TFI',
  CERTIFICATE_STAFF_TAB_CLICKED_TFI: 'CERTIFICATE_STAFF_TAB_CLICKED_TFI',
  CERTIFICATE_CREATE_NEW_TEMPLATE_CLICKED_TFI:
    'CERTIFICATE_CREATE_NEW_TEMPLATE_CLICKED_TFI',
  CERTIFICATE_VIEW_ALL_DEFAULT_TEMPLATE_CLICKED_TFI:
    'CERTIFICATE_VIEW_ALL_DEFAULT_TEMPLATE_CLICKED_TFI',
  CERTIFICATE_TEMPLATE_SELECTED_TFI: 'CERTIFICATE_TEMPLATE_SELECTED_TFI',
  CERTIFICATE_NAME_CHECKBOX_CLICKED_TFI:
    'CERTIFICATE_NAME_CHECKBOX_CLICKED_TFI',
  CERTIFICATE_GENERATE_CLICKED_TFI: 'CERTIFICATE_GENERATE_CLICKED_TFI',
  CERTIFICATE_FILTER_CLICKED_TFI: 'CERTIFICATE_FILTER_CLICKED_TFI',
  CERTIFICATE_FILTER_APPLY_CLICKED_TFI: 'CERTIFICATE_FILTER_APPLY_CLICKED_TFI',
  CERTIFICATE_FILTER_CANCEL_CLICKED_TFI:
    'CERTIFICATE_FILTER_CANCEL_CLICKED_TFI',
  CERTIFICATE_TEMPLATE_NODE_CLICKED_TFI:
    'CERTIFICATE_TEMPLATE_NODE_CLICKED_TFI',
  CERTIFICATE_BULK_DOWNLOAD_CLICKED_TFI:
    'CERTIFICATE_BULK_DOWNLOAD_CLICKED_TFI',
  CERTIFICATE_DOWNLOADED_TFI: 'CERTIFICATE_DOWNLOADED_TFI',
  CERTIFICATE_TEMPLATE_EDIT_CLICKED_TFI:
    'CERTIFICATE_TEMPLATE_EDIT_CLICKED_TFI',
  CERTIFICATE_TEMPLATE_DOWNLOAD_CLICKED_TFI:
    'CERTIFICATE_TEMPLATE_DOWNLOAD_CLICKED_TFI',
  CERTIFICATE_TEMPLATE_NODE_ARCHIEVE_CLICKED_TFI:
    'CERTIFICATE_TEMPLATE_NODE_ARCHIEVE_CLICKED_TFI',
  CERTIFICATE_TEMPLATE_NODE_ARCHIEVE_POP_UP_CLICKED_TFI:
    'CERTIFICATE_TEMPLATE_NODE_ARCHIEVE_POP_UP_CLICKED_TFI',
  CERTIFICATE_TEMPLATE_NODE_ARCHIEVED_TFI:
    'CERTIFICATE_TEMPLATE_NODE_ARCHIEVED_TFI',
  CERTIFICATE_RECENTLY_GENERATED_VIEW_CLICKED_TFI:
    'CERTIFICATE_RECENTLY_GENERATED_VIEW_CLICKED_TFI',
  CERTIFICATE_REGENATE_CLICKED_TFI: 'CERTIFICATE_REGENATE_CLICKED_TFI',
  CERTIFICATE_PREVIEW_TEMPLATE_CLICKED_TFI:
    'CERTIFICATE_PREVIEW_TEMPLATE_CLICKED_TFI',
  CERTIFICATE_ADD_TEMPLATE_CLICKED_TFI: 'CERTIFICATE_ADD_TEMPLATE_CLICKED_TFI',
  CERTIFICATE_VIEW_ALL_TEMPLATE_CLICKED_TFI:
    'CERTIFICATE_VIEW_ALL_TEMPLATE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_NAME_FILLED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_NAME_FILLED_TFI',
  CERTIFICATE_NEW_TEMPLATE_DESCRIPTION_FILLED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_DESCRIPTION_FILLED_TFI',
  CERTIFICATE_NEW_TEMPLATE_PAPER_SIZE_SELECTED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_PAPER_SIZE_SELECTED_TFI',
  CERTIFICATE_NEW_TEMPLATE_ORIENTATION_SELECTED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_ORIENTATION_SELECTED_TFI',
  CERTIFICATE_NEW_TEMPLATE_ADD_PAGE_MARGIN_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_ADD_PAGE_MARGIN_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_CREATE_NOW_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_CREATE_NOW_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_BACKGROUND_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_BACKGROUND_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_IMAGE_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_IMAGE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_FIELDS_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_FIELDS_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_WATERMARK_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_WATERMARK_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_UPLOAD_BACKGROUND_IMAGE_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_UPLOAD_BACKGROUND_IMAGE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_UPLOAD_OTHER_IMAGE_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_UPLOAD_OTHER_IMAGE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_UPLOAD_BACKGROUND_IMAGE_POP_UP_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_UPLOAD_BACKGROUND_IMAGE_POP_UP_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_BACKGROUND_COLOUR_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_BACKGROUND_COLOUR_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_BACKGROUND_SELECTED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_BACKGROUND_SELECTED_TFI',
  CERTIFICATE_NEW_TEMPLATE_UPLOAD_IMAGE_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_UPLOAD_IMAGE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_ADD_MORE_IMAGE_POP_UP_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_ADD_MORE_IMAGE_POP_UP_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_FIELD_NODE_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_FIELD_NODE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_FIELD_USE_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_FIELD_USE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_ADD_CUSTOM_FIELD_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_ADD_CUSTOM_FIELD_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_ADD_CUSTOM_FIELD_POP_UP_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_ADD_CUSTOM_FIELD_POP_UP_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_UPLOAD_WATERMARK_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_UPLOAD_WATERMARK_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_SAVE_CLICKED_TFI:
    'CERTIFICATE_NEW_TEMPLATE_SAVE_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_SAVED_TFI: 'CERTIFICATE_NEW_TEMPLATE_SAVED_TFI',
  VIEW_OLD_CERTIFICATES_CLICKED_TFI: 'VIEW_OLD_CERTIFICATES_CLICKED_TFI',
  CERTIFICATE_NEW_TEMPLATE_EXIT_CLICKED:
    'CERTIFICATE_NEW_TEMPLATE_EXIT_CLICKED',
  CERTIFICATE_SELECT_ALL_CHECKBOX_CLICKED_TFI:
    'CERTIFICATE_SELECT_ALL_CHECKBOX_CLICKED_TFI',
  CERTIFICATE_GENERATE_CONFIRMATION_CLICKED_TFI:
    'CERTIFICATE_GENERATE_CONFIRMATION_CLICKED_TFI',
  DOWNLOAD_CERTIFICATE_CLICKED_TFI: 'DOWNLOAD_CERTIFICATE_CLICKED_TFI',
  PRINT_CERTIFICATE_CLICKED_TFI: 'PRINT_CERTIFICATE_CLICKED_TFI',
  PREVIEW_CLICKED_TFI: 'PREVIEW_CLICKED_TFI',
  CERTIFICATE_NEW_GENERATED_TFI: 'CERTIFICATE_NEW_GENERATED_TFI',
  CERTIFICATE_BACK_TO_LISTING_PAGE_CLICKED_TFI:
    'CERTIFICATE_BACK_TO_LISTING_PAGE_CLICKED_TFI',
}
