export const CertificateInfoActionType = {
  FETCH_CERTIFICATE_TAB_DATA_REQUEST: 'FETCH_CERTIFICATE_TAB_DATA_REQUEST',
  FETCH_CERTIFICATE_TAB_DATA_SUCCESS: 'FETCH_CERTIFICATE_TAB_DATA_SUCCESS',
  FETCH_CERTIFICATE_TAB_DATA_FAILURE: 'FETCH_CERTIFICATE_TAB_DATA_FAILURE',
  FETCH_CERTIFICATE_ALL_TAB_DATA: 'FETCH_CERTIFICATE_ALL_TAB_DATA',
}

export const StudentProfileDataActions = {
  FETCH_CERTIFICATE_STUDENT_DATA_REQUEST:
    'FETCH_CERTIFICATE_STUDENT_DATA_REQUEST',
  FETCH_CERTIFICATE_STUDENT_DATA_SUCCESS:
    'FETCH_CERTIFICATE_STUDENT_DATA_SUCCESS',
  FETCH_CERTIFICATE_STUDENT_DATA_FAILURE:
    'FETCH_CERTIFICATE_STUDENT_DATA_FAILURE',
}

export const CreateCertificateItemTypes = {
  GENERATE_CERTIFICATE_ITEM: 'GENERATE_CERTIFICATE_ITEM',
  GENERATE_CERTIFICATE_ITEM_SUCCESS: 'GENERATE_CERTIFICATE_ITEM_SUCCESS',
  GENERATE_CERTIFICATE_ITEM_FAILURE: 'GENERATE_CERTIFICATE_ITEM_FAILURE',
  GENERATE_CERTIFICATE_ITEM_LOADING: 'GENERATE_CERTIFICATE_ITEM_LOADING',
}

export const CertificateActions = {
  SET_CERTIFICATE_TYPE: 'SET_CERTIFICATE_TYPE',
  SET_STUDENT_INFO: 'SET_STUDENT_INFO',
  SET_PDF_URL: 'SET_PDF_URL',
  SET_TC_INFO: 'SET_TC_INFO',
}
