export const StaffAttendanceActionType = {
  SET_GENERAL_STAFF_ATTENDANCE_LOADER: 'SET_GENERAL_STAFF_ATTENDANCE_LOADER',

  // Staff Attendance general action types
  STAFF_ATTENDANCE_DATES: 'STAFF_ATTENDANCE_DATES',
  STAFF_ATTENDANCE_UTC_TIMESTAMP: 'STAFF_ATTENDANCE_UTC_TIMESTAMP',
  STAFF_ATTENDANCE_UI_STATES_MANAGE: 'STAFF_ATTENDANCE_UI_STATES_MANAGE',
  STAFF_ATTENDANCE_SEARCH_TERM: 'STAFF_ATTENDANCE_SEARCH_TERM',
  STAFF_ATTENDANCE_SELECTED_TAB: 'STAFF_ATTENDANCE_SELECTED_TAB',
  STAFF_ATTENDANCE_PRESENT_ABSENT_COUNT:
    'STAFF_ATTENDANCE_PRESENT_ABSENT_COUNT',

  // Get Staff List action types
  GET_STAFF_DETAILS_LIST: 'GET_STAFF_DETAILS_LIST',
  STAFF_ATTENDANCE_FILTERS: 'STAFF_ATTENDANCE_FILTERS',
  GET_STAFF_FILTERS_LIST: 'GET_STAFF_FILTERS_LIST',
  STAFF_LIST_GET_SUCCEEDED: 'STAFF_LIST_GET_SUCCEEDED',
  STAFF_LIST_GET_FAILED: 'STAFF_LIST_GET_FAILED',

  // Get Staff Attendance list action types
  GET_STAFF_ATTENDANCE_LIST: 'GET_STAFF_ATTENDANCE_LIST',
  STAFF_ATTENDANCE_LIST_WITH_STATUS: 'STAFF_ATTENDANCE_LIST_WITH_STATUS',
  STAFF_ATTENDANCE_LIST_GET_SUCCEEDED: 'STAFF_ATTENDANCE_LIST_GET_SUCCEEDED',
  STAFF_ATTENDANCE_LIST_GET_FAILED: 'STAFF_ATTENDANCE_LIST_GET_FAILED',

  // Staff Attendance submit action types
  STAFF_ATTENDANCE_SUBMIT_REQUEST: 'STAFF_ATTENDANCE_SUBMIT_REQUEST',
  STAFF_ATTENDANCE_SUBMIT_SUCCEEDED: 'STAFF_ATTENDANCE_SUBMIT_SUCCEEDED',
  STAFF_ATTENDANCE_SUBMIT_FAILED: 'STAFF_ATTENDANCE_SUBMIT_FAILED',

  // Staff Attendance report download action types
  STAFF_ATTENDANCE_DOWNLOAD_REPORT_REQUEST:
    'STAFF_ATTENDANCE_DOWNLOAD_REPORT_REQUEST',
  STAFF_ATTENDANCE_DOWNLOAD_REPORT_SUCCESSDED:
    'STAFF_ATTENDANCE_DOWNLOAD_REPORT_SUCCESSDED',
  STAFF_ATTENDANCE_DOWNLOAD_REPORT_FAILED:
    'STAFF_ATTENDANCE_DOWNLOAD_REPORT_FAILED',
}

export const MARK_INDIVIDUAL_ATTENDANCE_STATUS =
  'MARK_INDIVIDUAL_ATTENDANCE_STATUS'

export const REVERT_MARKED_INDIVIDUAL_ATTENDANCE_STATUS =
  'REVERT_MARKED_INDIVIDUAL_ATTENDANCE_STATUS'

export const UPDATE_ALL_ATTENDANCE = 'UPDATE_ALL_ATTENDANCE'
export const EDIT_ATTENDANCE = 'EDIT_ATTENDANCE'

export const FETCH_LEAVE_DETAILS = 'FETCH_LEAVE_DETAILS'
export const FETCH_LEAVE_DETAILS_SUCCESS = 'FETCH_LEAVE_DETAILS_SUCCESS'
export const FETCH_LEAVE_DETAILS_FAILED = 'FETCH_LEAVE_DETAILS_FAILED'
export const GET_STAFF_ATTENDANCE = 'GET_STAFF_ATTENDANCE'
export const SYNC_STAFF_ATTENDANCE = 'SYNC_STAFF_ATTENDANCE'
