name: Sync translations CI

on:
    workflow_dispatch:
        inputs:
            releaseBranch:
                description: "Release branch"
                required: true

jobs:
    sync_translations:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Get release branch name
              id: release_branch
              run: |
                  echo "release_branch=${{ github.ref }}" >> "$GITHUB_OUTPUT"

            - name: Create sync branch
              id: create_sync_branch
              run: |
                  sync_branch="sync-translation-${GITHUB_RUN_NUMBER}"
                  git checkout -b $sync_branch
                  git push origin $sync_branch
                  echo "sync_branch=$sync_branch" >> "$GITHUB_OUTPUT"

            - name: Install dependencies
              run: npm install

            - name: Run sync translation script
              run: node index.js

            - name: git status
              run: |
                  git status

            - name: Check for changes and stop workflow if no changes
              id: changes_check
              run: |
                  if git diff --quiet HEAD; then
                    echo "No files have changed"
                  else
                    echo "has_changes=true" >> "$GITHUB_OUTPUT"
                    echo "Translation files are updated"
                  fi

            - name: Add and commit changes to translation files
              if: steps.changes_check.outputs.has_changes == 'true'
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add result.json
                  git commit -m "Auto update - translation files"
                  echo $steps.changes_check.outputs.has_changes
                  echo steps.changes_check.outputs.has_changes

            - name: Push changes
              if: steps.changes_check.outputs.has_changes == 'true'
              uses: ad-m/github-push-action@master
              with:
                  branch: ${{ steps.create_sync_branch.outputs.sync_branch }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Pull Request
              if: steps.changes_check.outputs.has_changes == 'true'
              uses: peter-evans/create-pull-request@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ${{ inputs.releaseBranch }}
                  branch: ${{ steps.create_sync_branch.outputs.sync_branch }}
                  title: "Sync Translation Changes"
                  body: "This pull request is automatically generated to sync translation changes."
                  labels: "auto-generated"
